<?php
namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --mode=table --tables=skills
         *
         */

        $dataTables = [
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8F5E9',
                'skill_color' => '#4CAF50',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar mengucap syukur atas nikmat kecil.',
                'skill_emoji' => '🤲',
                'skill_evaluasi' => '["Apakah anak mengucap syukur saat menerima sesuatu?","Apakah anak tidak mudah mengeluh tentang makanan atau mainan?","Apakah anak bisa menghargai pemberian orang lain?","Apakah anak senang berbagi dengan teman?","Apakah anak mengucap terima kasih tanpa diminta?"]',
                'skill_id' => 1,
                'skill_key' => 'bersyukur',
                'skill_pilars' => '["spiritual"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 1,
                'skill_title' => 'Bersyukur',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8F5E9',
                'skill_color' => '#4CAF50',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar ikhlas meskipun sulit.',
                'skill_emoji' => '🫶',
                'skill_evaluasi' => '["Apakah anak bisa menerima keadaan dengan lapang dada?","Apakah anak tidak mudah marah saat tidak mendapat keinginannya?","Apakah anak bisa mengikhlaskan mainan yang rusak?","Apakah anak tidak terlalu memaksakan kehendak?","Apakah anak bisa menerima kekalahan dengan baik?"]',
                'skill_id' => 2,
                'skill_key' => 'ikhlas',
                'skill_pilars' => '["spiritual"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 2,
                'skill_title' => 'Ikhlas',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8F5E9',
                'skill_color' => '#4CAF50',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar berkata jujur meskipun sulit.',
                'skill_emoji' => '🤝',
                'skill_evaluasi' => '["Apakah anak mengakui kesalahan tanpa takut dihukum?","Apakah anak bercerita dengan jujur tentang kegiatannya?","Apakah anak tidak mengambil barang orang lain?","Apakah anak berani mengatakan kebenaran meskipun sulit?","Apakah anak tidak berbohong untuk menghindari masalah?"]',
                'skill_id' => 3,
                'skill_key' => 'jujur',
                'skill_pilars' => '["spiritual"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 3,
                'skill_title' => 'Jujur',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8F5E9',
                'skill_color' => '#4CAF50',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar tidak sombong dan menghargai orang lain.',
                'skill_emoji' => '🙇',
                'skill_evaluasi' => '["Apakah anak tidak suka pamer?","Apakah anak mau mendengarkan pendapat orang lain?","Apakah anak tidak merendahkan teman?","Apakah anak mau belajar dari siapa saja?","Apakah anak menghargai semua orang tanpa memandang?"]',
                'skill_id' => 4,
                'skill_key' => 'rendah_hati',
                'skill_pilars' => '["spiritual"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 4,
                'skill_title' => 'Rendah Hati',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8F5E9',
                'skill_color' => '#4CAF50',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar menghargai perbedaan.',
                'skill_emoji' => '☮️',
                'skill_evaluasi' => '["Apakah anak tidak mengejek teman yang berbeda?","Apakah anak mau berteman dengan siapa saja?","Apakah anak bisa bermain dengan teman berbeda latar belakang?","Apakah anak tidak memilih-milih teman?","Apakah anak menghargai keunikan orang lain?"]',
                'skill_id' => 5,
                'skill_key' => 'toleransi',
                'skill_pilars' => '["spiritual"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 5,
                'skill_title' => 'Toleransi',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8F5E9',
                'skill_color' => '#4CAF50',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar bersikap sopan santun.',
                'skill_emoji' => '🙏',
                'skill_evaluasi' => '["Apakah anak menggunakan kata tolong dan terima kasih?","Apakah anak tidak berkata kasar?","Apakah anak sopan saat bertemu orang dewasa?","Apakah anak tidak membantah saat dinasehati?","Apakah anak meminta izin sebelum melakukan sesuatu?"]',
                'skill_id' => 6,
                'skill_key' => 'sopan',
                'skill_pilars' => '["kebiasaan"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 6,
                'skill_title' => 'Sopan',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8F5E9',
                'skill_color' => '#4CAF50',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar mengucap terima kasih.',
                'skill_emoji' => '🙏',
                'skill_evaluasi' => '["Apakah anak mengucap terima kasih saat dibantu?","Apakah anak menghargai pemberian orang lain?","Apakah anak tidak menganggap bantuan sebagai hal biasa?","Apakah anak mengucap terima kasih ke guru?","Apakah anak berterima kasih pada orang tua?"]',
                'skill_id' => 7,
                'skill_key' => 'berterima_kasih',
                'skill_pilars' => '["kebiasaan"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 7,
                'skill_title' => 'Berterima Kasih',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8F5E9',
                'skill_color' => '#4CAF50',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar memaafkan kesalahan orang lain.',
                'skill_emoji' => '💚',
                'skill_evaluasi' => '["Apakah anak bisa memaafkan teman yang berbuat salah?","Apakah anak tidak menyimpan dendam?","Apakah anak bisa melupakan kesalahan kecil?","Apakah anak tidak mengungkit kesalahan lama?","Apakah anak mau bermain lagi setelah bertengkar?"]',
                'skill_id' => 9,
                'skill_key' => 'memaafkan',
                'skill_pilars' => '["kebiasaan"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 9,
                'skill_title' => 'Memaafkan',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8F5E9',
                'skill_color' => '#4CAF50',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar meminta tolong saat membutuhkan.',
                'skill_emoji' => '🙋',
                'skill_evaluasi' => '["Apakah anak mau meminta tolong saat kesulitan?","Apakah anak menggunakan kata tolong dengan sopan?","Apakah anak tidak malu minta bantuan?","Apakah anak bisa menjelaskan apa yang dibutuhkan?","Apakah anak berterima kasih setelah dibantu?"]',
                'skill_id' => 10,
                'skill_key' => 'meminta_tolong',
                'skill_pilars' => '["kebiasaan"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 10,
                'skill_title' => 'Meminta Tolong',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8F5E9',
                'skill_color' => '#4CAF50',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar membantu orang di sekitarnya.',
                'skill_emoji' => '💛',
                'skill_evaluasi' => '["Apakah anak menolong teman yang kesulitan?","Apakah anak peduli dengan perasaan orang lain?","Apakah anak mau berbagi mainan atau makanan?","Apakah anak senang membantu pekerjaan rumah?","Apakah anak menunjukkan kasih sayang pada hewan?"]',
                'skill_id' => 11,
                'skill_key' => 'peduli_sesama',
                'skill_pilars' => '["sosial"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 11,
                'skill_title' => 'Peduli Sesama',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#FFF3E0',
                'skill_color' => '#FF9800',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar mencoba lagi saat gagal.',
                'skill_emoji' => '💪',
                'skill_evaluasi' => '["Apakah anak terus mencoba saat gagal?","Apakah anak tidak mudah marah saat kesulitan?","Apakah anak mau belajar hal baru meskipun sulit?","Apakah anak tidak langsung menyerah saat tugas berat?","Apakah anak termotivasi untuk memperbaiki kesalahan?"]',
                'skill_id' => 12,
                'skill_key' => 'pantang_menyerah',
                'skill_pilars' => '["karakter"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 1,
                'skill_title' => 'Pantang Menyerah',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#FFF3E0',
                'skill_color' => '#FF9800',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar menyampaikan pendapat.',
                'skill_emoji' => '🗣️',
                'skill_evaluasi' => '["Apakah anak berani menyampaikan pendapat?","Apakah anak tidak malu bertanya di depan kelas?","Apakah anak bisa menjelaskan keinginannya dengan jelas?","Apakah anak berani berbicara dengan orang baru?","Apakah anak tidak takut tampil di depan umum?"]',
                'skill_id' => 13,
                'skill_key' => 'pemberani',
                'skill_pilars' => '["karakter"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 2,
                'skill_title' => 'Pemberani',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#FFF3E0',
                'skill_color' => '#FF9800',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar menghadapi tantangan baru.',
                'skill_emoji' => '🔥',
                'skill_evaluasi' => '["Apakah anak mau mencoba makanan baru?","Apakah anak tertarik dengan kegiatan yang belum pernah dicoba?","Apakah anak tidak takut mencoba permainan baru?","Apakah anak mau mencoba sendiri sebelum minta bantuan?","Apakah anak senang dengan tantangan baru?"]',
                'skill_id' => 14,
                'skill_key' => 'mau_mencoba',
                'skill_pilars' => '["karakter"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 3,
                'skill_title' => 'Mau Mencoba',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[4,5,6,7,8,9,10,11]',
                'skill_bg' => '#FFF3E0',
                'skill_color' => '#FF9800',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar bertanggung jawab atas tugasnya.',
                'skill_emoji' => '🎯',
                'skill_evaluasi' => '["Apakah anak menyelesaikan pekerjaan yang dimulai?","Apakah anak tidak meninggalkan mainan begitu saja?","Apakah anak bisa fokus pada satu tugas sampai selesai?","Apakah anak ingat tanggung jawabnya tanpa diingatkan?","Apakah anak merasa puas saat menyelesaikan sesuatu?"]',
                'skill_id' => 15,
                'skill_key' => 'bertanggung_jawab',
                'skill_pilars' => '["karakter"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 4,
                'skill_title' => 'Bertanggung Jawab',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[5,6,7,8,9,10,11]',
                'skill_bg' => '#FFF3E0',
                'skill_color' => '#FF9800',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar memimpin dan mengambil keputusan.',
                'skill_emoji' => '👑',
                'skill_evaluasi' => '["Apakah anak mau memimpin kegiatan kelompok?","Apakah anak bisa mengambil keputusan dengan percaya diri?","Apakah anak tidak takut bertanggung jawab atas pilihannya?","Apakah anak bisa mengorganisir teman-temannya?","Apakah anak memberi contoh yang baik?"]',
                'skill_id' => 16,
                'skill_key' => 'leadership',
                'skill_pilars' => '["karakter"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 5,
                'skill_title' => 'Leadership',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E3F2FD',
                'skill_color' => '#2196F3',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar menemukan ide baru.',
                'skill_emoji' => '🎨',
                'skill_evaluasi' => '["Apakah anak suka menggambar atau membuat kerajinan?","Apakah anak punya imajinasi yang kreatif saat bermain?","Apakah anak bisa menemukan solusi unik untuk masalah?","Apakah anak senang bereksperimen dengan bahan baru?","Apakah anak suka bercerita atau membuat cerita?"]',
                'skill_id' => 17,
                'skill_key' => 'berpikir_kreatif',
                'skill_pilars' => '["kreatifitas"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 1,
                'skill_title' => 'Berpikir Kreatif',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E3F2FD',
                'skill_color' => '#2196F3',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar mencoba hal baru dengan rasa ingin tahu.',
                'skill_emoji' => '🔬',
                'skill_evaluasi' => '["Apakah anak bertanya mengapa tentang hal di sekitarnya?","Apakah anak suka mencoba dan mengamati hasilnya?","Apakah anak senang dengan percobaan sederhana?","Apakah anak punya rasa ingin tahu yang tinggi?","Apakah anak suka mengamati alam dan hewan?"]',
                'skill_id' => 18,
                'skill_key' => 'eksperimen',
                'skill_pilars' => '["kreatifitas"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 2,
                'skill_title' => 'Eksperimen',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E3F2FD',
                'skill_color' => '#2196F3',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar mencari solusi sendiri.',
                'skill_emoji' => '🧩',
                'skill_evaluasi' => '["Apakah anak bisa menyelesaikan puzzle atau teka-teki?","Apakah anak berpikir sebelum bertindak?","Apakah anak mencari cara sendiri untuk mengatasi kesulitan?","Apakah anak bisa menyusun strategi sederhana?","Apakah anak belajar dari kesalahan sebelumnya?"]',
                'skill_id' => 19,
                'skill_key' => 'memecahkan_masalah',
                'skill_pilars' => '["kreatifitas"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 3,
                'skill_title' => 'Memecahkan Masalah',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E3F2FD',
                'skill_color' => '#2196F3',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar menggunakan daya imajinasinya.',
                'skill_emoji' => '✨',
                'skill_evaluasi' => '["Apakah anak suka bermain peran?","Apakah anak bisa membuat cerita dari imajinasinya?","Apakah anak punya teman khayalan atau dunia imajinasi?","Apakah anak suka bermain dengan benda seolah-olah benda lain?","Apakah anak senang mendengarkan atau membaca dongeng?"]',
                'skill_id' => 20,
                'skill_key' => 'berimajinasi',
                'skill_pilars' => '["kreatifitas"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 4,
                'skill_title' => 'Berimajinasi',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E3F2FD',
                'skill_color' => '#2196F3',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar hal baru dengan semangat.',
                'skill_emoji' => '🌟',
                'skill_evaluasi' => '["Apakah anak senang belajar hal yang belum diketahui?","Apakah anak tidak takut mencoba aktivitas baru?","Apakah anak punya rasa penasaran yang tinggi?","Apakah anak suka bertanya tentang hal baru?","Apakah anak antusias saat diajarkan sesuatu?"]',
                'skill_id' => 21,
                'skill_key' => 'belajar_hal_baru',
                'skill_pilars' => '["kreatifitas"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 5,
                'skill_title' => 'Belajar Hal Baru',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#F3E5F5',
                'skill_color' => '#9C27B0',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar berkonsentrasi pada satu hal.',
                'skill_emoji' => '🎯',
                'skill_evaluasi' => '["Apakah anak bisa duduk tenang selama 15 menit?","Apakah anak tidak mudah terganggu saat mengerjakan sesuatu?","Apakah anak bisa mendengarkan cerita sampai selesai?","Apakah anak fokus saat mengerjakan tugas sekolah?","Apakah anak tidak sering melamun saat diajak bicara?"]',
                'skill_id' => 22,
                'skill_key' => 'fokus',
                'skill_pilars' => '["disiplin"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 1,
                'skill_title' => 'Fokus',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[4,5,6,7,8,9,10,11]',
                'skill_bg' => '#F3E5F5',
                'skill_color' => '#9C27B0',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar mengelola waktunya.',
                'skill_emoji' => '⏰',
                'skill_evaluasi' => '["Apakah anak tahu kapan waktunya belajar dan bermain?","Apakah anak tidak terlambat bangun tidur?","Apakah anak bisa menyelesaikan tugas tepat waktu?","Apakah anak tidak terlalu lama menonton layar?","Apakah anak punya rutinitas harian yang teratur?"]',
                'skill_id' => 23,
                'skill_key' => 'mengatur_waktu',
                'skill_pilars' => '["disiplin"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 2,
                'skill_title' => 'Mengatur Waktu',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#F3E5F5',
                'skill_color' => '#9C27B0',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar konsisten belajar setiap hari.',
                'skill_emoji' => '📖',
                'skill_evaluasi' => '["Apakah anak mau belajar tanpa disuruh?","Apakah anak punya jadwal belajar yang konsisten?","Apakah anak senang membaca buku?","Apakah anak mau mengulang pelajaran yang sudah dipelajari?","Apakah anak menunjukkan kemajuan dalam belajar?"]',
                'skill_id' => 24,
                'skill_key' => 'mau_dan_suka_belajar',
                'skill_pilars' => '["kebiasaan"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 3,
                'skill_title' => 'Mau dan Suka Belajar',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#F3E5F5',
                'skill_color' => '#9C27B0',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar menyelesaikan apa yang sudah dimulai.',
                'skill_emoji' => '🔁',
                'skill_evaluasi' => '["Apakah anak menyelesaikan tugas yang sudah dimulai?","Apakah anak tidak mudah menyerah di tengah jalan?","Apakah anak konsisten dengan jadwal belajarnya?","Apakah anak bisa fokus pada satu kegiatan sampai selesai?","Apakah anak tidak sering berpindah-pindah kegiatan?"]',
                'skill_id' => 55,
                'skill_key' => 'konsisten',
                'skill_pilars' => '["disiplin"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 6,
                'skill_title' => 'Konsisten',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#F3E5F5',
                'skill_color' => '#9C27B0',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar mengikuti kesepakatan.',
                'skill_emoji' => '✅',
                'skill_evaluasi' => '["Apakah anak mengikuti aturan di rumah?","Apakah anak patuh di sekolah?","Apakah anak tidak melanggar kesepakatan yang sudah dibuat?","Apakah anak mengerti konsekuensi dari perbuatannya?","Apakah anak bisa menunggu giliran?"]',
                'skill_id' => 25,
                'skill_key' => 'patuh_aturan',
                'skill_pilars' => '["disiplin"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 4,
                'skill_title' => 'Patuh Aturan',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[4,5,6,7,8,9,10,11]',
                'skill_bg' => '#F3E5F5',
                'skill_color' => '#9C27B0',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar bangun pagi dengan teratur.',
                'skill_emoji' => '🌅',
                'skill_evaluasi' => '["Apakah anak bangun pagi tanpa disuruh?","Apakah anak tidak sering terlambat?","Apakah anak punya rutinitas pagi yang teratur?","Apakah anak langsung mandi setelah bangun?","Apakah anak sarapan sebelum beraktivitas?"]',
                'skill_id' => 26,
                'skill_key' => 'bangun_pagi',
                'skill_pilars' => '["kesehatan"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 5,
                'skill_title' => 'Bangun Pagi',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[5,6,7,8,9,10,11]',
                'skill_bg' => '#E8EAF6',
                'skill_color' => '#3F51B5',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar menyiapkan makanan sendiri.',
                'skill_emoji' => '🍳',
                'skill_evaluasi' => '["Apakah anak mau membantu di dapur?","Apakah anak bisa menyiapkan makanan sederhana?","Apakah anak berhati-hati saat menggunakan alat dapur?","Apakah anak senang mencoba resep baru?","Apakah anak bisa membersihkan setelah memasak?"]',
                'skill_id' => 27,
                'skill_key' => 'masak_sederhana',
                'skill_pilars' => '["kemandirian"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 1,
                'skill_title' => 'Masak Sederhana',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8EAF6',
                'skill_color' => '#3F51B5',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar merapikan barangnya.',
                'skill_emoji' => '🧹',
                'skill_evaluasi' => '["Apakah anak merapikan mainan setelah bermain?","Apakah anak bisa merapikan tempat tidurnya sendiri?","Apakah anak tidak meninggalkan barang sembarangan?","Apakah anak mau membantu merapikan rumah?","Apakah anak tahu di mana barang-barangnya disimpan?"]',
                'skill_id' => 28,
                'skill_key' => 'beres_beres',
                'skill_pilars' => '["kemandirian"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 2,
                'skill_title' => 'Beres-beres',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8EAF6',
                'skill_color' => '#3F51B5',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar mandi dan sikat gigi sendiri.',
                'skill_emoji' => '🚿',
                'skill_evaluasi' => '["Apakah anak bisa mandi sendiri?","Apakah anak sikat gigi tanpa disuruh?","Apakah anak cuci tangan sebelum makan?","Apakah anak bisa memilih baju sendiri?","Apakah anak menjaga kebersihan pakaiannya?"]',
                'skill_id' => 29,
                'skill_key' => 'mengurus_diri',
                'skill_pilars' => '["kemandirian"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 3,
                'skill_title' => 'Mengurus Diri',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[6,7,8,9,10,11]',
                'skill_bg' => '#E8EAF6',
                'skill_color' => '#3F51B5',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar menabung dan berhemat.',
                'skill_emoji' => '💰',
                'skill_evaluasi' => '["Apakah anak punya celengan atau tabungan?","Apakah anak tidak boros jajan?","Apakah anak bisa membedakan kebutuhan dan keinginan?","Apakah anak senang menabung?","Apakah anak menghargai uang?"]',
                'skill_id' => 30,
                'skill_key' => 'keuangan',
                'skill_pilars' => '["kemandirian"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 4,
                'skill_title' => 'Keuangan',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8EAF6',
                'skill_color' => '#3F51B5',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar tata cara makan yang baik.',
                'skill_emoji' => '🍽️',
                'skill_evaluasi' => '["Apakah anak cuci tangan sebelum makan?","Apakah anak tidak berbicara saat mulut penuh?","Apakah anak tidak membuang makanan?","Apakah anak bisa makan sendiri dengan rapi?","Apakah anak berdoa sebelum makan?"]',
                'skill_id' => 32,
                'skill_key' => 'tata_cara_makan',
                'skill_pilars' => '["kemandirian"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 6,
                'skill_title' => 'Tata Cara Makan',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#EFEBE9',
                'skill_color' => '#8D6E63',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar membagi dengan orang lain.',
                'skill_emoji' => '🎁',
                'skill_evaluasi' => '["Apakah anak mau berbagi mainan dengan teman?","Apakah anak senang memberi makanan ke orang lain?","Apakah anak tidak pelit dengan barangnya?","Apakah anak bisa bermain gantian?","Apakah anak senang membantu teman yang membutuhkan?"]',
                'skill_id' => 33,
                'skill_key' => 'berbagi',
                'skill_pilars' => '["sosial"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 1,
                'skill_title' => 'Berbagi',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#EFEBE9',
                'skill_color' => '#8D6E63',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar bekerja sama dalam tim.',
                'skill_emoji' => '👫',
                'skill_evaluasi' => '["Apakah anak bisa bermain bersama tanpa bertengkar?","Apakah anak mau bergantian saat bermain?","Apakah anak bisa mengikuti aturan kelompok?","Apakah anak senang bekerja sama dalam tim?","Apakah anak tidak mendominasi saat bermain?"]',
                'skill_id' => 34,
                'skill_key' => 'kerja_sama',
                'skill_pilars' => '["sosial"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 2,
                'skill_title' => 'Kerja Sama',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#EFEBE9',
                'skill_color' => '#8D6E63',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar mendengarkan orang lain.',
                'skill_emoji' => '👂',
                'skill_evaluasi' => '["Apakah anak mendengarkan saat orang lain bicara?","Apakah anak tidak memotong pembicaraan?","Apakah anak bisa mengikuti instruksi sederhana?","Apakah anak memperhatikan saat guru menjelaskan?","Apakah anak tidak cuek saat diajak bicara?"]',
                'skill_id' => 35,
                'skill_key' => 'mendengarkan',
                'skill_pilars' => '["sosial"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 3,
                'skill_title' => 'Mendengarkan',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#EFEBE9',
                'skill_color' => '#8D6E63',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar memahami perasaan orang lain.',
                'skill_emoji' => '💗',
                'skill_evaluasi' => '["Apakah anak bisa merasakan kesedihan teman?","Apakah anak menolong teman yang menangis?","Apakah anak tidak mengejek orang lain?","Apakah anak peduli dengan perasaan adik atau kakak?","Apakah anak senang menghibur orang yang sedih?"]',
                'skill_id' => 36,
                'skill_key' => 'empati',
                'skill_pilars' => '["sosial"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 4,
                'skill_title' => 'Empati',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#FFEBEE',
                'skill_color' => '#F44336',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar mengenal perasaannya.',
                'skill_emoji' => '😊',
                'skill_evaluasi' => '["Apakah anak bisa menyebutkan perasaannya?","Apakah anak tahu kapan ia sedih atau senang?","Apakah anak bisa mengenali wajah marah dan senang?","Apakah anak bercerita tentang perasaannya?","Apakah anak tidak bingung dengan emosinya?"]',
                'skill_id' => 37,
                'skill_key' => 'mengenali_emosi',
                'skill_pilars' => '["emosi"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 1,
                'skill_title' => 'Mengenali Emosi',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#FFEBEE',
                'skill_color' => '#F44336',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar mengelola emosi dengan baik.',
                'skill_emoji' => '😤',
                'skill_evaluasi' => '["Apakah anak tidak mudah marah berlebihan?","Apakah anak bisa menenangkan diri sendiri?","Apakah anak tidak memukul saat marah?","Apakah anak bisa mengungkapkan marah dengan kata-kata?","Apakah anak tidak merusak barang saat kesal?"]',
                'skill_id' => 38,
                'skill_key' => 'mengelola_emosi',
                'skill_pilars' => '["emosi"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 2,
                'skill_title' => 'Mengelola Emosi',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#FFEBEE',
                'skill_color' => '#F44336',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar menyalurkan emosi dengan cara yang sehat.',
                'skill_emoji' => '🎨',
                'skill_evaluasi' => '["Apakah anak bisa menyalurkan emosi melalui kegiatan positif?","Apakah anak tidak melampiaskan emosi dengan cara negatif?","Apakah anak punya cara sendiri untuk menenangkan diri?","Apakah anak bisa menggambar atau menulis saat sedih?","Apakah anak senang berolahraga saat emosi?"]',
                'skill_id' => 39,
                'skill_key' => 'merelease_emosi',
                'skill_pilars' => '["emosi"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 3,
                'skill_title' => 'Merelease Emosi',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#FFEBEE',
                'skill_color' => '#F44336',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar bercerita ke orang tua.',
                'skill_emoji' => '💬',
                'skill_evaluasi' => '["Apakah anak bercerita tentang kegiatannya di sekolah?","Apakah anak tidak menyimpan masalah sendiri?","Apakah anak berani bilang jika ada masalah?","Apakah anak mau menceritakan perasaannya?","Apakah anak tidak takut bicara dengan orang tua?"]',
                'skill_id' => 40,
                'skill_key' => 'komunikasi_keluarga',
                'skill_pilars' => '["keluarga"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 4,
                'skill_title' => 'Komunikasi Keluarga',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#FFEBEE',
                'skill_color' => '#F44336',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar menikmati waktu bersama keluarga.',
                'skill_emoji' => '👨‍👩‍👧',
                'skill_evaluasi' => '["Apakah anak senang menghabiskan waktu dengan keluarga?","Apakah anak tidak lebih memilih gadget daripada keluarga?","Apakah anak mau ikut kegiatan keluarga?","Apakah anak bercerita tentang harinya?","Apakah anak terlihat bahagia saat bersama keluarga?"]',
                'skill_id' => 41,
                'skill_key' => 'quality_time',
                'skill_pilars' => '["keluarga"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 5,
                'skill_title' => 'Quality Time',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E0F2F1',
                'skill_color' => '#009688',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar memilih makanan bergizi.',
                'skill_emoji' => '🥗',
                'skill_evaluasi' => '["Apakah anak mau makan sayur dan buah?","Apakah anak tidak terlalu banyak makanan manis?","Apakah anak sarapan sebelum beraktivitas?","Apakah anak minum air putih yang cukup?","Apakah anak tidak terlalu sering jajan sembarangan?"]',
                'skill_id' => 42,
                'skill_key' => 'makan_sehat',
                'skill_pilars' => '["kesehatan"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 1,
                'skill_title' => 'Makan Sehat',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E0F2F1',
                'skill_color' => '#009688',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar tidur tepat waktu.',
                'skill_emoji' => '😴',
                'skill_evaluasi' => '["Apakah anak tidur tepat waktu?","Apakah anak tidak sering begadang?","Apakah anak bangun dengan segar di pagi hari?","Apakah anak punya rutinitas tidur yang teratur?","Apakah anak tidak terlalu lama main gadget sebelum tidur?"]',
                'skill_id' => 43,
                'skill_key' => 'tidur_teratur',
                'skill_pilars' => '["kesehatan"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 2,
                'skill_title' => 'Tidur Teratur',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E0F2F1',
                'skill_color' => '#009688',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar aktif bergerak setiap hari.',
                'skill_emoji' => '🏃',
                'skill_evaluasi' => '["Apakah anak aktif bergerak setiap hari?","Apakah anak senang bermain di luar?","Apakah anak tidak malas bergerak?","Apakah anak bisa berlari dan melompat dengan baik?","Apakah anak punya olahraga favorit?"]',
                'skill_id' => 44,
                'skill_key' => 'olahraga_teratur',
                'skill_pilars' => '["kesehatan"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 3,
                'skill_title' => 'Olahraga Teratur',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E0F2F1',
                'skill_color' => '#009688',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar menjaga kebersihan sekitar.',
                'skill_emoji' => '🌿',
                'skill_evaluasi' => '["Apakah anak tidak membuang sampah sembarangan?","Apakah anak mau membersihkan lingkungan?","Apakah anak peduli dengan kebersihan taman?","Apakah anak tahu cara memilah sampah?","Apakah anak senang menanam tanaman?"]',
                'skill_id' => 45,
                'skill_key' => 'kebersihan_lingkungan',
                'skill_pilars' => '["kesehatan"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 4,
                'skill_title' => 'Kebersihan Lingkungan',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E0F2F1',
                'skill_color' => '#009688',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar menjaga dan melestarikan alam.',
                'skill_emoji' => '🌍',
                'skill_evaluasi' => '["Apakah anak tidak merusak tanaman?","Apakah anak senang bermain di alam?","Apakah anak peduli dengan hewan di sekitarnya?","Apakah anak tidak membuang sampah ke sungai?","Apakah anak mau menanam pohon?"]',
                'skill_id' => 46,
                'skill_key' => 'menjaga_alam',
                'skill_pilars' => '["kebiasaan"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 5,
                'skill_title' => 'Menjaga Alam',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#FFF3E0',
                'skill_color' => '#FF9800',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar peduli dengan lingkungan sekitar.',
                'skill_emoji' => '♻️',
                'skill_evaluasi' => '["Apakah anak tidak membuang sampah sembarangan?","Apakah anak mau memilah sampah?","Apakah anak hemat menggunakan air?","Apakah anak mematikan lampu saat tidak digunakan?","Apakah anak peduli dengan kebersihan lingkungan?"]',
                'skill_id' => 47,
                'skill_key' => 'peduli_lingkungan',
                'skill_pilars' => '["kebiasaan"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 1,
                'skill_title' => 'Peduli Lingkungan',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#FFF3E0',
                'skill_color' => '#FF9800',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar grounding dan menikmati alam.',
                'skill_emoji' => '🌳',
                'skill_evaluasi' => '["Apakah anak senang bermain di luar rumah?","Apakah anak menikmati waktu di alam?","Apakah anak tidak takut kotor saat bermain?","Apakah anak bisa mengamati keindahan alam?","Apakah anak merasa tenang saat di alam?"]',
                'skill_id' => 48,
                'skill_key' => 'grounding_alam',
                'skill_pilars' => '["kesehatan"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 2,
                'skill_title' => 'Grounding Alam',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#FCE4EC',
                'skill_color' => '#E91E63',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar menjaga kedekatan dengan keluarga.',
                'skill_emoji' => '🏠',
                'skill_evaluasi' => '["Apakah anak senang menghabiskan waktu dengan keluarga?","Apakah anak tidak lebih memilih gadget daripada keluarga?","Apakah anak mau ikut kegiatan keluarga?","Apakah anak bercerita tentang harinya?","Apakah anak terlihat bahagia saat bersama keluarga?"]',
                'skill_id' => 49,
                'skill_key' => 'menjaga_kedekatan',
                'skill_pilars' => '["keluarga"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 1,
                'skill_title' => 'Menjaga Kedekatan',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => '["islam"]',
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8F5E9',
                'skill_color' => '#4CAF50',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar mengenal dan mencintai Allah SWT.',
                'skill_emoji' => '🕋',
                'skill_evaluasi' => '["Apakah anak tahu bahwa Allah menciptakan semua makhluk?","Apakah anak senang berdoa kepada Allah?","Apakah anak tahu nama-nama baik Allah?","Apakah anak tidak menyekutukan Allah?","Apakah anak bersyukur atas nikmat Allah?"]',
                'skill_id' => 50,
                'skill_key' => 'tauhid',
                'skill_pilars' => '["spiritual"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 1,
                'skill_title' => 'Tauhid',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => '["islam"]',
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8F5E9',
                'skill_color' => '#4CAF50',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar percaya dan takwa kepada Allah SWT.',
                'skill_emoji' => '🕌',
                'skill_evaluasi' => '["Apakah anak mau sholat bersama keluarga?","Apakah anak tahu kapan waktu sholat?","Apakah anak senang mendengarkan cerita nabi?","Apakah anak mau puasa saat Ramadan?","Apakah anak menghormati Al-Quran?"]',
                'skill_id' => 51,
                'skill_key' => 'iman_dan_taqwa',
                'skill_pilars' => '["spiritual"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 2,
                'skill_title' => 'Iman dan Taqwa',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#E8F5E9',
                'skill_color' => '#4CAF50',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar menghormati dan menyayangi orang tua.',
                'skill_emoji' => '👨‍👩‍👧‍👦',
                'skill_evaluasi' => '["Apakah anak tidak membantah orang tua?","Apakah anak membantu pekerjaan orang tua?","Apakah anak berdoa untuk orang tua?","Apakah anak mengucap terima kasih kepada orang tua?","Apakah anak tidak menyakiti perasaan orang tua?"]',
                'skill_id' => 52,
                'skill_key' => 'menghormati_orang_tua',
                'skill_pilars' => '["spiritual", "keluarga"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 3,
                'skill_title' => 'Menghormati Orang Tua',
                'skill_updated_at' => NULL,
            ],
            [
                'skill_active' => 1,
                'skill_agama' => NULL,
                'skill_ages' => '[3,4,5,6,7,8,9,10,11]',
                'skill_bg' => '#F3E5F5',
                'skill_color' => '#9C27B0',
                'skill_created_at' => NULL,
                'skill_desc' => 'Anak belajar bekerja keras dan tidak malas.',
                'skill_emoji' => '🐝',
                'skill_evaluasi' => '["Apakah anak mau mengerjakan tugas tanpa disuruh?","Apakah anak tidak malas belajar?","Apakah anak bisa fokus belajar selama 30 menit?","Apakah anak menyelesaikan pekerjaan yang sudah dimulai?","Apakah anak senang membantu pekerjaan rumah?"]',
                'skill_id' => 53,
                'skill_key' => 'rajin',
                'skill_pilars' => '["kebiasaan"]',
                'skill_plans' => NULL,
                'skill_sort_order' => 7,
                'skill_title' => 'Rajin',
                'skill_updated_at' => NULL,
            ],
        ];

        DB::table("skills")->insertOrIgnore($dataTables);
    }
}