<?php

namespace Database\Seeders\Activity;

use App\ActivityType;
use App\Models\Activity;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BermainPeranSeeder extends Seeder
{
    public function run(): void
    {
        $dataTables = [
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Koki","emoji":"👨‍🍳","desc":"Anak jadi koki"},{"name":"Pelanggan","emoji":"😊","desc":"Teman jadi pembeli"}],"pages":[{"num":1,"narrator":"Anak buka restoran mainan.","dialog":[{"role":"Koki","text":"Selamat datang! Mau pesan apa?"},{"role":"Pelanggan","text":"Nasi goreng, ya!"},{"role":"Koki","text":"Siap! Tunggu sebentar."}]},{"num":2,"narrator":"Koki siapkan bahan.","dialog":[{"role":"Koki","text":"Ambil telur dan nasi."},{"role":"Pelanggan","text":"Wangi sekali!"},{"role":"Koki","text":"Tambah sayur biar sehat."}]},{"num":3,"narrator":"Koki mulai masak.","dialog":[{"role":"Koki","text":"Goreng telur dulu."},{"role":"Pelanggan","text":"Aduk-aduk!"},{"role":"Koki","text":"Masukkan nasi. Aduk rata."}]},{"num":4,"narrator":"Tambah bumbu.","dialog":[{"role":"Koki","text":"Tambah kecap dan garam."},{"role":"Pelanggan","text":"Sedikit saja ya."},{"role":"Koki","text":"Betul! Jangan terlalu asin."}]},{"num":5,"narrator":"Masak hingga matang.","dialog":[{"role":"Koki","text":"Aduk terus sampai matang."},{"role":"Pelanggan","text":"Sudah matang?"},{"role":"Koki","text":"Sebentar lagi."}]},{"num":6,"narrator":"Hidangkan.","dialog":[{"role":"Koki","text":"Nasi goreng sudah jadi!"},{"role":"Pelanggan","text":"Wah! Cantik sekali!"},{"role":"Koki","text":"Selamat makan!"}]},{"num":7,"narrator":"Pelanggan makan.","dialog":[{"role":"Pelanggan","text":"Enak sekali!"},{"role":"Koki","text":"Makasih! Senang masak."},{"role":"Pelanggan","text":"Minta resepnya dong."}]},{"num":8,"narrator":"Restoran tutup.","dialog":[{"role":"Koki","text":"Sama-sama! Datang lagi ya."},{"role":"Pelanggan","text":"Pasti! Temanku juga mau."},{"role":"Koki","text":"Siap! Besok buka lagi."}]}]}',
                'desc' => 'Anak jadi koki masak nasi goreng',
                'image' => NULL,
                'moral' => 'Masak itu seru dan bermanfaat.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-koki-masak-nasi-goreng',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Koki Masak Nasi Goreng',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Penjual Buah","emoji":"🍎","desc":"Anak jadi penjual buah"},{"name":"Pembeli","emoji":"🛒","desc":"Teman jadi pembeli"}],"pages":[{"num":1,"narrator":"Anak buka toko buah.","dialog":[{"role":"Penjual Buah","text":"Buah segar! Mau beli apa?"},{"role":"Pembeli","text":"Apel berapa?"},{"role":"Penjual Buah","text":"Lima ribu sekilo."}]},{"num":2,"narrator":"Pembeli pilih buah.","dialog":[{"role":"Pembeli","text":"Mau apel dan pisang."},{"role":"Penjual Buah","text":"Apel merah. Manis."},{"role":"Pembeli","text":"Pisangnya juga."}]},{"num":3,"narrator":"Timbang buah.","dialog":[{"role":"Penjual Buah","text":"Satu kilo apel."},{"role":"Pembeli","text":"Pisangnya?"},{"role":"Penjual Buah","text":"Setengah kilo."}]},{"num":4,"narrator":"Hitung total.","dialog":[{"role":"Penjual Buah","text":"Apel lima ribu. Pisang tiga ribu."},{"role":"Pembeli","text":"Berapa semua?"},{"role":"Penjual Buah","text":"Delapan ribu."}]},{"num":5,"narrator":"Pembeli bayar.","dialog":[{"role":"Pembeli","text":"Ini uangnya."},{"role":"Penjual Buah","text":"Pas! Makasih."},{"role":"Pembeli","text":"Sama-sama."}]},{"num":6,"narrator":"Pembeli mau tambah.","dialog":[{"role":"Pembeli","text":"Mau jeruk juga."},{"role":"Penjual Buah","text":"Jeruk manis. Empat ribu."},{"role":"Pembeli","text":"Ambil satu kilo."}]},{"num":7,"narrator":"Kemas buah.","dialog":[{"role":"Penjual Buah","text":"Masukkan kantong ya."},{"role":"Pembeli","text":"Rapi. Makasih."},{"role":"Penjual Buah","text":"Hati-hati di jalan."}]},{"num":8,"narrator":"Toko tutup.","dialog":[{"role":"Pembeli","text":"Besok datang lagi!"},{"role":"Penjual Buah","text":"Terima kasih! Buah segar setiap hari."},{"role":"Pembeli","text":"Enak! Mau lagi."}]}]}',
                'desc' => 'Anak jadi penjual buah segar',
                'image' => NULL,
                'moral' => 'Jual beli itu jujur dan ramah.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-jualan-buah-segar',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Jualan Buah Segar',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Dokter","emoji":"👨‍⚕️","desc":"Anak jadi dokter"},{"name":"Pasien","emoji":"🤒","desc":"Teman jadi pasien"}],"pages":[{"num":1,"narrator":"Anak buka klinik mainan.","dialog":[{"role":"Dokter","text":"Selamat datang di klinik!"},{"role":"Pasien","text":"Dokter, badan panas."},{"role":"Dokter","text":"Sini diperiksa dulu."}]},{"num":2,"narrator":"Dokter tanya gejala.","dialog":[{"role":"Dokter","text":"Sudah berapa hari?"},{"role":"Pasien","text":"Dua hari."},{"role":"Dokter","text":"Ada batuk?"}]},{"num":3,"narrator":"Periksa tenggorokan.","dialog":[{"role":"Dokter","text":"Buka mulut. Aaah."},{"role":"Pasien","text":"Aaah."},{"role":"Dokter","text":"Tenggorokan merah."}]},{"num":4,"narrator":"Periksa telinga.","dialog":[{"role":"Dokter","text":"Lihat telinga ya."},{"role":"Pasien","text":"Begini?"},{"role":"Dokter","text":"Bersih. Bagus."}]},{"num":5,"narrator":"Dengar jantung.","dialog":[{"role":"Dokter","text":"Dengar jantung. Tik-tak."},{"role":"Pasien","text":"Seru!"},{"role":"Dokter","text":"Jantung sehat."}]},{"num":6,"narrator":"Dokter kasih obat.","dialog":[{"role":"Dokter","text":"Minum obat ya."},{"role":"Pasien","text":"Pahit?"},{"role":"Dokter","text":"Sedikit. Tapi sehat."}]},{"num":7,"narrator":"Dokter kasih saran.","dialog":[{"role":"Dokter","text":"Minum air putih banyak."},{"role":"Pasien","text":"Baik, Dokter."},{"role":"Dokter","text":"Istirahat yang cukup."}]},{"num":8,"narrator":"Pasien pulang.","dialog":[{"role":"Pasien","text":"Makasih, Dokter!"},{"role":"Dokter","text":"Sama-sama. Jaga kesehatan!"},{"role":"Pasien","text":"Insya Allah sembuh."}]}]}',
                'desc' => 'Anak jadi dokter periksa pasien',
                'image' => NULL,
                'moral' => 'Dokter membantu orang sakit.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-dokter-periksa-pasien',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Dokter Periksa Pasien',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Operator","emoji":"📞","desc":"Anak jadi operator telp"},{"name":"Pelanggan","emoji":"😊","desc":"Teman jadi pelanggan"}],"pages":[{"num":1,"narrator":"Telp berbunyi.","dialog":[{"role":"Operator","text":"Halo! Selamat datang."},{"role":"Pelanggan","text":"Mau pesan makanan."},{"role":"Operator","text":"Silakan. Mau apa?"}]},{"num":2,"narrator":"Pelanggan pesan.","dialog":[{"role":"Pelanggan","text":"Nasi goreng satu."},{"role":"Operator","text":"Minumnya?"},{"role":"Pelanggan","text":"Es teh manis."}]},{"num":3,"narrator":"Operator catat pesanan.","dialog":[{"role":"Operator","text":"Nasi goreng satu. Es teh satu."},{"role":"Pelanggan","text":"Betul!"},{"role":"Operator","text":"Berapa orang?"}]},{"num":4,"narrator":"Tanya alamat.","dialog":[{"role":"Operator","text":"Alamat pengiriman?"},{"role":"Pelanggan","text":"Jalan Mawar nomor lima."},{"role":"Operator","text":"Sudah dicatat."}]},{"num":5,"narrator":"Hitung total.","dialog":[{"role":"Operator","text":"Total lima belas ribu."},{"role":"Pelanggan","text":"Baik. Diantar ya."},{"role":"Operator","text":"Tiga puluh menit."}]},{"num":6,"narrator":"Kirim ke kurir.","dialog":[{"role":"Operator","text":"Pesanan dikirim!"},{"role":"Pelanggan","text":"Makasih!"},{"role":"Operator","text":"Sama-sama!"}]},{"num":7,"narrator":"Pelanggan terima.","dialog":[{"role":"Pelanggan","text":"Sudah sampai!"},{"role":"Operator","text":"Enak ya?"},{"role":"Pelanggan","text":"Enak! Pesan lagi."}]},{"num":8,"narrator":"Telp selesai.","dialog":[{"role":"Operator","text":"Makasih sudah pesan!"},{"role":"Pelanggan","text":"Besok pesan lagi!"},{"role":"Operator","text":"Siap! Kami tunggu."}]}]}',
                'desc' => 'Anak jadi operator telp pesan makanan',
                'image' => NULL,
                'moral' => 'Melayani dengan ramah itu penting.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-telp-pesan-makanan',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Telp Pesan Makanan',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Kasir","emoji":"🤑","desc":"Anak jadi kasir"},{"name":"Pembeli","emoji":"🛒","desc":"Teman jadi pembeli"}],"pages":[{"num":1,"narrator":"Anak buka toko mainan.","dialog":[{"role":"Kasir","text":"Selamat datang di toko!"},{"role":"Pembeli","text":"Mau beli ini."},{"role":"Kasir","text":"Silakan. Tiga ribu."}]},{"num":2,"narrator":"Pembeli pilih barang.","dialog":[{"role":"Pembeli","text":"Ini berapa?"},{"role":"Kasir","text":"Lima ribu."},{"role":"Pembeli","text":"Yang ini?"}]},{"num":3,"narrator":"Kasir hitung.","dialog":[{"role":"Kasir","text":"Total delapan ribu."},{"role":"Pembeli","text":"Ini uangnya."},{"role":"Kasir","text":"Uangnya pas."}]},{"num":4,"narrator":"Kasir kasih struk.","dialog":[{"role":"Kasir","text":"Ini struknya."},{"role":"Pembeli","text":"Makasih."},{"role":"Kasir","text":"Sama-sama."}]},{"num":5,"narrator":"Pembeli mau tambah.","dialog":[{"role":"Pembeli","text":"Mau beli lagi."},{"role":"Kasir","text":"Silakan!"},{"role":"Pembeli","text":"Yang merah."}]},{"num":6,"narrator":"Hitung lagi.","dialog":[{"role":"Kasir","text":"Dua ribu."},{"role":"Pembeli","text":"Ini uangnya."},{"role":"Kasir","text":"Kembalian seribu."}]},{"num":7,"narrator":"Kasir ramah.","dialog":[{"role":"Kasir","text":"Terima kasih sudah belanja!"},{"role":"Pembeli","text":"Tokonya bagus."},{"role":"Kasir","text":"Datang lagi ya!"}]},{"num":8,"narrator":"Toko tutup.","dialog":[{"role":"Pembeli","text":"Sampai jumpa!"},{"role":"Kasir","text":"Hati-hati di jalan!"},{"role":"Pembeli","text":"Besok datang lagi!"}]}]}',
                'desc' => 'Anak jadi kasir di toko',
                'image' => NULL,
                'moral' => 'Berhitung itu penting.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-kasir-di-toko',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Kasir di Toko',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Penjual Es","emoji":"🍦","desc":"Anak jadi penjual es krim"},{"name":"Pembeli","emoji":"😊","desc":"Teman jadi pembeli"}],"pages":[{"num":1,"narrator":"Anak buka gerobak es krim.","dialog":[{"role":"Penjual Es","text":"Es krim! Mau rasa apa?"},{"role":"Pembeli","text":"Cokelat!"},{"role":"Penjual Es","text":"Siap!"}]},{"num":2,"narrator":"Ambil es krim.","dialog":[{"role":"Penjual Es","text":"Cokelat satu."},{"role":"Pembeli","text":"Tambah stroberi?"},{"role":"Penjual Es","text":"Boleh! Dua rasa."}]},{"num":3,"narrator":"Kasih topping.","dialog":[{"role":"Penjual Es","text":"Mau topping?"},{"role":"Pembeli","text":"Meses!"},{"role":"Penjual Es","text":"Tabur banyak ya."}]},{"num":4,"narrator":"Es krim jadi.","dialog":[{"role":"Penjual Es","text":"Sudah jadi! Cantik."},{"role":"Pembeli","text":"Wah! Enak."},{"role":"Penjual Es","text":"Lima ribu."}]},{"num":5,"narrator":"Pembeli bayar.","dialog":[{"role":"Pembeli","text":"Ini uangnya."},{"role":"Penjual Es","text":"Makasih!"},{"role":"Pembeli","text":"Enak!"}]},{"num":6,"nistrator":"Pembeli mau tambah.","dialog":[{"role":"Pembeli","text":"Mau satu lagi. Vanila."},{"role":"Penjual Es","text":"Siap! Vanila."},{"role":"Pembeli","text":"Makasih!"}]},{"num":7,"narrator":"Teman datang.","dialog":[{"role":"Pembeli","text":"Teman! Es krim enak!"},{"role":"Penjual Es","text":"Silakan! Banyak rasa."},{"role":"Pembeli","text":"Mau mangga."}]},{"num":8,"narrator":"Gerobak tutup.","dialog":[{"role":"Penjual Es","text":"Es krim habis!"},{"role":"Pembeli","text":"Besok datang lagi!"},{"role":"Penjual Es","text":"Siap! Es segar setiap hari."}]}]}',
                'desc' => 'Anak jadi penjual es krim',
                'image' => NULL,
                'moral' => 'Berbagi kebahagiaan lewat makanan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-jualan-es-krim',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Jualan Es Krim',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Pemadam","emoji":"🧑‍🚒","desc":"Anak jadi pemadam"},{"name":"Warga","emoji":"😟","desc":"Teman jadi warga"}],"pages":[{"num":1,"narrator":"Ada api besar!","dialog":[{"role":"Warga","text":"Tolong! Ada api!"},{"role":"Pemadam","text":"Tenang! Kami datang!"},{"role":"Warga","text":"Cepat, tolong!"}]},{"num":2,"narrator":"Pemadam siap.","dialog":[{"role":"Pemadam","text":"Pakai helm dan baju tahan api."},{"role":"Warga","text":"Hati-hati!"},{"role":"Pemadam","text":"Naik truk. Jalan!"}]},{"num":3,"narrator":"Sampai lokasi.","dialog":[{"role":"Pemadam","text":"Api besar! Siapkan selang."},{"role":"Warga","text":"Rumahku!"},{"role":"Pemadam","text":"Tenang. Kami bantu."}]},{"num":4,"narrator":"Semprot api.","dialog":[{"role":"Pemadam","text":"Semprot air! Srrrt!"},{"role":"Warga","text":"Api mulai kecil!"},{"role":"Pemadam","text":"Terus semprot!"}]},{"num":5,"narrator":"Api padam.","dialog":[{"role":"Pemadam","text":"Api sudah padam!"},{"role":"Warga","text":"Alhamdulillah!"},{"role":"Pemadam","text":"Aman sekarang."}]},{"num":6,"narrator":"Periksa lokasi.","dialog":[{"role":"Pemadam","text":"Periksa masih ada api?"},{"role":"Warga","text":"Sudah tidak ada."},{"role":"Pemadam","text":"Bagus. Aman."}]},{"num":7,"narrator":"Warga berterima kasih.","dialog":[{"role":"Warga","text":"Terima kasih, Pemadam!"},{"role":"Pemadam","text":"Sama-sama. Hati-hati ya."},{"role":"Warga","text":"Kalian hebat!"}]},{"num":8,"narrator":"Pemadam pulang.","dialog":[{"role":"Pemadam","text":"Jaga keamanan ya."},{"role":"Warga","text":"Baik! Hati-hati di jalan."},{"role":"Pemadam","text":"Kalau ada api, hubungi kami!"}]}]}',
                'desc' => 'Anak jadi pemadam kebakaran',
                'image' => NULL,
                'moral' => 'Pemadam kebakaran itu berani.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-pemadam-kebakaran',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Pemadam Kebakaran',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Kurir","emoji":"📦","desc":"Anak jadi kurir"},{"name":"Penerima","emoji":"😊","desc":"Teman jadi penerima"}],"pages":[{"num":1,"narrator":"Kurir ambil paket.","dialog":[{"role":"Kurir","text":"Ada paket baru!"},{"role":"Penerima","text":"Untuk siapa?"},{"role":"Kurir","text":"Untukmu!"}]},{"num":2,"narrator":"Kurir antar paket.","dialog":[{"role":"Kurir","text":"Naik motor. Jalan!"},{"role":"Penerima","text":"Di mana ya?"},{"role":"Kurir","text":"Jalan Mawar."}]},{"num":3,"narrator":"Sampai tujuan.","dialog":[{"role":"Kurir","text":"Sampai! Ini rumahnya?"},{"role":"Penerima","text":"Betul!"},{"role":"Kurir","text":"Paket untukmu."}]},{"num":4,"narrator":"Buka paket.","dialog":[{"role":"Penerima","text":"Apa isinya?"},{"role":"Kurir","text":"Aku tidak tahu."},{"role":"Penerima","text":"Mainan!"}]},{"num":5,"narrator":"Tanda tangan.","dialog":[{"role":"Kurir","text":"Tanda tangan di sini."},{"role":"Penerima","text":"Begini?"},{"role":"Kurir","text":"Makasih!"}]},{"num":6,"narrator":"Penerima senang.","dialog":[{"role":"Penerima","text":"Mainan baru! Senang!"},{"role":"Kurir","text":"Makasih sudah belanja."},{"role":"Penerima","text":"Sama-sama!"}]},{"num":7,"narrator":"Kurir lanjut.","dialog":[{"role":"Kurir","text":"Ada paket lagi."},{"role":"Penerima","text":"Hati-hati di jalan!"},{"role":"Kurir","text":"Makasih!"}]},{"num":8,"narrator":"Kurir pulang.","dialog":[{"role":"Kurir","text":"Paket semua terkirim!"},{"role":"Penerima","text":"Kurir hebat!"},{"role":"Kurir","text":"Makasih! Besok antar lagi."}]}]}',
                'desc' => 'Anak jadi kurir antar paket',
                'image' => NULL,
                'moral' => 'Mengantar dengan aman itu tanggung jawab.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["bertanggung_jawab"]',
                'slug' => 'main-kurir-antar-paket',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Kurir Antar Paket',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Polisi","emoji":"👮","desc":"Anak jadi polisi"},{"name":"Warga","emoji":"😟","desc":"Teman jadi warga"}],"pages":[{"num":1,"narrator":"Warga minta tolong.","dialog":[{"role":"Warga","text":"Polisi, dompet hilang!"},{"role":"Polisi","text":"Tenang. Di mana terakhir?"},{"role":"Warga","text":"Di taman."}]},{"num":2,"narrator":"Polisi tanya ciri-ciri.","dialog":[{"role":"Polisi","text":"Dompetnya warna apa?"},{"role":"Warga","text":"Cokelat."},{"role":"Polisi","text":"Ada apa di dalam?"}]},{"num":3,"narrator":"Warga jelaskan.","dialog":[{"role":"Warga","text":"Ada uang dan foto."},{"role":"Polisi","text":"Baik. Aku cari."},{"role":"Warga","text":"Makasih, Polisi."}]},{"num":4,"narrator":"Polisi cari di taman.","dialog":[{"role":"Polisi","text":"Cari di sini ya."},{"role":"Warga","text":"Di dekat bangku."},{"role":"Polisi","text":"Sini. Aku lihat."}]},{"num":5,"narrator":"Polisi teliti.","dialog":[{"role":"Polisi","text":"Lihat di bawah bangku."},{"role":"Warga","text":"Ketemu?"},{"role":"Polisi","text":"Belum. Cari lagi."}]},{"num":6,"narrator":"Dompet ketemu.","dialog":[{"role":"Polisi","text":"Ini dompetnya!"},{"role":"Warga","text":"Alhamdulillah!"},{"role":"Polisi","text":"Cek isinya lengkap?"}]},{"num":7,"narrator":"Warga senang.","dialog":[{"role":"Warga","text":"Lengkap! Makasih!"},{"role":"Polisi","text":"Sama-sama. Jaga barang ya."},{"role":"Warga","text":"Baik, Polisi!"}]},{"num":8,"narrator":"Polisi kasih saran.","dialog":[{"role":"Polisi","text":"Jangan letakkan sembarangan."},{"role":"Warga","text":"Baik. Hati-hati."},{"role":"Polisi","text":"Kalau hilang lagi, lapor ya!"}]}]}',
                'desc' => 'Anak jadi polisi bantu warga',
                'image' => NULL,
                'moral' => 'Polisi melindungi semua orang.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-polisi-bantu-warga',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Polisi Bantu Warga',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '["islam"]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Guru Ngaji","emoji":"📖","desc":"Anak jadi guru ngaji"},{"name":"Murid","emoji":"😊","desc":"Teman jadi murid"}],"pages":[{"num":1,"narrator":"Anak jadi guru ngaji.","dialog":[{"role":"Guru Ngaji","text":"Baca Al-Quran yuk!"},{"role":"Murid","text":"Mau!"},{"role":"Guru Ngaji","text":"Mulai huruf Alif."}]},{"num":2,"narrator":"Belajar huruf hijaiyah.","dialog":[{"role":"Guru Ngaji","text":"Alif. Ba. Ta."},{"role":"Murid","text":"Alif! Ba!"},{"role":"Guru Ngaji","text":"Bagus!"}]},{"num":3,"narrator":"Belajar membaca.","dialog":[{"role":"Guru Ngaji","text":"Baca pelan ya."},{"role":"Murid","text":"Bismillah."},{"role":"Guru Tajweed","text":"Betul! Pelan."}]},{"num":4,"narrator":"Belajar tajwid.","dialog":[{"role":"Guru Ngaji","text":"Panjang sedikit."},{"role":"Murid","text":"Begini?"},{"role":"Guru Ngaji","text":"Bagus!"}]},{"num":5,"narrator":"Murid lancar.","dialog":[{"role":"Murid","text":"Bisa!"},{"role":"Guru Ngaji","text":"Alhamdulillah."},{"role":"Murid","text":"Mau lagi!"}]},{"num":6,"narrator":"Belajar doa.","dialog":[{"role":"Guru Ngaji","text":"Belajar doa makan."},{"role":"Murid","text":"Bismillah."},{"role":"Guru Ngaji","text":"Betul!"}]},{"num":7,"narrator":"Murid hafal.","dialog":[{"role":"Murid","text":"Sudah hafal!"},{"role":"Guru Ngaji","text":"Hebat! Rajin ya."},{"role":"Murid","text":"Setiap hari!"}]},{"num":8,"narrator":"Ngaji selesai.","dialog":[{"role":"Guru Ngaji","text":"Alhamdulillah. Selesai."},{"role":"Murid","text":"Makasih, Guru!"},{"role":"Guru Ngaji","text":"Besok lanjut ya."}]}]}',
                'desc' => 'Anak jadi guru ngaji',
                'image' => NULL,
                'moral' => 'Belajar Al-Quran itu mulia.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["iman_dan_taqwa"]',
                'slug' => 'main-guru-ngaji',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Guru Ngaji',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Guru","emoji":"👩‍🏫","desc":"Anak jadi guru"},{"name":"Murid","emoji":"😊","desc":"Teman jadi murid"}],"pages":[{"num":1,"narrator":"Anak jadi guru.","dialog":[{"role":"Guru","text":"Selamat pagi, Murid!"},{"role":"Murid","text":"Selamat pagi, Bu Guru!"},{"role":"Guru","text":"Hari ini belajar huruf."}]},{"num":2,"narrator":"Guru tulis huruf A.","dialog":[{"role":"Guru","text":"Ini huruf A. Coba tiru."},{"role":"Murid","text":"Begini?"},{"role":"Guru","text":"Bagus! Lanjut B."}]},{"num":3,"narrator":"Belajar huruf B.","dialog":[{"role":"Guru","text":"Huruf B. Dua perut."},{"role":"Murid","text":"B besar, b kecil."},{"role":"Guru","text":"Hebat!"}]},{"num":4,"narrator":"Belajar huruf C.","dialog":[{"role":"Guru","text":"Huruf C. Seperti bulan."},{"role":"Murid","text":"C. Seperti senyum."},{"role":"Guru","text":"Betul!"}]},{"num":5,"narrator":"Belajar huruf D.","dialog":[{"role":"Guru","text":"Huruf D. Dua perut."},{"role":"Murid","text":"D besar, d kecil."},{"role":"Guru","text":"Pintar!"}]},{"num":6,"narrator":"Murid menulis sendiri.","dialog":[{"role":"Murid","text":"A, B, C, D!"},{"role":"Guru","text":"Tulis yang rapi ya."},{"role":"Murid","text":"Baik, Guru."}]},{"num":7,"narrator":"Guru puji murid.","dialog":[{"role":"Guru","text":"Wah! Rapi sekali!"},{"role":"Murid","text":"Makasih, Guru!"},{"role":"Guru","text":"Rajin belajar ya."}]},{"num":8,"narrator":"Belajar selesai.","dialog":[{"role":"Murid","text":"Bisa A, B, C, D!"},{"role":"Guru","text":"Hebat! Besok lanjut E."},{"role":"Murid","text":"Makasih, Guru!"}]}]}',
                'desc' => 'Anak jadi guru mengajar',
                'image' => NULL,
                'moral' => 'Mengajar itu sabar dan baik.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-guru-mengajar-huruf',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Guru Mengajar Huruf',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Supir Taksi","emoji":"🚕","desc":"Anak jadi supir taksi"},{"name":"Penumpang","emoji":"😊","desc":"Teman jadi penumpang"}],"pages":[{"num":1,"narrator":"Taksi menunggu.","dialog":[{"role":"Supir Taksi","text":"Mau ke mana?"},{"role":"Penumpang","text":"Ke pasar."},{"role":"Supir Taksi","text":"Silakan naik."}]},{"num":2,"narrator":"Penumpang naik.","dialog":[{"role":"Penumpang","text":"Berapa ongkosnya?"},{"role":"Supir Taksi","text":"Sepuluh ribu."},{"role":"Penumpang","text":"Baik."}]},{"num":3,"narrator":"Taksi jalan.","dialog":[{"role":"Supir Taksi","text":"Jalan ya."},{"role":"Penumpang","text":"Pelan saja."},{"role":"Supir Taksi","text":"Aman."}]},{"num":4,"narrator":"Di jalan.","dialog":[{"role":"Penumpang","text":"Macet."},{"role":"Supir Taksi","text":"Sabar. Sebentar lagi."},{"role":"Penumpang","text":"Baik."}]},{"num":5,"narrator":"Sampai tujuan.","dialog":[{"role":"Supir Taksi","text":"Sampai pasar!"},{"role":"Penumpang","text":"Makasih!"},{"role":"Supir Taksi","text":"Sepuluh ribu."}]},{"num":6,"narrator":"Bayar ongkos.","dialog":[{"role":"Penumpang","text":"Ini uangnya."},{"role":"Supir Taksi","text":"Pas! Makasih."},{"role":"Penumpang","text":"Sama-sama."}]},{"num":7,"narrator":"Penumpang turun.","dialog":[{"role":"Penumpang","text":"Hati-hati di jalan!"},{"role":"Supir Taksi","text":"Makasih! Selamat belanja."},{"role":"Penumpang","text":"Besok naik lagi."}]},{"num":8,"narrator":"Taksi lanjut.","dialog":[{"role":"Supir Taksi","text":"Ada penumpang lagi!"},{"role":"Penumpang","text":"Ke mana?"},{"role":"Supir Taksi","text":"Ke mana saja! Silakan."}]}]}',
                'desc' => 'Anak jadi supir taksi',
                'image' => NULL,
                'moral' => 'Mengantar dengan aman itu baik.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-supir-taksi',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Supir Taksi',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Pilot","emoji":"✈️","desc":"Anak jadi pilot"},{"name":"Penumpang","emoji":"😊","desc":"Teman jadi penumpang"}],"pages":[{"num":1,"narrator":"Anak jadi pilot.","dialog":[{"role":"Pilot","text":"Selamat datang di pesawat!"},{"role":"Penumpang","text":"Mau ke mana?"},{"role":"Pilot","text":"Ke awan!"}]},{"num":2,"narrator":"Siap terbang.","dialog":[{"role":"Pilot","text":"Pasang sabuk pengaman."},{"role":"Penumpang","text":"Sudah!"},{"role":"Pilot","text":"Mesin hidup. Jalan!"}]},{"num":3,"narrator":"Pesawat jalan di landasan.","dialog":[{"role":"Pilot","text":"Kecepatan penuh!"},{"role":"Penumpang","text":"Wah! Cepat!"},{"role":"Pilot","text":"Terbang!"}]},{"num":4,"narrator":"Pesawat terbang tinggi.","dialog":[{"role":"Pilot","text":"Terbang tinggi!"},{"role":"Penumpang","text":"Wah! Awan dekat!"},{"role":"Pilot","text":"Lihat di bawah. Kecil."}]},{"num":5,"narrator":"Di atas awan.","dialog":[{"role":"Penumpang","text":"Awan seperti kapas!"},{"role":"Pilot","text":"Cantik ya."},{"role":"Penumpang","text":"Mau pegang!"}]},{"num":6,"narrator":"Pilot belok pesawat.","dialog":[{"role":"Pilot","text":"Belok kiri. Lihat gunung."},{"role":"Penumpang","text":"Besar!"},{"role":"Pilot","text":"Indah ya."}]},{"num":7,"narrator":"Mendarat.","dialog":[{"role":"Pilot","text":"Mendarat. Sampai!"},{"role":"Penumpang","text":"Seru! Terbang lagi!"},{"role":"Pilot","text":"Siap! Ke bulan!"}]},{"num":8,"narrator":"Penumpang berterima kasih.","dialog":[{"role":"Penumpang","text":"Makasih, Pilot!"},{"role":"Pilot","text":"Sama-sama! Besok terbang lagi."},{"role":"Penumpang","text":"Pasti!"}]}]}',
                'desc' => 'Anak jadi pilot terbang',
                'image' => NULL,
                'moral' => 'Terbang tinggi impikan besar.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-pilot-terbang',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Pilot Terbang',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Penjual Bunga","emoji":"💐","desc":"Anak jadi penjual bunga"},{"name":"Pembeli","emoji":"😊","desc":"Teman jadi pembeli"}],"pages":[{"num":1,"narrator":"Anak buka toko bunga.","dialog":[{"role":"Penjual Bunga","text":"Bunga cantik! Mau beli apa?"},{"role":"Pembeli","text":"Mawar merah."},{"role":"Penjual Bunga","text":"Silakan!"}]},{"num":2,"narrator":"Pembeli pilih bunga.","dialog":[{"role":"Pembeli","text":"Yang ini cantik."},{"role":"Penjual Bunga","text":"Mawar merah. Harum."},{"role":"Pembeli","text":"Mau tiga."}]},{"num":3,"nistructor":"Buat buket.","dialog":[{"role":"Penjual Bunga","text":"Buat buket ya."},{"role":"Pembeli","text":"Cantik!"},{"role":"Penjual Bunga","text":"Tambah pita."}]},{"num":4,"narrator":"Buket jadi.","dialog":[{"role":"Penjual Bunga","text":"Sudah jadi!"},{"role":"Pembeli","text":"Wah! Bagus."},{"role":"Penjual Bunga","text":"Lima belas ribu."}]},{"num":5,"narrator":"Pembeli bayar.","dialog":[{"role":"Pembeli","text":"Ini uangnya."},{"role":"Penjual Bunga","text":"Makasih!"},{"role":"Pembeli","text":"Untuk Ibu."}]},{"num":6,"narrator":"Pembeli kasih Ibu.","dialog":[{"role":"Pembeli","text":"Bu, ini untuk Ibu."},{"role":"Penjual Bunga","text":"Cantik ya."},{"role":"Pembeli","text":"Makasih, Bu!"}]},{"num":7,"narrator":"Ibu senang.","dialog":[{"role":"Penjual Bunga","text":"Bunga bikin senang."},{"role":"Pembeli","text":"Ibu senang!"},{"role":"Penjual Bunga","text":"Beli lagi ya."}]},{"num":8,"narrator":"Toko tutup.","dialog":[{"role":"Penjual Bunga","text":"Bunga habis!"},{"role":"Pembeli","text":"Besok datang lagi!"},{"role":"Penjual Bunga","text":"Siap! Bunga segar setiap hari."}]}]}',
                'desc' => 'Anak jadi penjual bunga',
                'image' => NULL,
                'moral' => 'Memberi hadiah itu menyenangkan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-jualan-bunga',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Jualan Bunga',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Petani","emoji":"🧑‍🌾","desc":"Anak jadi petani"},{"name":"Teman","emoji":"😊","desc":"Teman bantu"}],"pages":[{"num":1,"narrator":"Anak jadi petani.","dialog":[{"role":"Petani","text":"Ayo tanam padi!"},{"role":"Teman","text":"Caranya?"},{"role":"Petani","text":"Masukkan benih ke tanah."}]},{"num":2,"narrator":"Siapkan tanah.","dialog":[{"role":"Petani","text":"Gali tanah dulu."},{"role":"Teman","text":"Begini?"},{"role":"Petani","text":"Betul! Dalam sedikit."}]},{"num":3,"narrator":"Tanam benih.","dialog":[{"role":"Petani","text":"Masukkan benih pelan."},{"role":"Teman","text":"Sudah. Kapan tumbuh?"},{"role":"Petani","text":"Sabar. Beberapa hari."}]},{"num":4,"narrator":"Siram air.","dialog":[{"role":"Petani","text":"Siram air pelan."},{"role":"Teman","text":"Jangan terlalu banyak."},{"role":"Petani","text":"Betul! Cukup."}]},{"num":5,"narrator":"Benih tumbuh.","dialog":[{"role":"Teman","text":"Tumbuh! Hijau!"},{"role":"Petani","text":"Rajin siram ya."},{"role":"Teman","text":"Setiap pagi!"}]},{"num":6,"narrator":"Rawat tanaman.","dialog":[{"role":"Petani","text":"Cabut rumput di sini."},{"role":"Teman","text":"Rumput liar."},{"role":"Petani","text":"Biar padi kuat."}]},{"num":7,"narrator":"Padi besar.","dialog":[{"role":"Teman","text":"Padi sudah besar!"},{"role":"Petani","text":"Karena dirawat."},{"role":"Teman","text":"Senang!"}]},{"num":8,"narrator":"Petani senang.","dialog":[{"role":"Petani","text":"Bertani seru!"},{"role":"Teman","text":"Jadi petani seru!"},{"role":"Petani","text":"Ayo tanam lagi!"}]}]}',
                'desc' => 'Anak jadi petani tanam padi',
                'image' => NULL,
                'moral' => 'Bertani butuh sabar dan rajin.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-petani-tanam-padi',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Petani Tanam Padi',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Petani","emoji":"🧑‍🌾","desc":"Anak jadi petani"},{"name":"Teman","emoji":"😊","desc":"Teman bantu panen"}],"pages":[{"num":1,"narrator":"Waktunya panen.","dialog":[{"role":"Petani","text":"Padi sudah kuning!"},{"role":"Teman","text":"Mau bantu!"},{"role":"Petani","text":"Ayo panen!"}]},{"num":2,"narrator":"Siapkan alat.","dialog":[{"role":"Petani","text":"Ambil sabit."},{"role":"Teman","text":"Hati-hati ya."},{"role":"Petani","text":"Pelan saja."}]},{"num":3,"narrator":"Potong padi.","dialog":[{"role":"Petani","text":"Potong pelan ya."},{"role":"Teman","text":"Begini?"},{"role":"Petani","text":"Betul! Kumpulkan."}]},{"num":4,"narrator":"Kumpulkan padi.","dialog":[{"role":"Teman","text":"Banyak sekali!"},{"role":"Petani","text":"Hasil kerja keras."},{"role":"Teman","text":"Senang!"}]},{"num":5,"narrator":"Jemur padi.","dialog":[{"role":"Petani","text":"Jemur di matahari."},{"role":"Teman","text":"Biar kering?"},{"role":"Petani","text":"Betul! Kering enak."}]},{"num":6,"narrator":"Padi kering.","dialog":[{"role":"Teman","text":"Sudah kering!"},{"role":"Petani","text":"Kuliti berasnya."},{"role":"Teman","text":"Wah! Putih."}]},{"num":7,"narrator":"Masak nasi.","dialog":[{"role":"Petani","text":"Masak nasi ya."},{"role":"Teman","text":"Enak! Dari sawah."},{"role":"Petani","text":"Hasil sendiri."}]},{"num":8,"narrator":"Makan bersama.","dialog":[{"role":"Teman","text":"Makan enak!"},{"role":"Petani","text":"Bertani bermanfaat."},{"role":"Teman","text":"Mau tanam lagi!"}]}]}',
                'desc' => 'Anak jadi petani panen padi',
                'image' => NULL,
                'moral' => 'Hasil kerja keras itu memuaskan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-petani-panen-padi',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Petani Panen Padi',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Perawat","emoji":"👩‍⚕️","desc":"Anak jadi perawat"},{"name":"Bayi","emoji":"👶","desc":"Boneka jadi bayi"}],"pages":[{"num":1,"narrator":"Anak jadi perawat.","dialog":[{"role":"Perawat","text":"Bayi rewel."},{"role":"Bayi","text":"Uaa!"},{"role":"Perawat","text":"Jangan menangis."}]},{"num":2,"narrator":"Perawat tenangkan.","dialog":[{"role":"Perawat","text":"Sini. Peluk."},{"role":"Bayi","text":"Uaa!"},{"role":"Perawat","text":"Tenang ya."}]},{"num":3,"narrator":"Kasih makan.","dialog":[{"role":"Perawat","text":"Makan ya."},{"role":"Bayi","text":"Uaa!"},{"role":"Perawat","text":"Pelan-pelan."}]},{"num":4,"narrator":"Minum susu.","dialog":[{"role":"Perawat","text":"Minum susu."},{"role":"Bayi","text":"Uaa."},{"role":"Perawat","text":"Enak ya."}]},{"num":5,"narrator":"Ganti baju.","dialog":[{"role":"Perawat","text":"Ganti baju ya."},{"role":"Bayi","text":"Uaa!"},{"role":"Perawat","text":"Baju bersih."}]},{"num":6,"narrator":"Mandi bayi.","dialog":[{"role":"Perawat","text":"Mandi air hangat."},{"role":"Bayi","text":"Uaa."},{"role":"Perawat","text":"Wangi ya."}]},{"num":7,"narrator":"Main sebentar.","dialog":[{"role":"Perawat","text":"Main ya."},{"role":"Bayi","text":"Uaa! Senang."},{"role":"Perawat","text":"Ketawa!"}]},{"num":8,"narrator":"Bayi tidur.","dialog":[{"role":"Perawat","text":"Tidur ya."},{"role":"Bayi","text":"Uaa."},{"role":"Perawat","text":"Ninabobo. Tidur."}]}]}',
                'desc' => 'Anak jadi perawat rawat bayi',
                'image' => NULL,
                'moral' => 'Merawat itu sabar dan lembut.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["peduli_sesama"]',
                'slug' => 'main-perawat-rawat-bayi',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Perawat Rawat Bayi',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Tukang Pos","emoji":"🏣","desc":"Anak jadi tukang pos"},{"name":"Penerima","emoji":"😊","desc":"Teman jadi penerima"}],"pages":[{"num":1,"narrator":"Anak jadi tukang pos.","dialog":[{"role":"Tukang Pos","text":"Ada surat!"},{"role":"Penerima","text":"Untuk siapa?"},{"role":"Tukang Pos","text":"Untukmu!"}]},{"num":2,"narrator":"Cek alamat.","dialog":[{"role":"Tukang Pos","text":"Ini alamatnya?"},{"role":"Penerima","text":"Betul!"},{"role":"Tukang Pos","text":"Serahkan surat."}]},{"num":3,"narrator":"Tanda tangan.","dialog":[{"role":"Tukang Pos","text":"Tanda tangan di sini."},{"role":"Penerima","text":"Begini?"},{"role":"Tukang Pos","text":"Terima kasih."}]},{"num":4,"narrator":"Baca surat.","dialog":[{"role":"Penerima","text":"Surat dari Nenek!"},{"role":"Tukang Pos","text":"Senang ya."},{"role":"Penerima","text":"Makasih, Pos!"}]},{"num":5,"narrator":"Tukang Pos lanjut.","dialog":[{"role":"Tukang Pos","text":"Ada surat lagi."},{"role":"Penerima","text":"Untuk tetangga."},{"role":"Tukang Pos","text":"Aku antar."}]},{"num":6,"narrator":"Antar surat kedua.","dialog":[{"role":"Tukang Pos","text":"Surat untuk Ibu!"},{"role":"Penerima","text":"Di sana rumahnya."},{"role":"Tukang Pos","text":"Makasih!"}]},{"num":7,"narrator":"Tukang Pos capek.","dialog":[{"role":"Tukang Pos","text":"Capek. Istirahat."},{"role":"Penerima","text":"Minum dulu."},{"role":"Tukang Pos","text":"Makasih!"}]},{"num":8,"narrator":"Pulang.","dialog":[{"role":"Tukang Pos","text":"Besok ada surat lagi."},{"role":"Penerima","text":"Makasih sudah mengantar!"},{"role":"Tukang Pos","text":"Sama-sama! Tugas mulia."}]}]}',
                'desc' => 'Anak jadi tukang pos kirim surat',
                'image' => NULL,
                'moral' => 'Mengirim surat itu menyenangkan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-tukang-pos-kirim-surat',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Tukang Pos Kirim Surat',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Montir","emoji":"🔧","desc":"Anak jadi montir"},{"name":"Pemilik Mobil","emoji":"🚗","desc":"Teman jadi pemilik"}],"pages":[{"num":1,"narrator":"Mobil mogok.","dialog":[{"role":"Pemilik Mobil","text":"Mobil mogok!"},{"role":"Montir","text":"Aku periksa."},{"role":"Pemilik Mobil","text":"Tolong ya."}]},{"num":2,"narrator":"Montir periksa mesin.","dialog":[{"role":"Montir","text":"Buka kap mesin."},{"role":"Pemilik Mobil","text":"Apa yang rusak?"},{"role":"Montir","text":"Oli habis."}]},{"num":3,"narrator":"Tambah oli.","dialog":[{"role":"Montir","text":"Tambah oli dulu."},{"role":"Pemilik Mobil","text":"Berapa banyak?"},{"role":"Montir","text":"Sedikit saja."}]},{"num":4,"narrator":"Periksa ban.","dialog":[{"role":"Montir","text":"Ban kurang angin."},{"role":"Pemilik Mobil","text":"Isi angin?"},{"role":"Montir","text":"Ya. Penting."}]},{"num":5,"narrator":"Isi angin ban.","dialog":[{"role":"Montir","text":"Kriiik. Sudah keras."},{"role":"Pemilik Mobil","text":"Bagus!"},{"role":"Montir","text":"Aman."}]},{"num":6,"narrator":"Coba mesin.","dialog":[{"role":"Montir","text":"Coba hidupkan mesin."},{"role":"Pemilik Mobil","text":"Mreng! Hidup!"},{"role":"Montir","text":"Sudah jalan!"}]},{"num":7,"narrator":"Mobil jalan.","dialog":[{"role":"Pemilik Mobil","text":"Makasih, Montir!"},{"role":"Montir","text":"Rajin rawat ya."},{"role":"Pemilik Mobil","text":"Baik!"}]},{"num":8,"narrator":"Montir pesan.","dialog":[{"role":"Montir","text":"Ganti oli tiap bulan."},{"role":"Pemilik Mobil","text":"Baik. Makasih!"},{"role":"Montir","text":"Hati-hati di jalan!"}]}]}',
                'desc' => 'Anak jadi montir perbaiki mobil',
                'image' => NULL,
                'moral' => 'Memperbaiki butuh teliti.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-montir-perbaiki-mobil',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Montir Perbaiki Mobil',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Astronot","emoji":"🚀","desc":"Anak jadi astronot"},{"name":"Komandan","emoji":"👨‍🚀","desc":"Teman jadi komandan"}],"pages":[{"num":1,"narrator":"Roket siap.","dialog":[{"role":"Komandan","text":"Roket siap!"},{"role":"Astronot","text":"Mau ke bulan!"},{"role":"Komandan","text":"Pakai baju antariksa."}]},{"num":2,"narrator":"Pakai baju antariksa.","dialog":[{"role":"Astronot","text":"Baju berat!"},{"role":"Komandan","text":"Biar aman di luar angkasa."},{"role":"Astronot","text":"Siap!"}]},{"num":3,"narrator":"Hitung mundur.","dialog":[{"role":"Komandan","text":"Tiga, dua, satu!"},{"role":"Astronot","text":"Terbang!"},{"role":"Komandan","text":"Wuuush!"}]},{"num":4,"narrator":"Di luar angkasa.","dialog":[{"role":"Astronot","text":"Wah! Bintang banyak!"},{"role":"Komandan","text":"Lihat bumi. Kecil."},{"role":"Astronot","text":"Cantik!"}]},{"num":5,"narrator":"Lihat bulan.","dialog":[{"role":"Komandan","text":"Bulan di depan!"},{"role":"Astronot","text":"Besar!"},{"role":"Komandan","text":"Mendarat di sana."}]},{"num":6,"narrator":"Di bulan.","dialog":[{"role":"Astronot","text":"Di bulan! Ringan!"},{"role":"Komandan","text":"Ambil batu bulan."},{"role":"Astronot","text":"Seru!"}]},{"num":7,"narrator":"Jelajah bulan.","dialog":[{"role":"Astronot","text":"Lihat kawah!"},{"role":"Komandan","text":"Besar sekali."},{"role":"Astronot","text":"Petualangan seru!"}]},{"num":8,"narrator":"Pulang ke bumi.","dialog":[{"role":"Komandan","text":"Sudah waktunya pulang."},{"role":"Astronot","text":"Mau ke bulan lagi!"},{"role":"Komandan","text":"Mimpi besar bisa tercapai!"}]}]}',
                'desc' => 'Anak jadi astronot ke bulan',
                'image' => NULL,
                'moral' => 'Mimpi besar bisa tercapai.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'main-astronot-ke-bulan',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Astronot ke Bulan',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Penyanyi","emoji":"🎤","desc":"Anak jadi penyanyi"},{"name":"Penonton","emoji":"👏","desc":"Teman jadi penonton"}],"pages":[{"num":1,"narrator":"Anak mau nyanyi.","dialog":[{"role":"Penyanyi","text":"Aku mau nyanyi!"},{"role":"Penonton","text":"Apa lagunya?"},{"role":"Penyanyi","text":"Pelangi!"}]},{"num":2,"narrator":"Naik panggung.","dialog":[{"role":"Penyanyi","text":"Wah! Tinggi."},{"role":"Penonton","text":"Jangan takut!"},{"role":"Penyanyi","text":"Aku berani."}]},{"num":3,"narrator":"Mulai nyanyi.","dialog":[{"role":"Penyanyi","text":"Pelangi, pelangi!"},{"role":"Penonton","text":"Bagus!"},{"role":"Penyanyi","text":"Alangkah indahmu."}]},{"num":4,"narrator":"Nyanyi lagi.","dialog":[{"role":"Penyanyi","text":"Merah kuning hijau."},{"role":"Penonton","text":"Lagi! Lagi!"},{"role":"Penyanyi","text":"Di langit yang biru."}]},{"num":5,"narrator":"Penonton tepuk tangan.","dialog":[{"role":"Penonton","text":"Tepuk tangan! Hebat!"},{"role":"Penyanyi","text":"Makasih!"},{"role":"Penonton","text":"Nyanyi lagi!"}]},{"num":6,"narrator":"Nyanyi lagu kedua.","dialog":[{"role":"Penyanyi","text":"Topi Sapi!"},{"role":"Penonton","text":"Seru! Aku ikut!"},{"role":"Penyanyi","text":"Ayo bersama!"}]},{"num":7,"narrator":"Nyanyi bersama.","dialog":[{"role":"Penonton","text":"Topi saya bundar!"},{"role":"Penyanyi","text":"Bundar topi saya!"},{"role":"Penonton","text":"Seru!"}]},{"num":8,"narrator":"Selesai.","dialog":[{"role":"Penyanyi","text":"Makasih sudah menonton!"},{"role":"Penonton","text":"Mau lagi! Besok ya."},{"role":"Penyanyi","text":"Siap! Tampil lagi!"}]}]}',
                'desc' => 'Anak jadi penyanyi di panggung',
                'image' => NULL,
                'moral' => 'Tampil berani itu hebat.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["pemberani"]',
                'slug' => 'main-penyanyi-di-panggung',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Penyanyi di Panggung',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Pelukis","emoji":"🎨","desc":"Anak jadi pelukis"},{"name":"Pembeli","emoji":"😊","desc":"Teman jadi pembeli lukisan"}],"pages":[{"num":1,"narrator":"Anak buka galeri.","dialog":[{"role":"Pelukis","text":"Mau lihat lukisan?"},{"role":"Pembeli","text":"Wah! Lukisan bagus!"},{"role":"Pelukis","text":"Ini gambar apa?"}]},{"num":2,"narrator":"Pelukis cerita lukisan pertama.","dialog":[{"role":"Pelukis","text":"Ini rumah dan pohon."},{"role":"Pembeli","text":"Cantik! Aku mau beli."},{"role":"Pelukis","text":"Terima kasih!"}]},{"num":3,"narrator":"Lihat lukisan kedua.","dialog":[{"role":"Pembeli","text":"Yang ini apa?"},{"role":"Pelukis","text":"Gunung dan sungai."},{"role":"Pembeli","text":"Indah!"}]},{"num":4,"narrator":"Lukis pesanan.","dialog":[{"role":"Pembeli","text":"Mau pesan lukisan."},{"role":"Pelukis","text":"Mau gambar apa?"},{"role":"Pembeli","text":"Kucing kesayangan."}]},{"num":5,"narrator":"Pelukis melukis.","dialog":[{"role":"Pelukis","text":"Gambar kucing dulu."},{"role":"Pembeli","text":"Mata besar ya."},{"role":"Pelukis","text":"Betul! Lucu."}]},{"num":6,"narrator":"Tambah warna.","dialog":[{"role":"Pelukis","text":"Tambah warna oranye."},{"role":"Pembeli","text":"Seperti kucingku!"},{"role":"Pelukis","text":"Hampir selesai."}]},{"num":7,"narrator":"Lukisan selesai.","dialog":[{"role":"Pelukis","text":"Sudah jadi!"},{"role":"Pembeli","text":"Cantik! Makasih!"},{"role":"Pelukis","text":"Senang melukis."}]},{"num":8,"narrator":"Galeri tutup.","dialog":[{"role":"Pembeli","text":"Aku pajang di kamar."},{"role":"Pelukis","text":"Mau lukis lagi."},{"role":"Pembeli","text":"Aku mau pesan lagi!"}]}]}',
                'desc' => 'Anak jadi pelukis jual lukisan',
                'image' => NULL,
                'moral' => 'Karya seni itu berharga.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif"]',
                'slug' => 'main-pelukis-jual-lukisan',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Pelukis Jual Lukisan',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Satpam","emoji":"🛡️","desc":"Anak jadi satpam"},{"name":"Pengunjung","emoji":"😊","desc":"Teman jadi pengunjung"}],"pages":[{"num":1,"narrator":"Anak jaga pintu.","dialog":[{"role":"Satpam","text":"Siapa? Kartu akses?"},{"role":"Pengunjung","text":"Mau masuk."},{"role":"Satpam","text":"Ini kartuku."}]},{"num":2,"narrator":"Satpam cek kartu.","dialog":[{"role":"Satpam","text":"Kartu valid."},{"role":"Pengunjung","text":"Boleh masuk?"},{"role":"Satpam","text":"Silakan."}]},{"num":3,"narrator":"Pengunjung masuk.","dialog":[{"role":"Satpam","text":"Hati-hati ya."},{"role":"Pengunjung","text":"Makasih."},{"role":"Satpam","text":"Lantai licin."}]},{"num":4,"narrator":"Satpam jaga malam.","dialog":[{"role":"Satpam","text":"Malam. Jaga terus."},{"role":"Pengunjung","text":"Masih di sini?"},{"role":"Satpam","text":"Ya. Aman."}]},{"num":5,"narrator":"Ada suara mencurigakan.","dialog":[{"role":"Satpam","text":"Apa suara itu?"},{"role":"Pengunjung","text":"Kucing."},{"role":"Satpam","text":"Aman. Bukan maling."}]},{"num":6,"narrator":"Pengunjung pulang.","dialog":[{"role":"Pengunjung","text":"Pulang dulu."},{"role":"Satpam","text":"Hati-hati di jalan."},{"role":"Pengunjung","text":"Sampai jumpa!"}]},{"num":7,"narrator":"Satpam sendiri.","dialog":[{"role":"Satpam","text":"Jaga terus. Aman."},{"role":"Satpam","text":"Tidak boleh tidur."},{"role":"Satpam","text":"Tanggung jawab."}]},{"num":8,"narrator":"Pagi tiba.","dialog":[{"role":"Satpam","text":"Pagi! Tugas selesai."},{"role":"Pengunjung","text":"Selamat pagi!"},{"role":"Satpam","text":"Selamat pagi! Aman."}]}]}',
                'desc' => 'Anak jadi satpam jaga pintu',
                'image' => NULL,
                'moral' => 'Menjaga itu tanggung jawab.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["bertanggung_jawab"]',
                'slug' => 'main-satpam-jaga-pintu',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Satpam Jaga Pintu',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"roles":[{"name":"Tukang Kebun","emoji":"🌻","desc":"Anak jadi tukang kebun"},{"name":"Teman","emoji":"😊","desc":"Teman bantu"}],"pages":[{"num":1,"narrator":"Anak jadi tukang kebun.","dialog":[{"role":"Tukang Kebun","text":"Kebun perlu dirawat."},{"role":"Teman","text":"Bantu ya!"},{"role":"Tukang Kebun","text":"Ayo cabut rumput."}]},{"num":2,"narrator":"Cabut rumput.","dialog":[{"role":"Tukang Kebun","text":"Tarik pelan."},{"role":"Teman","text":"Sudah. Bersih!"},{"role":"Tukang Kebun","text":"Bagus!"}]},{"num":3,"narrator":"Siram tanaman.","dialog":[{"role":"Tukang Kebun","text":"Siram bunga pelan."},{"role":"Teman","text":"Sudah. Segar!"},{"role":"Tukang Kebun","text":"Tambah pupuk."}]},{"num":4,"narrator":"Tambah pupuk.","dialog":[{"role":"Tukang Kebun","text":"Tabur pupuk sedikit."},{"role":"Teman","text":"Biar subur?"},{"role":"Tukang Kebun","text":"Betul!"}]},{"num":5,"narrator":"Tanam bunga baru.","dialog":[{"role":"Tukang Kebun","text":"Tanam bunga baru."},{"role":"Teman","text":"Warna apa?"},{"role":"Tukang Kebun","text":"Merah dan kuning."}]},{"num":6,"narrator":"Siram bunga baru.","dialog":[{"role":"Teman","text":"Sudah ditanam."},{"role":"Tukang Kebun","text":"Siram pelan ya."},{"role":"Teman","text":"Sudah!"}]},{"num":7,"narrator":"Bunga mekar.","dialog":[{"role":"Teman","text":"Bunga mekar!"},{"role":"Tukang Kebun","text":"Karena dirawat."},{"role":"Teman","text":"Cantik!"}]},{"num":8,"narrator":"Kebun indah.","dialog":[{"role":"Tukang Kebun","text":"Kebun sudah indah."},{"role":"Teman","text":"Mau rawat lagi!"},{"role":"Tukang Kebun","text":"Setiap hari ya."}]}]}',
                'desc' => 'Anak jadi tukang kebun',
                'image' => NULL,
                'moral' => 'Merawat tanaman itu sabar.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["menjaga_alam"]',
                'slug' => 'main-tukang-kebun-rawat-bunga',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Main Tukang Kebun Rawat Bunga',
                'type' => 'bermain_peran',
                'views' => 0,
            ],
        ];

        DB::table("activities")->insertOrIgnore($dataTables);
    }
}
