<?php

namespace Database\Seeders\Activity;

use App\ActivityType;
use App\Models\Activity;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IlmuPengetahuanSeeder extends Seeder
{
    public function run(): void
    {
        $dataTables = [
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Ambil es batu dari kulkas. Dingin ya! Masukkan ke mangkuk."},{"num":2,"text":"Letakkan mangkuk di bawah matahari. Amati apa yang terjadi."},{"num":3,"text":"Es batu mencair! Jadi air. Kenapa ya? Karena panas."}]}',
                'desc' => 'Eksperimen sederhana tentang perubahan wujud benda.',
                'image' => 'cover.png',
                'moral' => 'Anak belajar tentang perubahan wujud benda.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif"]',
                'slug' => 'es-batu-yang-mencair',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Es Batu yang Mencair',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Isi pot dengan tanah. Tanam benih kacang hijau."},{"num":2,"text":"Siram air setiap pagi. Letakkan di tempat terang."},{"num":3,"text":"Amati setiap hari. Catat perubahannya di buku."},{"num":4,"text":"Hari ketiga, ada tunas kecil hijau muncul!"},{"num":5,"text":"Tunas jadi batang. Daun mulai tumbuh."},{"num":6,"text":"Siram terus. Jangan lupa ya."},{"num":7,"text":"Tanaman makin besar. Akarnya kuat."},{"num":8,"text":"Berhasil! Benih jadi tanaman. Butuh sabar."}]}',
                'desc' => 'Menanam benih dan mengamati pertumbuhannya.',
                'image' => 'cover.png',
                'moral' => 'Tumbuhan butuh air dan sinar matahari.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen"]',
                'slug' => 'benih-yang-tumbuh',
                'sort_order' => 1,
                'status' => 'pending',
                'title' => 'Benih yang Tumbuh',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan gelas air bening dan kertas putih."},{"num":2,"text":"Letakkan gelas di dekat jendela yang terkena sinar matahari."},{"num":3,"text":"Arahkan kertas di belakang gelas. Lihat! Ada warna pelangi!"}]}',
                'desc' => 'Membuat pelangi kecil dari air dan sinar matahari.',
                'image' => 'cover.png',
                'moral' => 'Pelangi tercipta dari cahaya dan air.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen"]',
                'slug' => 'pelangi-dari-air',
                'sort_order' => 2,
                'status' => 'pending',
                'title' => 'Pelangi dari Air',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan magnet kecil dan beberapa benda: klip, pensil, koin, sendok."},{"num":2,"text":"Dekatkan magnet ke setiap benda. Mana yang tertarik?"},{"num":3,"text":"Klip dan sendok tertarik! Pensil dan koin tidak."},{"num":4,"text":"Kenapa? Karena klip dan sendok terbuat dari besi."},{"num":5,"text":"Coba cari benda lain di rumah. Mana yang tertarik magnet?"},{"num":6,"text":"Kulkas bisa ditempeli magnet! Karena terbuat dari besi."},{"num":7,"text":"Magnet punya dua kutub: utara dan selatan."},{"num":8,"text":"Eksperimen selesai! Magnet itu seru."}]}',
                'desc' => 'Eksperimen sederhana tentang daya tarik magnet.',
                'image' => 'cover.png',
                'moral' => 'Magnet bisa menarik benda tertentu.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["memecahkan_masalah"]',
                'slug' => 'magnet-ajaib',
                'sort_order' => 3,
                'status' => 'pending',
                'title' => 'Magnet Ajaib',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[6,7,8,9,10]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan cuka dan baking soda. Mau coba sesuatu!"},{"num":2,"text":"Masukkan baking soda ke gelas."},{"num":3,"text":"Tuang cuka pelan-pelan."},{"num":4,"text":"Wah! Ada gelembung! Seperti gunung berapi kecil."},{"num":5,"text":"Gelembung itu gas karbon dioksida."},{"num":6,"text":"Reaksi kimia terjadi saat dua bahan bertemu."},{"num":7,"text":"Coba lagi dengan takaran beda. Lebih banyak gelembung?"},{"num":8,"text":"Eksperimen kimia itu seru dan aman!"}]}',
                'desc' => 'Reaksi kimia sederhana dari kapur dan cuka.',
                'image' => 'cover.png',
                'moral' => 'Campur dua bahan bisa bikin reaksi seru.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen"]',
                'slug' => 'kapur-dan-cuka',
                'sort_order' => 4,
                'status' => 'pending',
                'title' => 'Kapur dan Cuka',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[6,7,8,9,10]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan telur rebus yang sudah dikupas dan botol mulut lebar."},{"num":2,"text":"Nyalakan korek api, masukkan ke botol sebentar."},{"num":3,"text":"Letakkan telur di mulut botol. Amati!"},{"num":4,"text":"Telur masuk sendiri ke botol! Wah!"},{"num":5,"text":"Kenapa? Karena api membakar oksigen di botol."},{"num":6,"text":"Tekanan udara luar mendorong telur masuk."},{"num":7,"text":"Coba keluarkan telur: balik botol, kasih air hangat."},{"num":8,"text":"Fisika itu seru! Banyak hal luar biasa."}]}',
                'desc' => 'Eksperimen fisika tentang tekanan udara.',
                'image' => 'cover.png',
                'moral' => 'Tekanan udara bisa melakukan hal luar biasa.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["memecahkan_masalah"]',
                'slug' => 'telur-masuk-botol',
                'sort_order' => 5,
                'status' => 'pending',
                'title' => 'Telur Masuk Botol',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan cat air merah, kuning, dan biru."},{"num":2,"text":"Campur merah dan kuning. Apa jadinya?"},{"num":3,"text":"Jadi oranye! Seru!"},{"num":4,"text":"Campur kuning dan biru. Apa jadinya?"},{"num":5,"text":"Jadi hijau! Cantik!"},{"num":6,"text":"Campur merah dan biru. Apa jadinya?"},{"num":7,"text":"Jadi ungu! Wah!"},{"num":8,"text":"Tiga warna jadi banyak warna. Kreatif!"}]}',
                'desc' => 'Eksperimen mencampur warna primer.',
                'image' => 'cover.png',
                'moral' => 'Campur warna bisa bikin warna baru.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif"]',
                'slug' => 'warna-campur',
                'sort_order' => 6,
                'status' => 'pending',
                'title' => 'Warna Campur',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Ambil kertas persegi. Lipat dua."},{"num":2,"text":"Lipat sudut ke tengah. Jadi segitiga."},{"num":3,"text":"Lipat bawah ke atas. Balik. Lipat lagi."},{"num":4,"text":"Buka jadi segitiga besar. Lipat bawah ke atas."},{"num":5,"text":"Bentuk jadi kapal. Tarik ujungnya."},{"num":6,"text":"Kapal kertas jadi! Masukkan ke air."},{"num":7,"text":"Kapal mengapung! Seru!"},{"num":8,"text":"Coba hias kapal pakai spidol. Kapal perang!"}]}',
                'desc' => 'Membuat kapal kertas dan mengapungkannya.',
                'image' => 'cover.png',
                'moral' => 'Kertas bisa jadi kapal kalau dilipat dengan benar.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif"]',
                'slug' => 'kapal-kertas',
                'sort_order' => 7,
                'status' => 'pending',
                'title' => 'Kapal Kertas',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[7,8,9,10]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Ambil daun hijau dari pohon."},{"num":2,"text":"Letakkan di atas kertas putih di bawah sinar matahari."},{"num":3,"text":"Tutupi sebagian daun dengan kertas hitam."},{"num":4,"text":"Tunggu beberapa jam. Angkat kertas hitam."},{"num":5,"text":"Bagian yang tertutup lebih pucat!"},{"num":6,"text":"Sinar matahari membantu daun tetap hijau."},{"num":7,"text":"Tumbuhan pakai sinar untuk bikin makanan."},{"num":8,"text":"Itu namanya fotosintesis. Seru!"}]}',
                'desc' => 'Eksperimen tentang fotosintesis sederhana.',
                'image' => 'cover.png',
                'moral' => 'Tumbuhan membuat makanan dari sinar matahari.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen"]',
                'slug' => 'daun-dan-sinar',
                'sort_order' => 8,
                'status' => 'pending',
                'title' => 'Daun dan Sinar',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan segelas air dan satu sendok garam."},{"num":2,"text":"Masukkan garam ke air. Aduk rata."},{"num":3,"text":"Garam hilang! Tapi air jadi asin."},{"num":4,"text":"Coba minum sedikit. Asin ya!"},{"num":5,"text":"Garam tidak hilang. Dia larut di air."},{"num":6,"text":"Kalau airnya dijemur, garamnya muncul lagi!"},{"num":7,"text":"Larut itu artinya bercampur rata."},{"num":8,"text":"Banyak benda bisa larut di air. Coba gula!"}]}',
                'desc' => 'Eksperimen melarutkan garam dalam air.',
                'image' => 'cover.png',
                'moral' => 'Garam bisa hilang di dalam air tapi masih ada.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen"]',
                'slug' => 'garam-dan-air',
                'sort_order' => 9,
                'status' => 'pending',
                'title' => 'Garam dan Air',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan dua gelas air dan dua telur."},{"num":2,"text":"Masukkan telur ke gelas air biasa. Tenggelam!"},{"num":3,"text":"Masukkan garam banyak ke gelas kedua. Aduk."},{"num":4,"text":"Masukkan telur ke air garam. Apa terjadi?"},{"num":5,"text":"Telur terapung! Wah!"},{"num":6,"text":"Air garam lebih berat dari air biasa."},{"num":7,"text":"Itu sebabnya telur bisa mengapung."},{"num":8,"text":"Laut asin, jadi kita lebih mudah mengapung!"}]}',
                'desc' => 'Eksperimen tentang densitas air garam.',
                'image' => 'cover.png',
                'moral' => 'Air garam lebih berat dari air biasa.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["memecahkan_masalah"]',
                'slug' => 'telur-terapung',
                'sort_order' => 10,
                'status' => 'pending',
                'title' => 'Telur Terapung',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Matikan lampu. Nyalakan senter ke dinding."},{"num":2,"text":"Letakkan tangan di depan senter. Ada bayangan!"},{"num":3,"text":"Coba bentuk kelinci dengan jari. Lucu!"},{"num":4,"text":"Bentuk burung. Terbang!"},{"num":5,"text":"Makin dekat tangan ke senter, makin besar bayangan."},{"num":6,"text":"Makin jauh, makin kecil."},{"num":7,"text":"Bayangan terbentuk karena cahaya terhalang."},{"num":8,"text":"Coba bentuk lain! Kreatif!"}]}',
                'desc' => 'Bermain bayangan dengan tangan dan senter.',
                'image' => 'cover.png',
                'moral' => 'Bayangan terbentuk karena cahaya terhalang.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'bayangan-tangan',
                'sort_order' => 11,
                'status' => 'pending',
                'title' => 'Bayangan Tangan',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[7,8,9,10]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan jarum, magnet, gabus, dan mangkuk air."},{"num":2,"text":"Gosok jarum dengan magnet sebanyak 30 kali."},{"num":3,"text":"Tusukkan jarum ke gabus kecil."},{"num":4,"text":"Letakkan gabus di mangkuk air."},{"num":5,"text":"Gabus berputar! Jarum menunjuk utara-selatan."},{"num":6,"text":"Itu prinsip kompas!"},{"num":7,"text":"Coba putar mangkuk. Jarum tetap menunjuk utara."},{"num":8,"text":"Kompas membantu navigasi. Seru!"}]}',
                'desc' => 'Membuat kompas dari jarum dan magnet.',
                'image' => 'cover.png',
                'moral' => 'Kompas menunjukkan arah utara.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["belajar_hal_baru"]',
                'slug' => 'kompas-sederhana',
                'sort_order' => 12,
                'status' => 'pending',
                'title' => 'Kompas Sederhana',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[6,7,8,9,10]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Buat gunung dari tanah liat di atas nampan."},{"num":2,"text":"Lubangi puncaknya. Masukkan baking soda."},{"num":3,"text":"Tambah pewarna makanan merah."},{"num":4,"text":"Tuang cuka ke lubang. Siap-siap!"},{"num":5,"text":"Wah! Letusan! Ada busa merah keluar!"},{"num":6,"text":"Cuka dan baking soda bikin gas."},{"num":7,"text":"Gas itu yang bikin letusan."},{"num":8,"text":"Gunung berapi sungguhan juga begitu!"}]}',
                'desc' => 'Membuat gunung berapi mini dari baking soda.',
                'image' => 'cover.png',
                'moral' => 'Gunung berapi meletus karena tekanan gas.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen"]',
                'slug' => 'vulkan-mini',
                'sort_order' => 13,
                'status' => 'pending',
                'title' => 'Vulkan Mini',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan magnet kecil dan beberapa benda kecil."},{"num":2,"text":"Dekatkan magnet ke klip kertas. Wah, menempel!"},{"num":3,"text":"Dekatkan magnet ke pensil. Tidak menempel."},{"num":4,"text":"Dekatkan magnet ke sendok logam. Menempel!"},{"num":5,"text":"Dekatkan magnet ke koin. Tidak menempel."},{"num":6,"text":"Magnet hanya menarik benda dari besi."},{"num":7,"text":"Coba cari benda lain yang tertarik magnet!"},{"num":8,"text":"Magnet itu seru! Punya dua kutub utara dan selatan."}]}',
                'desc' => 'Eksperimen sederhana tentang daya tarik magnet.',
                'image' => 'cover.png',
                'moral' => 'Magnet hanya menarik benda yang terbuat dari besi.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","memecahkan_masalah"]',
                'slug' => 'magnet-dan-peniti',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Magnet dan Peniti',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan dua gelas air dan beberapa benda kecil."},{"num":2,"text":"Masukkan batu ke gelas. Tenggelam!"},{"num":3,"text":"Masukkan gabus ke gelas. Mengapung!"},{"num":4,"text":"Masukkan koin ke gelas. Tenggelam!"},{"num":5,"text":"Masukkan pensil ke gelas. Mengapung!"},{"num":6,"text":"Benda yang ringan bisa mengapung."},{"num":7,"text":"Benda yang berat akan tenggelam."},{"num":8,"text":"Coba benda lain! Mana yang mengapung?"}]}',
                'desc' => 'Eksperimen tentang benda yang mengapung dan tenggelam.',
                'image' => 'cover.png',
                'moral' => 'Benda berat tenggelam dan benda ringan mengapung.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","berpikir_logis"]',
                'slug' => 'air-yang-mengambang',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Air yang Mengambang',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan gelas bening dan air."},{"num":2,"text":"Isi gelas dengan air sampai setengah."},{"num":3,"text":"Letakkan di dekat jendela yang terkena matahari."},{"num":4,"text":"Letakkan kertas putih di belakang gelas."},{"num":5,"text":"Lihat! Ada warna pelangi di kertas!"},{"num":6,"text":"Cahaya matahari terurai jadi tujuh warna."},{"num":7,"text":"Itulah warna pelangi yang indah."},{"num":8,"text":"Pelangi terbentuk dari cahaya dan air!"}]}',
                'desc' => 'Membuat pelangi kecil dari gelas air.',
                'image' => 'cover.png',
                'moral' => 'Pelangi terbentuk dari cahaya yang terurai.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","mengenal_warna"]',
                'slug' => 'pelangi-di-gelas',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Pelangi di Gelas',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan lilin kecil dan korek api."},{"num":2,"text":"Nyalakan lilin. Amati apinya."},{"num":3,"text":"Tutup lilin dengan gelas bening."},{"num":4,"text":"Api lilin padam sendiri!"},{"num":5,"text":"Kenapa? Karena oksigen habis."},{"num":6,"text":"Api butuh oksigen untuk menyala."},{"num":7,"text":"Tanpa oksigen, api tidak bisa hidup."},{"num":8,"text":"Itu sebabnya kita butuh udara untuk bernapas!"}]}',
                'desc' => 'Eksperimen tentang hubungan api dan udara.',
                'image' => 'cover.png',
                'moral' => 'Api butuh oksigen untuk bisa menyala.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","berpikir_logis"]',
                'slug' => 'lilin-dan-udara',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lilin dan Udara',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan biji kacang hijau dan pot kecil."},{"num":2,"text":"Isi pot dengan tanah sampai penuh."},{"num":3,"text":"Tanam biji di dalam tanah. Tutup tipis."},{"num":4,"text":"Siram air setiap pagi secukupnya."},{"num":5,"text":"Letakkan di tempat yang kena matahari."},{"num":6,"text":"Tunggu beberapa hari. Ada tunas muncul!"},{"num":7,"text":"Tunas jadi batang kecil yang hijau."},{"num":8,"text":"Tumbuhan butuh air dan sinar matahari!"}]}',
                'desc' => 'Menanam biji dan mengamati pertumbuhannya.',
                'image' => 'cover.png',
                'moral' => 'Tumbuhan butuh air dan sinar matahari untuk tumbuh.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","sabar"]',
                'slug' => 'tumbuhan-dari-biji',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Tumbuhan dari Biji',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[6,7,8,9,10]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan jarum, magnet, gabus, dan mangkuk air."},{"num":2,"text":"Gosok jarum dengan magnet sebanyak 30 kali."},{"num":3,"text":"Tusukkan jarum ke gabus kecil."},{"num":4,"text":"Letakkan gabus di mangkuk air."},{"num":5,"text":"Gabus berputar! Jarum menunjuk utara-selatan."},{"num":6,"text":"Itu prinsip kompas sederhana!"},{"num":7,"text":"Coba putar mangkuk. Jarum tetap menunjuk utara."},{"num":8,"text":"Kompas membantu kita tahu arah!"}]}',
                'desc' => 'Membuat kompas dari jarum dan magnet.',
                'image' => 'cover.png',
                'moral' => 'Kompas menunjukkan arah utara dan selatan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","belajar_hal_baru"]',
                'slug' => 'kompas-sederhana',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Kompas Sederhana',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan kertas putih dan pensil."},{"num":2,"text":"Letakkan kertas di luar rumah saat matahari terik."},{"num":3,"text":"Letakkan mainan di atas kertas."},{"num":4,"text":"Tunggu beberapa jam di bawah sinar matahari."},{"num":5,"text":"Angkat mainan. Ada bayangan yang tercetak!"},{"num":6,"text":"Bagian yang tertutup tetap putih."},{"num":7,"text":"Bagian yang terkena matahari berubah warna."},{"num":8,"text":"Matahari bisa mencetak bayangan di kertas!"}]}',
                'desc' => 'Eksperimen tentang bayangan dari sinar matahari.',
                'image' => 'cover.png',
                'moral' => 'Sinar matahari bisa mencetak bayangan benda.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","pengamatan"]',
                'slug' => 'bayangan-matahari',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Bayangan Matahari',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Ambil es batu dari kulkas. Dingin ya!"},{"num":2,"text":"Letakkan es batu di mangkuk."},{"num":3,"text":"Amati es batunya. Ada air menetes."},{"num":4,"text":"Es batu mencair jadi air!"},{"num":5,"text":"Kenapa? Karena suhu ruangan lebih hangat."},{"num":6,"text":"Es berubah wujud dari padat jadi cair."},{"num":7,"text":"Kalau airnya dijemur, jadi uap!"},{"num":8,"text":"Benda bisa berubah wujud karena suhu."}]}',
                'desc' => 'Eksperimen tentang perubahan wujud es batu.',
                'image' => 'cover.png',
                'moral' => 'Es batu mencair karena suhu yang lebih hangat.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","pengamatan"]',
                'slug' => 'es-batu-mencair',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Es Batu Mencair',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan cat air merah dan cat air kuning."},{"num":2,"text":"Celupkan kuas ke cat merah."},{"num":3,"text":"Lalu celupkan ke cat kuning."},{"num":4,"text":"Aduk di palet. Wah, jadi oranye!"},{"num":5,"text":"Campur kuning dan biru. Jadinya hijau!"},{"num":6,"text":"Campur merah dan biru. Jadinya ungu!"},{"num":7,"text":"Tiga warna dasar bisa jadi banyak warna."},{"num":8,"text":"Warna itu seru! Coba campur lagi!"}]}',
                'desc' => 'Eksperimen mencampur warna dasar.',
                'image' => 'cover.png',
                'moral' => 'Campur warna dasar bisa menghasilkan warna baru.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","mengenal_warna"]',
                'slug' => 'warna-yang-berubah',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Warna yang Berubah',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan telur rebus dan botol mulut lebar."},{"num":2,"text":"Kupas telur rebus sampai bersih."},{"num":3,"text":"Nyalakan korek api, masukkan ke botol."},{"num":4,"text":"Letakkan telur di mulut botol."},{"num":5,"text":"Telur masuk sendiri ke botol!"},{"num":6,"text":"Api membakar oksigen di dalam botol."},{"num":7,"text":"Tekanan udara luar mendorong telur masuk."},{"num":8,"text":"Tekanan udara itu kuat dan luar biasa!"}]}',
                'desc' => 'Eksperimen tentang tekanan udara.',
                'image' => 'cover.png',
                'moral' => 'Tekanan udara bisa mendorong benda masuk botol.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","memecahkan_masalah"]',
                'slug' => 'telur-masuk-botol',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Telur Masuk Botol',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan segelas air dan sendok garam."},{"num":2,"text":"Masukkan garam ke dalam air."},{"num":3,"text":"Aduk rata sampai garam hilang."},{"num":4,"text":"Coba minum sedikit. Airnya asin!"},{"num":5,"text":"Garam tidak hilang, tapi larut di air."},{"num":6,"text":"Kalau airnya dijemur, garamnya muncul lagi."},{"num":7,"text":"Larut artinya bercampur rata dengan air."},{"num":8,"text":"Banyak benda bisa larut di air. Coba gula!"}]}',
                'desc' => 'Eksperimen melarutkan garam dalam air.',
                'image' => 'cover.png',
                'moral' => 'Garam larut di air tapi tidak hilang.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","pengamatan"]',
                'slug' => 'garam-dan-air',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Garam dan Air',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan kertas dan mangkuk berisi air."},{"num":2,"text":"Lipat kertas jadi bentuk kapal kecil."},{"num":3,"text":"Letakkan kapal kertas di atas air."},{"num":4,"text":"Kapal mengapung! Wah, seru!"},{"num":5,"text":"Kertas bisa mengapung karena ringan."},{"num":6,"text":"Coba tiup kapal pelan-pelan. Jalan!"},{"num":7,"text":"Kalau kertasnya basah, kapal tenggelam."},{"num":8,"text":"Benda ringan bisa mengapung di air!"}]}',
                'desc' => 'Membuat kapal kertas dan mengapungkannya.',
                'image' => 'cover.png',
                'moral' => 'Benda ringan bisa mengapung di air.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","eksperimen"]',
                'slug' => 'kapal-kertas-terapung',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Kapal Kertas Terapung',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Buka kulkas di rumah. Lihat pintunya."},{"num":2,"text":"Ada magnet menempel di pintu kulkas!"},{"num":3,"text":"Coba lepas magnet. Ada tarikan kuat."},{"num":4,"text":"Tempelkan magnet ke pintu kulkas lagi."},{"num":5,"text":"Magnet menempel kuat di kulkas."},{"num":6,"text":"Kulkas terbuat dari besi di dalamnya."},{"num":7,"text":"Magnet bisa menempel di benda besi."},{"num":8,"text":"Coba cari benda lain yang bisa ditempeli magnet!"}]}',
                'desc' => 'Eksperimen magnet di kulkas rumah.',
                'image' => 'cover.png',
                'moral' => 'Magnet bisa menempel di benda yang terbuat dari besi.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","pengamatan"]',
                'slug' => 'magnet-di-kulkas',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Magnet di Kulkas',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[6,7,8,9,10]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan prisma segitiga dari kaca."},{"num":2,"text":"Arahkan senter ke prisma dari samping."},{"num":3,"text":"Lihat di sisi lain! Ada warna pelangi!"},{"num":4,"text":"Cahaya putih terurai jadi tujuh warna."},{"num":5,"text":"Merah, jingga, kuning, hijau, biru, nila, ungu."},{"num":6,"text":"Itulah spektrum warna cahaya."},{"num":7,"text":"Prisma membelah cahaya jadi warna-warna."},{"num":8,"text":"Pelangi di langit juga terbentuk seperti ini!"}]}',
                'desc' => 'Eksperimen membelah cahaya dengan prisma.',
                'image' => 'cover.png',
                'moral' => 'Cahaya putih terdiri dari tujuh warna.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","mengenal_warna"]',
                'slug' => 'pelangi-dari-prisma',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Pelangi dari Prisma',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan tanaman kecil di pot."},{"num":2,"text":"Letakkan tanaman di dekat jendela terang."},{"num":3,"text":"Amati! Tanaman condong ke jendela."},{"num":4,"text":"Pindahkan tanaman ke sisi lain."},{"num":5,"text":"Beberapa hari lagi, tanaman condong ke cahaya baru."},{"num":6,"text":"Tumbuhan selalu mencari cahaya matahari."},{"num":7,"text":"Cahaya membantu tumbuhan membuat makanan."},{"num":8,"text":"Itu namanya fototropisme. Seru!"}]}',
                'desc' => 'Eksperimen tentang tumbuhan mencari cahaya.',
                'image' => 'cover.png',
                'moral' => 'Tumbuhan selalu tumbuh ke arah cahaya matahari.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","pengamatan"]',
                'slug' => 'tumbuhan-tumbuh-ke-cahaya',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Tumbuhan Tumbuh ke Cahaya',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan tiga gelas air bening."},{"num":2,"text":"Teteskan pewarna merah ke gelas pertama."},{"num":3,"text":"Teteskan pewarna biru ke gelas kedua."},{"num":4,"text":"Teteskan pewarna kuning ke gelas ketiga."},{"num":5,"text":"Aduk masing-masing. Air berubah warna!"},{"num":6,"text":"Campur air merah dan biru. Jadi ungu!"},{"num":7,"text":"Campur air kuning dan merah. Jadi oranye!"},{"num":8,"text":"Air bisa berubah warna kalau dicampur pewarna!"}]}',
                'desc' => 'Eksperimen mengubah warna air.',
                'image' => 'cover.png',
                'moral' => 'Air bisa berubah warna dengan pewarna.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","mengenal_warna"]',
                'slug' => 'air-berubah-warna',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Air Berubah Warna',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Ambil bola karet dan bawa ke luar rumah."},{"num":2,"text":"Jatuhkan bola dari atas tanpa dilempar."},{"num":3,"text":"Bola memantul ke atas!"},{"num":4,"text":"Jatuhkan lagi dari ketinggian berbeda."},{"num":5,"text":"Makin tinggi dijatuhkan, makin tinggi mantulnya."},{"num":6,"text":"Bola memantul karena ada gaya pegas."},{"num":7,"text":"Coba bandingkan bola karet dan bola plastik."},{"num":8,"text":"Bola yang lebih keras mantul lebih tinggi!"}]}',
                'desc' => 'Eksperimen tentang bola yang memantul.',
                'image' => 'cover.png',
                'moral' => 'Bola memantul karena gaya pegas di dalamnya.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","pengamatan"]',
                'slug' => 'bola-memantul',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Bola Memantul',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Ambil daun hijau dari pohon."},{"num":2,"text":"Masukkan daun ke dalam gelas berisi air."},{"num":3,"text":"Letakkan gelas di bawah sinar matahari."},{"num":4,"text":"Amati beberapa jam. Ada gelembung kecil!"},{"num":5,"text":"Gelembung itu adalah oksigen."},{"num":6,"text":"Daun bernapas dan menghasilkan oksigen."},{"num":7,"text":"Tumbuhan menghirup karbon dioksida."},{"num":8,"text":"Tumbuhan memberi kita udara bersih!"}]}',
                'desc' => 'Eksperimen tentang daun yang menghasilkan oksigen.',
                'image' => 'cover.png',
                'moral' => 'Daun menghasilkan oksigen untuk kita bernapas.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","mengenal_alam"]',
                'slug' => 'daun-bernapas',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Daun Bernapas',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Matikan lampu di kamar. Gelap ya!"},{"num":2,"text":"Nyalakan senter ke arah dinding."},{"num":3,"text":"Letakkan tangan di depan senter."},{"num":4,"text":"Ada bayangan tangan di dinding!"},{"num":5,"text":"Bentuk kelinci dengan jari. Lucu!"},{"num":6,"text":"Makin dekat tangan ke senter, makin besar bayangan."},{"num":7,"text":"Makin jauh, makin kecil bayangan."},{"num":8,"text":"Bayangan terbentuk karena cahaya terhalang!"}]}',
                'desc' => 'Bermain bayangan dengan senter dan tangan.',
                'image' => 'cover.png',
                'moral' => 'Bayangan terbentuk karena cahaya terhalang benda.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi","berpikir_kreatif"]',
                'slug' => 'senter-dan-bayangan',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Senter dan Bayangan',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan balon dan sedotan plastik."},{"num":2,"text":"Tiup balon sampai besar, lalu ikat."},{"num":3,"text":"Tempelkan sedotan di bagian bawah balon dengan lakban."},{"num":4,"text":"Tarik tali melalui sedotan."},{"num":5,"text":"Lepas balon! Balon terbang menyusuri tali!"},{"num":6,"text":"Udara keluar dari balon ke belakang."},{"num":7,"text":"Balon bergerak ke depan karena gaya dorong."},{"num":8,"text":"Roket sungguhan juga pakai prinsip yang sama!"}]}',
                'desc' => 'Membuat roket dari balon dan tali.',
                'image' => 'cover.png',
                'moral' => 'Gaya dorong udara bisa membuat benda bergerak.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen","berpikir_kreatif"]',
                'slug' => 'roket-balon',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Roket Balon',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
        ];

        Activity::where('type', ActivityType::ILMU_PENGETAHUAN->value)->delete();
        DB::table("activities")->insertOrIgnore($dataTables);
    }
}
