<?php

namespace Database\Seeders\Activity;

use App\ActivityType;
use App\Models\Activity;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IlmuPengetahuanSeeder extends Seeder
{
    public function run(): void
    {
        $dataTables = [
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Ambil es batu dari kulkas. Dingin ya! Masukkan ke mangkuk."},{"num":2,"text":"Letakkan mangkuk di bawah matahari. Amati apa yang terjadi."},{"num":3,"text":"Es batu mencair! Jadi air. Kenapa ya? Karena panas."}]}',
                'desc' => 'Eksperimen sederhana tentang perubahan wujud benda.',
                'image' => 'cover.png',
                'moral' => 'Anak belajar tentang perubahan wujud benda.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif"]',
                'slug' => 'es-batu-yang-mencair',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Es Batu yang Mencair',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Isi pot dengan tanah. Tanam benih kacang hijau."},{"num":2,"text":"Siram air setiap pagi. Letakkan di tempat terang."},{"num":3,"text":"Amati setiap hari. Catat perubahannya di buku."},{"num":4,"text":"Hari ketiga, ada tunas kecil hijau muncul!"},{"num":5,"text":"Tunas jadi batang. Daun mulai tumbuh."},{"num":6,"text":"Siram terus. Jangan lupa ya."},{"num":7,"text":"Tanaman makin besar. Akarnya kuat."},{"num":8,"text":"Berhasil! Benih jadi tanaman. Butuh sabar."}]}',
                'desc' => 'Menanam benih dan mengamati pertumbuhannya.',
                'image' => 'cover.png',
                'moral' => 'Tumbuhan butuh air dan sinar matahari.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen"]',
                'slug' => 'benih-yang-tumbuh',
                'sort_order' => 1,
                'status' => 'pending',
                'title' => 'Benih yang Tumbuh',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan gelas air bening dan kertas putih."},{"num":2,"text":"Letakkan gelas di dekat jendela yang terkena sinar matahari."},{"num":3,"text":"Arahkan kertas di belakang gelas. Lihat! Ada warna pelangi!"}]}',
                'desc' => 'Membuat pelangi kecil dari air dan sinar matahari.',
                'image' => 'cover.png',
                'moral' => 'Pelangi tercipta dari cahaya dan air.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen"]',
                'slug' => 'pelangi-dari-air',
                'sort_order' => 2,
                'status' => 'pending',
                'title' => 'Pelangi dari Air',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan magnet kecil dan beberapa benda: klip, pensil, koin, sendok."},{"num":2,"text":"Dekatkan magnet ke setiap benda. Mana yang tertarik?"},{"num":3,"text":"Klip dan sendok tertarik! Pensil dan koin tidak."},{"num":4,"text":"Kenapa? Karena klip dan sendok terbuat dari besi."},{"num":5,"text":"Coba cari benda lain di rumah. Mana yang tertarik magnet?"},{"num":6,"text":"Kulkas bisa ditempeli magnet! Karena terbuat dari besi."},{"num":7,"text":"Magnet punya dua kutub: utara dan selatan."},{"num":8,"text":"Eksperimen selesai! Magnet itu seru."}]}',
                'desc' => 'Eksperimen sederhana tentang daya tarik magnet.',
                'image' => 'cover.png',
                'moral' => 'Magnet bisa menarik benda tertentu.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["memecahkan_masalah"]',
                'slug' => 'magnet-ajaib',
                'sort_order' => 3,
                'status' => 'pending',
                'title' => 'Magnet Ajaib',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[6,7,8,9,10]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan cuka dan baking soda. Mau coba sesuatu!"},{"num":2,"text":"Masukkan baking soda ke gelas."},{"num":3,"text":"Tuang cuka pelan-pelan."},{"num":4,"text":"Wah! Ada gelembung! Seperti gunung berapi kecil."},{"num":5,"text":"Gelembung itu gas karbon dioksida."},{"num":6,"text":"Reaksi kimia terjadi saat dua bahan bertemu."},{"num":7,"text":"Coba lagi dengan takaran beda. Lebih banyak gelembung?"},{"num":8,"text":"Eksperimen kimia itu seru dan aman!"}]}',
                'desc' => 'Reaksi kimia sederhana dari kapur dan cuka.',
                'image' => 'cover.png',
                'moral' => 'Campur dua bahan bisa bikin reaksi seru.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen"]',
                'slug' => 'kapur-dan-cuka',
                'sort_order' => 4,
                'status' => 'pending',
                'title' => 'Kapur dan Cuka',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[6,7,8,9,10]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan telur rebus yang sudah dikupas dan botol mulut lebar."},{"num":2,"text":"Nyalakan korek api, masukkan ke botol sebentar."},{"num":3,"text":"Letakkan telur di mulut botol. Amati!"},{"num":4,"text":"Telur masuk sendiri ke botol! Wah!"},{"num":5,"text":"Kenapa? Karena api membakar oksigen di botol."},{"num":6,"text":"Tekanan udara luar mendorong telur masuk."},{"num":7,"text":"Coba keluarkan telur: balik botol, kasih air hangat."},{"num":8,"text":"Fisika itu seru! Banyak hal luar biasa."}]}',
                'desc' => 'Eksperimen fisika tentang tekanan udara.',
                'image' => 'cover.png',
                'moral' => 'Tekanan udara bisa melakukan hal luar biasa.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["memecahkan_masalah"]',
                'slug' => 'telur-masuk-botol',
                'sort_order' => 5,
                'status' => 'pending',
                'title' => 'Telur Masuk Botol',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan cat air merah, kuning, dan biru."},{"num":2,"text":"Campur merah dan kuning. Apa jadinya?"},{"num":3,"text":"Jadi oranye! Seru!"},{"num":4,"text":"Campur kuning dan biru. Apa jadinya?"},{"num":5,"text":"Jadi hijau! Cantik!"},{"num":6,"text":"Campur merah dan biru. Apa jadinya?"},{"num":7,"text":"Jadi ungu! Wah!"},{"num":8,"text":"Tiga warna jadi banyak warna. Kreatif!"}]}',
                'desc' => 'Eksperimen mencampur warna primer.',
                'image' => 'cover.png',
                'moral' => 'Campur warna bisa bikin warna baru.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif"]',
                'slug' => 'warna-campur',
                'sort_order' => 6,
                'status' => 'pending',
                'title' => 'Warna Campur',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Ambil kertas persegi. Lipat dua."},{"num":2,"text":"Lipat sudut ke tengah. Jadi segitiga."},{"num":3,"text":"Lipat bawah ke atas. Balik. Lipat lagi."},{"num":4,"text":"Buka jadi segitiga besar. Lipat bawah ke atas."},{"num":5,"text":"Bentuk jadi kapal. Tarik ujungnya."},{"num":6,"text":"Kapal kertas jadi! Masukkan ke air."},{"num":7,"text":"Kapal mengapung! Seru!"},{"num":8,"text":"Coba hias kapal pakai spidol. Kapal perang!"}]}',
                'desc' => 'Membuat kapal kertas dan mengapungkannya.',
                'image' => 'cover.png',
                'moral' => 'Kertas bisa jadi kapal kalau dilipat dengan benar.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif"]',
                'slug' => 'kapal-kertas',
                'sort_order' => 7,
                'status' => 'pending',
                'title' => 'Kapal Kertas',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[7,8,9,10]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Ambil daun hijau dari pohon."},{"num":2,"text":"Letakkan di atas kertas putih di bawah sinar matahari."},{"num":3,"text":"Tutupi sebagian daun dengan kertas hitam."},{"num":4,"text":"Tunggu beberapa jam. Angkat kertas hitam."},{"num":5,"text":"Bagian yang tertutup lebih pucat!"},{"num":6,"text":"Sinar matahari membantu daun tetap hijau."},{"num":7,"text":"Tumbuhan pakai sinar untuk bikin makanan."},{"num":8,"text":"Itu namanya fotosintesis. Seru!"}]}',
                'desc' => 'Eksperimen tentang fotosintesis sederhana.',
                'image' => 'cover.png',
                'moral' => 'Tumbuhan membuat makanan dari sinar matahari.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen"]',
                'slug' => 'daun-dan-sinar',
                'sort_order' => 8,
                'status' => 'pending',
                'title' => 'Daun dan Sinar',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan segelas air dan satu sendok garam."},{"num":2,"text":"Masukkan garam ke air. Aduk rata."},{"num":3,"text":"Garam hilang! Tapi air jadi asin."},{"num":4,"text":"Coba minum sedikit. Asin ya!"},{"num":5,"text":"Garam tidak hilang. Dia larut di air."},{"num":6,"text":"Kalau airnya dijemur, garamnya muncul lagi!"},{"num":7,"text":"Larut itu artinya bercampur rata."},{"num":8,"text":"Banyak benda bisa larut di air. Coba gula!"}]}',
                'desc' => 'Eksperimen melarutkan garam dalam air.',
                'image' => 'cover.png',
                'moral' => 'Garam bisa hilang di dalam air tapi masih ada.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen"]',
                'slug' => 'garam-dan-air',
                'sort_order' => 9,
                'status' => 'pending',
                'title' => 'Garam dan Air',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan dua gelas air dan dua telur."},{"num":2,"text":"Masukkan telur ke gelas air biasa. Tenggelam!"},{"num":3,"text":"Masukkan garam banyak ke gelas kedua. Aduk."},{"num":4,"text":"Masukkan telur ke air garam. Apa terjadi?"},{"num":5,"text":"Telur terapung! Wah!"},{"num":6,"text":"Air garam lebih berat dari air biasa."},{"num":7,"text":"Itu sebabnya telur bisa mengapung."},{"num":8,"text":"Laut asin, jadi kita lebih mudah mengapung!"}]}',
                'desc' => 'Eksperimen tentang densitas air garam.',
                'image' => 'cover.png',
                'moral' => 'Air garam lebih berat dari air biasa.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["memecahkan_masalah"]',
                'slug' => 'telur-terapung',
                'sort_order' => 10,
                'status' => 'pending',
                'title' => 'Telur Terapung',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Matikan lampu. Nyalakan senter ke dinding."},{"num":2,"text":"Letakkan tangan di depan senter. Ada bayangan!"},{"num":3,"text":"Coba bentuk kelinci dengan jari. Lucu!"},{"num":4,"text":"Bentuk burung. Terbang!"},{"num":5,"text":"Makin dekat tangan ke senter, makin besar bayangan."},{"num":6,"text":"Makin jauh, makin kecil."},{"num":7,"text":"Bayangan terbentuk karena cahaya terhalang."},{"num":8,"text":"Coba bentuk lain! Kreatif!"}]}',
                'desc' => 'Bermain bayangan dengan tangan dan senter.',
                'image' => 'cover.png',
                'moral' => 'Bayangan terbentuk karena cahaya terhalang.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berimajinasi"]',
                'slug' => 'bayangan-tangan',
                'sort_order' => 11,
                'status' => 'pending',
                'title' => 'Bayangan Tangan',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[7,8,9,10]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Siapkan jarum, magnet, gabus, dan mangkuk air."},{"num":2,"text":"Gosok jarum dengan magnet sebanyak 30 kali."},{"num":3,"text":"Tusukkan jarum ke gabus kecil."},{"num":4,"text":"Letakkan gabus di mangkuk air."},{"num":5,"text":"Gabus berputar! Jarum menunjuk utara-selatan."},{"num":6,"text":"Itu prinsip kompas!"},{"num":7,"text":"Coba putar mangkuk. Jarum tetap menunjuk utara."},{"num":8,"text":"Kompas membantu navigasi. Seru!"}]}',
                'desc' => 'Membuat kompas dari jarum dan magnet.',
                'image' => 'cover.png',
                'moral' => 'Kompas menunjukkan arah utara.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["belajar_hal_baru"]',
                'slug' => 'kompas-sederhana',
                'sort_order' => 12,
                'status' => 'pending',
                'title' => 'Kompas Sederhana',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Buat gunung dari tanah liat di atas nampan."},{"num":2,"text":"Lubangi puncaknya. Masukkan baking soda."},{"num":3,"text":"Tambah pewarna makanan merah."},{"num":4,"text":"Tuang cuka ke lubang. Siap-siap!"},{"num":5,"text":"Wah! Letusan! Ada busa merah keluar!"},{"num":6,"text":"Cuka dan baking soda bikin gas."},{"num":7,"text":"Gas itu yang bikin letusan."},{"num":8,"text":"Gunung berapi sungguhan juga begitu!"}]}',
                'desc' => 'Membuat gunung berapi mini dari baking soda.',
                'image' => 'cover.png',
                'moral' => 'Gunung berapi meletus karena tekanan gas.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["eksperimen"]',
                'slug' => 'vulkan-mini',
                'sort_order' => 13,
                'status' => 'pending',
                'title' => 'Vulkan Mini',
                'type' => 'ilmu_pengetahuan',
                'views' => 0,
            ],
        ];

        Activity::where('type', ActivityType::ILMU_PENGETAHUAN->value)->delete();
        DB::table("activities")->insertOrIgnore($dataTables);
    }
}
