<?php

namespace Database\Seeders\Activity;

use App\ActivityType;
use App\Models\Activity;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class KomikSeeder extends Seeder
{
    public function run(): void
    {
        $samples = [
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[6,7,8]',
                'created_by' => 1,
                'creator' => 'gemini',
                'data' => '{"pages":[{"num":1,"text":"Di kedalaman laut dalam hidup berbagai ikan. Cahaya dari karang bercahaya menjadi penunjuk jalan utama."},{"num":2,"text":"Adik Ikan Lentera: Semalam cahayanya terang sekali. Sekarang semuanya padam dan suasana jadi gelap gulita. Bibi Ikan Hiu Kerdil: Apa yang terjadi ini?"},{"num":3,"text":"Ayah Gurita: Pasti ada yang sengaja merusaknya agar jalanan jadi berbahaya. Kakak Ikan Pedang: Mungkin ikan baru yang belum tahu aturan."},{"num":4,"text":"Adik Ikan Bintang: Jangan bicara sembarangan! Kita tidak punya bukti apa pun. Ayah Gurita: Lalu siapa lagi kalau bukan dia?"},{"num":5,"text":"Suasana jadi tegang. Semua saling curiga dan tidak berani bergerak ke mana-mana."},{"num":6,"text":"Kakek Ikan Belut: Berhentilah menuduh. Gelap saja sudah cukup menyulitkan, jangan tambah keributan."},{"num":7,"text":"Kakek Ikan Belut: Mari berkumpul. Cari tahu apa yang berubah, bukan siapa yang disalahkan."},{"num":8,"text":"Mereka berenang perlahan mendekati karang. Meraba dan mengamati sekelilingnya dengan hati-hati."},{"num":9,"text":"Adik Ikan Lentera: Lihat! Ada endapan lumpur tebal yang menutupi seluruh permukaan karang itu. Bibi Ikan Hiu Kerdil: Itu sebabnya cahayanya tidak terlihat."},{"num":10,"text":"Kakak Ikan Pedang: Arus air kemarin memang membawa banyak lumpur dari dasar palung. Ayah Gurita: Ternyata bukan ulah siapa-siapa."},{"num":11,"text":"Adik Ikan Bintang: Kalau kita bersihkan lapisan lumpur ini, cahayanya pasti bisa menyala kembali."},{"num":12,"text":"Mereka bekerja sama. Ada yang menggerakkan sirip menyapu, ada yang mendorong gumpalan lumpur menjauh."},{"num":13,"text":"Sedikit demi sedikit lapisan kotoran hilang. Perlahan cahaya lembut mulai memancar kembali dari dalam karang."},{"num":14,"text":"Ayah Gurita: Maaf aku sudah terburu menuduh. Kakak Ikan Pedang: Aku juga salah terlalu cepat menduga."},{"num":15,"text":"Laut dalam kembali terang. Semua belajar bahwa masalah terpecahkan lewat pengamatan bukan lewat dugaan semata."}]}',
                'desc' => 'Lampu alami yang menerangi jalur perjalanan tiba-tiba padam. Semua hewan saling curiga sampai mencari penyebab aslinya.',
                'image' => 'cover.png',
                'moral' => 'Moral cerita ini adalah saat terjadi hal yang tidak biasa, langsung menuduh atau merasa takut tidak akan menyelesaikan masalah. Lebih baik tenang, amati keadaan, kumpulkan petunjuk, dan cari akar permasalahannya bersama. Kebenaran dan solusi akan muncul dengan pikiran yang jernih.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["memecahkan_masalah", "kerja_sama", "mengamati", "menghindari_salah_paham", "berpikir_jernih"]',
                'slug' => 'di-negeri-laut-dalam-cahaya-hilang',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Di Negeri Laut Dalam Cahaya Hilang',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[7,8,9]',
                'created_by' => 1,
                'creator' => 'gemini',
                'data' => '{"pages":[{"num":1,"text":"Adik Elang Emas punya sayap yang kuat dan penglihatan tajam. Ia dijuluki Pahlawan Hutan."},{"num":2,"text":"Adik Elang: Aku bisa terbang ke mana saja dan melihat apa saja. Bibi Burung Hantu: Kekuatan itu bukan untuk pamer, tapi untuk menjaga hutan ini."},{"num":3,"text":"Suatu hari ia ingin terbang jauh ke pegunungan. Ia lupa menyebarkan pesan peringatan hujan lebat akan datang."},{"num":4,"text":"Hujan turun deras tanpa peringatan. Beberapa sarang terendam dan jalan setapak menjadi licin berbahaya."},{"num":5,"text":"Adik Elang: Maafkan aku! Aku lebih mementingkan keinginan sendiri daripada tugas. Ayah Elang Tua: Kekuatan tanpa tanggung jawab bisa membawa bahaya."},{"num":6,"text":"Ia segera bertindak. Membantu memindahkan sarang ke tempat lebih tinggi dan mengarahkan jalan yang aman."},{"num":7,"text":"Setelah keadaan aman, ia berkumpul dengan semua warga hutan."},{"num":8,"text":"Adik Elang: Mulai sekarang aku akan mengutamakan tugas. Setiap kekuatan yang aku miliki akan kupakai untuk kebaikan bersama."},{"num":9,"text":"Ia membuat jadwal rutin: memantau cuaca, mengawasi batas hutan, dan selalu siap sedia membantu."},{"num":10,"text":"Beberapa minggu kemudian, ia melihat kabut asap mendekat. Ia segera memberi peringatan ke seluruh penjuru."},{"num":11,"text":"Semua hewan bersiap dan menjauh dari jalur asap. Tidak ada yang terluka atau terjebak."},{"num":12,"text":"Bibi Rusa: Berkat kewaspadaanmu, kita semua selamat. Adik Elang: Itu tugas dan tanggung jawabku."},{"num":13,"text":"Ia belajar bahwa menjadi pahlawan bukan soal kekuatan, tapi soal bisa dipercaya."},{"num":14,"text":"Setiap hari ia bekerja dengan sungguh-sungguh. Semua warga hutan merasa aman dan tenang."},{"num":15,"text":"Adik Elang Emas terbang tinggi dengan bangga. Tanggung jawab membuatnya menjadi pahlawan yang sesungguhnya."}]}',
                'desc' => 'Sebagai penjaga hutan, Adik Elang Emas punya kekuatan terbang tinggi. Ia sadar kekuatan harus dipakai untuk melindungi semua warga, bukan hanya untuk dirinya sendiri.',
                'image' => 'cover.png',
                'moral' => 'Moral cerita ini adalah memiliki kekuatan atau kelebihan berarti memiliki tanggung jawab yang lebih besar. Kita harus menjaga apa yang dipercayakan, bertindak dengan hati-hati, dan memastikan keamanan orang lain. Tanggung jawab membuat kita menjadi pribadi yang bisa diandalkan dan dihormati.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["bertanggung_jawab", "dapat_diandalkan", "melindungi", "berani"]',
                'slug' => 'pahlawan-hutan-tanggung-jawab-sang-penjaga',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Pahlawan Hutan: Tanggung Jawab Sang Penjaga',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[7,8,9,10]',
                'created_by' => 1,
                'creator' => 'gemini',
                'data' => '{"pages":[{"num":1,"text":"Adik Singa Berani terpilih menjadi pemimpin muda di Desa Hewan. Ia punya wibawa dan keberanian."},{"num":2,"text":"Musim kemarau tiba. Aliran sungai utama menyusut drastis. Semua hewan mulai cemas."},{"num":3,"text":"Adik Kuda: Kita harus menggali sumur baru! Adik Gajah: Kita cari sumber air lain di luar desa saja."},{"num":4,"text":"Pendapat berbeda-beda. Tidak ada yang sepakat, pekerjaan tidak kunjung dimulai."},{"num":5,"text":"Adik Singa: Tenanglah. Kita tidak bisa berjalan dengan banyak arah sekaligus. Mari duduk bersama."},{"num":6,"text":"Ia meminta setiap orang menyampaikan pendapatnya. Mendengarkan baik-baik tanpa memotong pembicaraan."},{"num":7,"text":"Adik Singa: Menggali sumur butuh tenaga banyak tapi hasilnya tahan lama. Mencari sumber baru butuh waktu perjalanan jauh."},{"num":8,"text":"Adik Singa: Kita bagi tugas. Sebagian menggali sumur, sebagian lagi mencari petunjuk arah air di sekitar."},{"num":9,"text":"Ia mengatur siapa yang paling kuat untuk menggali, siapa yang paling pandai membaca jalur untuk menjelajah."},{"num":10,"text":"Semua orang merasa dihargai. Mereka bekerja dengan semangat sesuai peran masing-masing."},{"num":11,"text":"Dalam waktu singkat, air ditemukan di dalam tanah dan juga ditemukan aliran air kecil di balik bukit."},{"num":12,"text":"Ayah Kerbau: Berkat kepemimpinanmu, kita bisa menyelesaikan masalah dengan cepat. Adik Singa: Ini hasil kerja kita semua."},{"num":13,"text":"Ia mengajarkan bahwa pemimpin harus bisa menyatukan hati, bukan hanya memberi perintah."},{"num":14,"text":"Desa Hewan menjadi makmur. Setiap ada masalah, semua orang percaya pada cara penyelesaiannya."},{"num":15,"text":"Adik Singa tersenyum. Kepemimpinan yang bijak membawa kebahagiaan bagi seluruh warga."}]}',
                'desc' => 'Saat sungai kering, semua bingung. Adik Singa Berani memimpin dengan bijak, mendengarkan pendapat semua orang dan mengambil keputusan terbaik untuk kepentingan bersama.',
                'image' => 'cover.png',
                'moral' => 'Moral cerita ini adalah kepemimpinan yang baik bukan soal memerintah, tapi soal mengajak, mendengarkan, dan menyatukan kekuatan. Pemimpin yang baik bisa melihat kelebihan setiap orang dan mengarahkannya untuk mencapai tujuan bersama.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["leadership", "bermusyawarah", "menyatukan", "membuat_keputusan"]',
                'slug' => 'pemimpin-cerdas-di-desa-hewan',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Pemimpin Cerdas di Desa Hewan',
                'type' => 'komik',
                'views' => 1,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7]',
                'created_by' => 1,
                'creator' => 'gemini',
                'data' => '{"pages":[{"num":1,"text":"Di terumbu karang yang indah, hidup banyak jenis hewan laut dengan ciri khas masing-masing."},{"num":2,"text":"Adik Ikan Badut tinggal di sela anemon. Ia suka berenang di tempat yang terang dan tenang."},{"num":3,"text":"Di sebelahnya tinggal Adik Ikan Kelinci Laut yang bergerak lambat dan suka bersembunyi di celah gelap."},{"num":4,"text":"Adik Ikan Badut: Kenapa kamu selalu di tempat gelap saja? Ayo berenang ke tempat yang terang dan asyik."},{"num":5,"text":"Adik Ikan Kelinci Laut: Tubuhku tidak tahan sinar matahari yang terik. Tempat gelap membuatku merasa aman."},{"num":6,"text":"Awalnya Adik Ikan Badut merasa aneh. Ia pikir semua harus suka tempat yang sama dengannya."},{"num":7,"text":"Suatu hari ia melihat Adik Ikan Pari yang berenang dekat dasar, dan Adik Ikan Layang yang suka melesat di arus kuat."},{"num":8,"text":"Adik Ikan Badut bertanya pada Bibi Penyu: Mengapa kita semua punya kebiasaan yang berbeda?"},{"num":9,"text":"Bibi Penyu: Itulah keindahan alam. Perbedaan bukan alasan untuk bertengkar, tapi untuk saling melengkapi."},{"num":10,"text":"Adik Ikan Badut mengerti. Ia tidak lagi memaksa temannya mengikuti keinginannya sendiri."},{"num":11,"text":"Ia mulai berkunjung ke tempat tinggal teman-temannya dengan cara yang tidak mengganggu kenyamanan mereka."},{"num":12,"text":"Adik Ikan Kelinci Laut pun merasa dihargai. Ia juga menceritakan hal-hal menarik yang ada di tempat gelap."},{"num":13,"text":"Mereka saling menjaga. Tidak ada yang merasa terganggu, semua merasa nyaman dengan caranya masing-masing."},{"num":14,"text":"Adik Ikan Badut berkata: Ternyata hidup lebih indah kalau kita menghargai cara hidup orang lain."},{"num":15,"text":"Terumbu karang menjadi tempat yang damai. Toleransi membuat semua makhluk bisa hidup berdampingan dengan bahagia."}]}',
                'desc' => 'Di terumbu karang hidup berbagai ikan dengan kebiasaan berbeda. Adik Ikan Badut belajar menghargai perbedaan agar bisa hidup rukun berdampingan.',
                'image' => 'cover.png',
                'moral' => 'Moral cerita ini adalah setiap makhluk memiliki sifat, kebiasaan, dan kebutuhan yang berbeda. Toleransi berarti menghargai perbedaan itu tanpa memaksakan kehendak sendiri. Hidup berdampingan dengan saling menghormati membuat lingkungan menjadi damai dan aman.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["toleransi", "saling_menghargai", "menghormati_perbedaan", "rukun"]',
                'slug' => 'adik-ikan-badut-dan-tetangganya',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Adik Ikan Badut dan Tetangganya',
                'type' => 'komik',
                'views' => 1,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di sebuah kebun, hiduplah Adik Semut yang sangat rajin. Setiap hari ia mengangkut makanan ke sarang."},{"num":2,"text":"Suatu hari, Adik Semut menemukan remah roti yang sangat besar. Ia tidak bisa mengangkatnya sendirian."},{"num":3,"text":"Adik Semut memanggil teman-temannya. Ayo kita angkat bersama-sama!"},{"num":4,"text":"Ratu Semut melihat dari singgasananya. Ia tersenyum bangga melihat semut-semut bekerja sama."},{"num":5,"text":"Bibi Semut: Kita harus kompak! Semua kaki harus melangkah bersamaan."},{"num":6,"text":"Dengan hitungan satu, dua, tiga! Remah roti itu terangkat dan bergerak menuju sarang."},{"num":7,"text":"Ratu Semut: Hebat sekali kalian! Kerja sama membuat pekerjaan berat jadi ringan."},{"num":8,"text":"Semua semut merayakan bersama. Mereka belajar bahwa bersama-sama semua bisa dilakukan."}]}',
                'desc' => 'Adik Semut menemukan makanan besar dan meminta bantuan teman-temannya untuk mengangkatnya bersama.',
                'image' => 'cover.png',
                'moral' => 'Bekerja sama membuat pekerjaan berat menjadi ringan. Kita tidak perlu melakukan semuanya sendirian.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kerja_sama", "gotong_royong", "komunikasi"]',
                'slug' => 'adik-semut-dan-ratu-semut',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Adik Semut dan Ratu Semut',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di sebuah halaman, Adik Kucing sedang berjemur di bawah sinar matahari pagi."},{"num":2,"text":"Tiba-tiba ia mendengar suara kecil. Cip cip cip! Ternyata ada Anak Ayam yang tersesat."},{"num":3,"text":"Anak Ayam: Aku terpisah dari indukku. Aku takut dan tidak tahu jalan pulang."},{"num":4,"text":"Adik Kucing: Jangan takut, aku akan menemanimu. Mari kita cari indukmu bersama."},{"num":5,"text":"Mereka berjalan berdampingan melewati kebun dan sawah. Adik Kucing melindungi Anak Ayam dari bahaya."},{"num":6,"text":"Akhirnya mereka mendengar suara kokokan induk ayam yang sedang mencari anaknya."},{"num":7,"text":"Anak Ayam: Terima kasih, Kucing! Kau teman yang baik meskipun kita berbeda."},{"num":8,"text":"Adik Kucing: Persahabatan tidak melihat bentuk atau jenis. Yang penting hati kita baik."}]}',
                'desc' => 'Adik Kucing menolong Anak Ayam yang tersesat dan mengantarnya kembali ke induknya.',
                'image' => 'cover.png',
                'moral' => 'Persahabatan sejati tidak memandang perbedaan. Kebaikan hati bisa menyatukan siapa saja.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["menolong", "empati", "persahabatan"]',
                'slug' => 'adik-kucing-dan-anak-ayam',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Adik Kucing dan Anak Ayam',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di kota kecil, hiduplah sebuah robot bernama Pahlawan Robot. Ia dibuat untuk membantu manusia."},{"num":2,"text":"Suatu hari, tanah berguncang keras! Gempa bumi mengguncang seluruh kota."},{"num":3,"text":"Banyak rumah yang rusak dan orang-orang ketakutan. Pahlawan Robot segera berlari membantu."},{"num":4,"text":"Kakak Teknisi: Robot, tolong angkat pohon yang tumbang menutup jalan!"},{"num":5,"text":"Pahlawan Robot mengangkat pohon besar itu dengan mudah. Jalan menjadi terbuka kembali."},{"num":6,"text":"Adik Kecil: Tolong! Aku terjebak di bawah reruntuhan! Pahlawan Robot segera menolong."},{"num":7,"text":"Ayah Dokter: Terima kasih, Robot. Kau menyelamatkan banyak nyawa hari ini."},{"num":8,"text":"Pahlawan Robot: Aku dibuat untuk menolong. Membantu sesama adalah tugasku yang paling penting."}]}',
                'desc' => 'Pahlawan Robot membantu menyelamatkan warga kota saat terjadi gempa bumi yang menakutkan.',
                'image' => 'cover.png',
                'moral' => 'Menolong orang yang membutuhkan adalah hal mulia. Setiap orang bisa menjadi pahlawan dengan cara masing-masing.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["menolong", "keberanian", "tanggung_jawab"]',
                'slug' => 'pahlawan-robot-penyelamat',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Pahlawan Robot Penyelamat',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di sebuah keranjang, Adik Jeruk bersama teman-temannya: Apel, Pisang, dan Anggur."},{"num":2,"text":"Adik Jeruk: Kita punya warna dan rasa yang berbeda. Tapi kita semua enak dimakan!"},{"num":3,"text":"Suatu hari, anak-anak membutuhkan jus buah untuk acara di sekolah."},{"num":4,"text":"Bibi Penjual: Kita butuh semua buah untuk membuat jus yang enak dan sehat."},{"num":5,"text":"Adik Jeruk memberikan vitamin C, Apel memberikan manisnya, Pisang memberikan tenaga."},{"num":6,"text":"Anggur menambah warna yang cantik. Semua bercampur menjadi jus yang lezat."},{"num":7,"text":"Anak-anak minum jus itu dengan senang. Badan jadi sehat dan kuat."},{"num":8,"text":"Adik Jeruk: Ternyata kita lebih hebat kalau bersama! Setiap buah punya kelebihan masing-masing."}]}',
                'desc' => 'Adik Jeruk dan teman-teman buahnya bekerja sama membuat jus yang sehat dan enak untuk anak-anak.',
                'image' => 'cover.png',
                'moral' => 'Setiap orang punya kelebihan masing-masing. Bersama-sama kita bisa menghasilkan sesuatu yang lebih baik.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kerja_sama", "menghargai_perbedaan", "kesehatan"]',
                'slug' => 'adik-jeruk-dan-teman-temannya',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Adik Jeruk dan Teman-temannya',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di langit biru, Kakak Elang terbang tinggi dengan gagah. Ia bisa melihat segalanya dari atas."},{"num":2,"text":"Di bawah, Adik Merpati terbang rendah. Ia ingin bisa terbang setinggi Kakak Elang."},{"num":3,"text":"Adik Merpati: Kakak, ajari aku terbang tinggi seperti kamu!"},{"num":4,"text":"Kakak Elang: Aku bisa mengajarimu, tapi kamu juga punya kelebihan yang tidak aku miliki."},{"num":5,"text":"Adik Merpati: Kelebihan apa? Kakak Elang: Kamu bisa membawa surat dan menemukan jalan pulang dari mana saja!"},{"num":6,"text":"Mereka berlatih bersama. Kakak Elang mengajar terbang tinggi, Adik Merpati mengajar navigasi."},{"num":7,"text":"Kakak Elang: Ternyata kita saling melengkapi. Aku jadi tahu jalan pulang lebih cepat."},{"num":8,"text":"Adik Merpati: Setiap burung punya keistimewaan. Belajar dari satu sama lain membuat kita lebih hebat."}]}',
                'desc' => 'Kakak Elang dan Adik Merpati belajar dari kelebihan masing-masing dan saling mengajar.',
                'image' => 'cover.png',
                'moral' => 'Setiap orang punya kelebihan unik. Belajar dari orang lain membuat kita semakin pintar dan lengkap.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["belajar", "saling_menghargai", "kerendahan_hati"]',
                'slug' => 'kakak-elang-dan-adik-merpati',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Kakak Elang dan Adik Merpati',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di hutan pegunungan, Ayah Beruang mengajak Anak Beruang ke sungai untuk pertama kali."},{"num":2,"text":"Anak Beruang: Ayah, airnya dingin! Aku takut masuk ke dalam sungai."},{"num":3,"text":"Ayah Beruang: Jangan takut. Ayah akan mengajarimu cara menangkap ikan yang benar."},{"num":4,"text":"Ayah Beruang menunjukkan caranya. Berdiri diam di air dangkal, tunggu ikan lewat, lalu tangkap cepat."},{"num":5,"text":"Anak Beruang mencoba. Gagal! Ia terpeleset dan jatuh ke air. Tapi ia tertawa."},{"num":6,"text":"Anak Beruang mencoba lagi. Kali ini kakinya lebih mantap. Ia menunggu dengan sabar."},{"num":7,"text":"Akhirnya, Anak Beruang berhasil menangkap ikan pertamanya! Hore!"},{"num":8,"text":"Ayah Beruang: Anakku, latihan dan sabar adalah kunci. Kalau tidak berhasil, coba lagi ya!"}]}',
                'desc' => 'Ayah Beruang mengajarkan Anak Beruang cara menangkap ikan di sungai dengan sabar dan penuh kasih sayang.',
                'image' => 'cover.png',
                'moral' => 'Dengan kesabaran dan latihan, kita bisa menguasai hal baru. Jangan takut gagal, coba lagi!',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kesabaran", "ketekunan", "belajar"]',
                'slug' => 'ayah-beruang-dan-anak-beruang',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Ayah Beruang dan Anak Beruang',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di taman yang indah, Adik Bunga tumbuh dengan cantik. Warnanya merah muda dan harum baunya."},{"num":2,"text":"Setiap hari Adik Bunga menunggu kedatangan Kupu-Kupu yang suka hinggap di kelopaknya."},{"num":3,"text":"Kupu-Kupu: Terima kasih, Bunga. Madumu sangat manis dan membuatku kuat terbang."},{"num":4,"text":"Adik Bunga: Sama-sama, Kupu-Kupu. Kau membantu menyebarkan serbuku ke bunga lain."},{"num":5,"text":"Suatu hari hujan turun sangat deras. Adik Bunga ketakutan akan layu."},{"num":6,"text":"Kupu-Kupu melindungi Adik Bunga dengan sayapnya yang lebar dari tetesan hujan."},{"num":7,"text":"Setelah hujan berhenti, Adik Bunga masih segar dan cantik berkat perlindungan Kupu-Kupu."},{"num":8,"text":"Adik Bunga: Terima kasih sudah melindungiku. Kita memang saling membutuhkan ya!"}]}',
                'desc' => 'Adik Bunga dan Kupu-Kupu saling membantu dan melindungi dalam keadaan senang maupun susah.',
                'image' => 'cover.png',
                'moral' => 'Sahabat sejati selalu ada di saat senang maupun susah. Saling membantu membuat hubungan semakin kuat.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["persahabatan", "saling_membantu", "setia_kawan"]',
                'slug' => 'adik-bunga-dan-kupu-kupu',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Adik Bunga dan Kupu-Kupu',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di padang rumput, Bibi Lebah bekerja keras setiap hari mengunjungi bunga demi bunga."},{"num":2,"text":"Adik Lebah: Bibi, mengapa kita harus bekerja terus? Capek sekali."},{"num":3,"text":"Bibi Lebah: Kita mengumpulkan nektar dari bunga untuk dijadikan madu yang enak."},{"num":4,"text":"Adik Lebah mencoba mengunjungi satu bunga. Nektarnya manis! Tapi hanya sedikit."},{"num":5,"text":"Bibi Lebah: Kita harus mengunjungi ratusan bunga untuk membuat satu botol madu."},{"num":6,"text":"Adik Lebah mengunjungi bunga lagi dan lagi. Ia mulai mengerti arti kerja keras."},{"num":7,"text":"Akhirnya, madu pertama Adik Lebah jadi! Rasanya manis dan legit."},{"num":8,"text":"Bibi Lebah: Hasil kerja keras terasa lebih nikmat. Kita bangga karena usaha sendiri, ya!"}]}',
                'desc' => 'Bibi Lebah mengajarkan Adik Lebah cara membuat madu dengan kerja keras dan ketekunan.',
                'image' => 'cover.png',
                'moral' => 'Hasil kerja keras terasa lebih nikmat dan membanggakan. Jangan malas, terus berusaha!',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kerja_keras", "ketekunan", "disiplin"]',
                'slug' => 'bibi-lebah-dan-madu',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Bibi Lebah dan Madu',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di laut yang biru, Adik Ikan berenang gembira di antara terumbu karang yang indah."},{"num":2,"text":"Adik Ikan: Rumahku cantik sekali! Karang ini tempat bermain dan berlindung."},{"num":3,"text":"Suatu hari, Adik Ikan melihat sampah plastik mengambang dekat terumbu karang."},{"num":4,"text":"Bibi Penyu: Sampah itu berbahaya! Ikan kecil bisa tersangkut dan karang bisa rusak."},{"num":5,"text":"Adik Ikan memanggil semua temannya. Ayo kita dorong sampah ini ke tepi pantai!"},{"num":6,"text":"Mereka bekerja sama mendorong sampah plastik dengan ekor sampai terdampar di pantai."},{"num":7,"text":"Kakek Laut: Bagus sekali kalian! Menjaga rumah sendiri itu sangat penting."},{"num":8,"text":"Adik Ikan: Terumbu karang adalah rumah kita. Kita harus menjaga dan melindunginya selalu!"}]}',
                'desc' => 'Adik Ikan dan teman-temannya membersihkan sampah plastik yang mengancam terumbu karang mereka.',
                'image' => 'cover.png',
                'moral' => 'Menjaga kebersihan lingkungan adalah tanggung jawab kita bersama. Rumah yang bersih membuat semua bahagia.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["menjaga_lingkungan", "kerja_sama", "tanggung_jawab"]',
                'slug' => 'adik-ikan-dan-terumbu-karang',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Adik Ikan dan Terumbu Karang',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di hutan lebat, Kakak Harimau adalah pemangsa yang kuat. Semua hewan takut padanya."},{"num":2,"text":"Suatu hari, Kakak Harimau mendengar suara rintihan. Ternyata Anak Rusa terjebak di lumpur."},{"num":3,"text":"Anak Rusa: Tolong! Aku tidak bisa bergerak! Kakak Harimau mendekat dengan langkah besar."},{"num":4,"text":"Anak Rusa menangis: Jangan makan aku! Aku terjebak dan butuh pertolongan."},{"num":5,"text":"Kakak Harimau berpikir sejenak. Ia melihat ketakutan di mata Anak Rusa."},{"num":6,"text":"Kakak Harimau mengulurkan cakarnya dan menarik Anak Rusa keluar dari lumpur."},{"num":7,"text":"Anak Rusa: Terima kasih, Kakak! Kau menyelamatkan nyawaku meskipun kita berbeda."},{"num":8,"text":"Kakak Harimau: Kadang kebaikan lebih penting dari kekuatan. Menolong membuat hatiku tenang."}]}',
                'desc' => 'Kakak Harimau belajar menunjukkan belas kasihan dengan menolong Anak Rusa yang terjebak lumpur.',
                'image' => 'cover.png',
                'moral' => 'Kebaikan dan belas kasihan lebih berharga dari kekuatan. Menolong orang lain membuat hati tenang.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["belas_kasihan", "kebaikan", "mengelola_emosi"]',
                'slug' => 'kakak-harimau-dan-anak-rusa',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Kakak Harimau dan Anak Rusa',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di dalam tas sekolah, Adik Pensil dan Buku tinggal berdampingan. Mereka teman baik."},{"num":2,"text":"Adik Pensil: Aku bisa menggambar dan menulis! Tanpa aku, Buku kosong saja."},{"num":3,"text":"Buku: Tapi tanpa aku, tulisanmu tidak ada tempatnya. Kita saling membutuhkan."},{"num":4,"text":"Suatu malam, mereka berpetualang keluar dari tas. Di meja belajar, ada banyak hal menarik."},{"num":5,"text":"Adik Pensil menggambar bintang dan bulan di halaman Buku. Cantik sekali!"},{"num":6,"text":"Buku: Wah, gambarmu bagus! Tapi jangan lupa tulis juga ceritanya ya."},{"num":7,"text":"Adik Pensil menulis cerita tentang petualangan mereka berdua. Buku senang sekali."},{"num":8,"text":"Adik Pensil: Ternyata kita lebih hebat kalau bersama. Menulis dan menggambar saling melengkapi!"}]}',
                'desc' => 'Adik Pensil dan Buku berpetualang bersama menciptakan cerita dan gambar yang indah.',
                'image' => 'cover.png',
                'moral' => 'Saling melengkapi membuat hasil kerja lebih baik. Hargai teman yang punya kelebihan berbeda.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kreativitas", "saling_melengkapi", "persahabatan"]',
                'slug' => 'adik-pensil-dan-buku',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Adik Pensil dan Buku',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di tepi sungai, berdiri Ayah Pohon yang besar dan rindang. Akarnya kuat mencengkeram tanah."},{"num":2,"text":"Suatu hari angin kencang datang. Dahan bergoyang keras tapi Ayah Pohon tetap tegak."},{"num":3,"text":"Adik Pohon Muda: Ayah, mengapa angin tidak bisa menjatuhkanmu?"},{"num":4,"text":"Ayah Pohon: Karena akarku dalam dan kuat. Akar adalah keluarga yang saling menguatkan."},{"num":5,"text":"Adik Daun: Kami juga membantu! Daun-daun mengurangi kekuatan angin."},{"num":6,"text":"Akar-Akar kecil berbisik: Kami saling berpegangan di dalam tanah. Itulah kekuatan keluarga."},{"num":7,"text":"Setelah angin reda, semua pohon masih berdiri. Mereka tersenyum bahagia."},{"num":8,"text":"Ayah Pohon: Keluarga yang saling mendukung akan tetap kuat menghadapi badai apa pun."}]}',
                'desc' => 'Ayah Pohon dan keluarganya menghadapi angin kencang dengan kekuatan saling mendukung.',
                'image' => 'cover.png',
                'moral' => 'Keluarga yang saling mendukung akan tetap kuat menghadapi masalah apa pun.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kekeluargaan", "saling_mendukung", "kekuatan"]',
                'slug' => 'ayah-pohon-dan-akar',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Ayah Pohon dan Akar',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di kebun bunga, Adik Kupu-Kupu dulunya adalah seekor ulat yang biasa saja."},{"num":2,"text":"Adik Ulat: Aku jelek dan lambat. Semua orang menghindariku."},{"num":3,"text":"Bibi Bunga: Jangan sedih. Suatu hari kau akan berubah menjadi sesuatu yang indah."},{"num":4,"text":"Adik Ulat rajin makan daun setiap hari. Ia sabar menunggu waktunya tiba."},{"num":5,"text":"Akhirnya Adik Ulat membuat kepompong. Di dalamnya, ia berubah perlahan."},{"num":6,"text":"Setelah beberapa minggu, kepompong terbuka. Keluarlah Adik Kupu-Kupu yang cantik!"},{"num":7,"text":"Semua hewan kagum. Sayapnya berwarna-warni dan indah sekali."},{"num":8,"text":"Adik Kupu-Kupu: Perubahan butuh kesabaran. Jangan menyerah, keindahan akan datang pada waktunya."}]}',
                'desc' => 'Adik Ulat berubah menjadi Kupu-Kupu yang cantik dengan penuh kesabaran dan ketekunan.',
                'image' => 'cover.png',
                'moral' => 'Perubahan besar butuh waktu dan kesabaran. Jangan menyerah, proses akan membawa hasil yang indah.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kesabaran", "ketekunan", "kepercayaan_diri"]',
                'slug' => 'adik-kupu-kupu-dan-ulat',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Adik Kupu-Kupu dan Ulat',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di kebun sayur, Bibi Kelinci punya wortel yang banyak dan segar."},{"num":2,"text":"Bibi Kelinci: Ini wortelku! Aku tidak mau berbagi dengan siapa pun."},{"num":3,"text":"Adik Kucing datang: Bibi, bolehkah aku minta satu wortel? Aku lapar."},{"num":4,"text":"Bibi Kelinci: Tidak! Cari makanmu sendiri! Lalu Adik Kucing pergi dengan sedih."},{"num":5,"text":"Hujan turun deras dan kebun Bibi Kelinci terendam. Semua wortelnya rusak."},{"num":6,"text":"Bibi Kelinci menangis. Ia tidak punya makanan. Teman-temannya datang membantu."},{"num":7,"text":"Adik Kucing membawa ikan untuk Bibi Kelinci. Maafkan aku dulu tidak berbagi, kata Bibi Kelinci."},{"num":8,"text":"Bibi Kelinci: Berbagi itu penting. Kalau kita memberi, orang lain juga akan membantu kita."}]}',
                'desc' => 'Bibi Kelinci belajar pentingnya berbagi setelah mengalami kesulitan dan ditolong oleh teman-temannya.',
                'image' => 'cover.png',
                'moral' => 'Berbagi itu penting. Kalau kita memberi dengan tulus, kebaikan akan kembali pada kita.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berbagi", "keikhlasan", "empati"]',
                'slug' => 'bibi-kelinci-dan-wortel',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Bibi Kelinci dan Wortel',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di bandara, Adik Pesawat bersiap terbang untuk pertama kali ke langit biru."},{"num":2,"text":"Adik Pesawat: Wah, awan-awan itu tinggi sekali. Aku takut nabrak!"},{"num":3,"text":"Kakak Awan: Jangan takut, Pesawat! Kami lembut dan tidak berbahaya."},{"num":4,"text":"Adik Pesawat terbang menembus awan. Ternyata awan itu lembut seperti kapas."},{"num":5,"text":"Dari atas, Adik Pesawat melihat kota, sungai, dan gunung yang sangat indah."},{"num":6,"text":"Adik Pesawat: Luas sekali dunia ini! Aku jadi ingin tahu lebih banyak."},{"num":7,"text":"Kakak Awan: Dunia penuh hal menarik. Terbanglah tinggi dan jelajahi semuanya!"},{"num":8,"text":"Adik Pesawat mendarat dengan senyum. Petualangan di langit membuatnya berani dan penasaran."}]}',
                'desc' => 'Adik Pesawat menjelajahi langit dan menemukan keindahan dunia dari ketinggian.',
                'image' => 'cover.png',
                'moral' => 'Jangan takut mencoba hal baru. Dunia penuh keindahan yang menunggu untuk dijelajahi.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["keberanian", "rasa_ingin_tahu", "petualangan"]',
                'slug' => 'adik-pesawat-dan-awan',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Adik Pesawat dan Awan',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di hutan, Kakak Singa sombong karena meraja paling kuat. Semua hewan takut."},{"num":2,"text":"Suatu hari, Kakak Singa terjebak dalam jaring pemburu. Ia tidak bisa lepas!"},{"num":3,"text":"Adik Mousedeer melihatnya. Kakak Singa meminta tolong padanya."},{"num":4,"text":"Adik Mousedeer: Kau dulu mengejekku karena kecil. Sekarang kau minta tolong padaku?"},{"num":5,"text":"Tapi Adik Mousedeer tetap membantu. Ia menggigit tali jaring dengan giginya yang tajam."},{"num":6,"text":"Tali demi taliputus. Kakak Singa akhirnya bebas dari jaring."},{"num":7,"text":"Kakak Singa: Maafkan aku sudah mengejekmu. Kau kecil tapi sangat pintar dan baik hati."},{"num":8,"text":"Adik Mousedeer: Kekuatan bukan soal besar atau kecil. Kebaikan hati yang membuat kita hebat."}]}',
                'desc' => 'Adik Mousedeer yang kecil tapi cerdas menolong Kakak Singa yang sombong dari jaring pemburu.',
                'image' => 'cover.png',
                'moral' => 'Kecerdasan dan kebaikan hati lebih berharga dari kekuatan. Jangan meremehkan orang lain.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kecerdasan", "kebaikan", "tidak_sombong"]',
                'slug' => 'kakak-singa-dan-mousedeer',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Kakak Singa dan Mousedeer',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di pantai yang indah, Adik Bintang Laut tinggal di antara batu karang dan pasir putih."},{"num":2,"text":"Suatu hari, banyak orang membuang sampah di pantai. Pasir jadi kotor dan berbau."},{"num":3,"text":"Adik Bintang Laut: Pantai ini rumahku. Kalau kotor, aku dan teman-teman tidak bisa hidup."},{"num":4,"text":"Adik Bintang Laut memanggil Kepiting dan Siput. Ayo kita bersihkan pantai!"},{"num":5,"text":"Mereka mengumpulkan sampah kecil-kecil. Tapi sampahnya terlalu banyak."},{"num":6,"text":"Anak-anak yang bermain melihat mereka. Mereka ikut membantu memungut sampah."},{"num":7,"text":"Pantai kembali bersih dan indah. Semua hewan laut senang."},{"num":8,"text":"Adik Bintang Laut: Terima kasih sudah menjaga rumah kita. Pantai ini milik kita bersama!"}]}',
                'desc' => 'Adik Bintang Laut dan teman-temannya membersihkan pantai dari sampah yang mengotori rumah mereka.',
                'image' => 'cover.png',
                'moral' => 'Menjaga kebersihan pantai dan laut adalah tanggung jawab bersama. Alam rumah bagi banyak makhluk.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["menjaga_lingkungan", "kerja_sama", "peduli"]',
                'slug' => 'adik-bintang-laut-dan-pantai',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Adik Bintang Laut dan Pantai',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di hutan Afrika, musim kemarau tiba. Semua sungai mengering dan tidak ada air."},{"num":2,"text":"Ayah Gajah melihat anak-anak hewan kehausan. Ia merasa sedih dan prihatin."},{"num":3,"text":"Ayah Gajah: Aku punya ingatan yang kuat. Aku tahu di mana ada sumber air tersembunyi."},{"num":4,"text":"Dengan langkah besar, Ayah Gajah berjalan jauh melewati padang rumput yang kering."},{"num":5,"text":"Akhirnya ia menemukan sumber air di balik bukit. Airnya jernih dan segar!"},{"num":6,"text":"Ayah Gajah kembali dan memandu semua hewan ke sumber air itu."},{"num":7,"text":"Semua hewan minum dengan gembira. Kelinci, zebra, jerapah, semuanya kebagian."},{"num":8,"text":"Ayah Gajah: Membantu yang membutuhkan adalah kewajiban kita. Berbagi membuat semua selamat."}]}',
                'desc' => 'Ayah Gajah menemukan sumber air tersembunyi dan membaginya dengan semua hewan yang kehausan.',
                'image' => 'cover.png',
                'moral' => 'Membantu dan berbagi dengan yang membutuhkan adalah kewajiban. Kebaikan menyelamatkan banyak orang.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berbagi", "kepemimpinan", "peduli"]',
                'slug' => 'ayah-gajah-dan-air',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Ayah Gajah dan Air',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di kamar anak-anak, Adik Robot terbuat dari kardus bekas yang sudah tidak dipakai."},{"num":2,"text":"Adik Robot: Walaupun aku hanya dari kardus, aku bisa jadi apa saja!"},{"num":3,"text":"Kakak Anak: Aku akan menggambarmu jadi robot penjelajah luar angkasa!"},{"num":4,"text":"Dengan krayon dan cat, Adik Robot berubah jadi robot luar angkasa yang keren."},{"num":5,"text":"Kakak Anak berpura-pura menerbangkan Adik Robot ke planet Mars dan Bulan."},{"num":6,"text":"Adik Robot: Di planet Mars kita ketemu alien yang ramah! Mereka suka bermain."},{"num":7,"text":"Bibi Ibu: Wah, kalian hebat! Dari kardus bekas bisa jadi mainan yang seru."},{"num":8,"text":"Adik Robot: Imajinasi membuat segalanya mungkin. Dari benda sederhana, kita bisa berpetualang!"}]}',
                'desc' => 'Adik Robot dari kardus bekas berpetualang ke luar angkasa bersama Kakak Anak dengan imajinasi.',
                'image' => 'cover.png',
                'moral' => 'Imajinasi membuat segalanya mungkin. Dari benda sederhana, kita bisa menciptakan petualangan luar biasa.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["imajinasi", "kreativitas", "bermain"]',
                'slug' => 'adik-robot-dan-kardus',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Adik Robot dan Kardus',
                'type' => 'komik',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"pages":[{"num":1,"text":"Di sebuah desa, Bibi Kura-Kura punya impian bisa terbang seperti burung."},{"num":2,"text":"Semua hewan menertawakannya. Kura-kura mana bisa terbang!"},{"num":3,"text":"Bibi Kura-Kura: Aku tahu aku lambat. Tapi aku tidak akan menyerah."},{"num":4,"text":"Setiap hari Bibi Kura-Kura berlatih melompat dari bukit kecil. Gagal lagi dan lagi."},{"num":5,"text":"Kakak Burung: Kau memang tidak bisa terbang, tapi kau punya kekuatan lain."},{"num":6,"text":"Dalam lomba lomba desa, Bibi Kura-Kura berjalan pelan tapi tidak pernah berhenti."},{"num":7,"text":"Kelinci dan Kancil kelelahan dan berhenti di tengah jalan. Bibi Kura-Kura terus berjalan."},{"num":8,"text":"Bibi Kura-Kura menang! Lambat tapi pasti mengalahkan cepat tapi mudah menyerah. Ketentuan hati adalah kekuatan!"}]}',
                'desc' => 'Bibi Kura-Kura yang lambat memenangkan lomba dengan ketekunan dan tidak pernah menyerah.',
                'image' => 'cover.png',
                'moral' => 'Ketekunan dan tidak mudah menyerah lebih penting dari kecepatan. Lambat tapi pasti akan menang.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["ketekunan", "tidak_menyerah", "kepercayaan_diri"]',
                'slug' => 'bibi-kura-kura-dan-terbang',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Bibi Kura-Kura dan Terbang',
                'type' => 'komik',
                'views' => 0,
            ],
        ];

        $maxOrder = Activity::max('sort_order') ?? 0;

        Activity::where('type', ActivityType::KOMIK->value)->delete();

        foreach ($samples as $i => $item) {
            Activity::firstOrCreate(
                ['slug' => Str::slug($item['title'])],
                [
                    'type' => 'komik',
                    'title' => $item['title'],
                    'desc' => $item['desc'] ?? null,
                    'image' => $item['image'] ?? null,
                    'moral' => $item['data']['moral'] ?? null,
                    'ages' => $item['ages'] ?? [],
                    'agama' => $item['agama'] ?? [],
                    'skills' => $item['skills'] ?? [],
                    'data' => $item['data'] ?? [],
                    'sort_order' => $maxOrder + $i + 1,
                    'active' => true,
                ]
            );
        }
    }
}
