<?php

namespace Database\Seeders\Activity;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MengenalBendaSeeder extends Seeder
{
    public function run(): void
    {
        $dataTables = [
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"slides":[{"num":1,"nama":"Panci","image":"https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop","digunakan_untuk":"Merebus air dan memasak sup","fungsi":"Wadah besar untuk memasak makanan yang butuh banyak air","spesifikasi":"Terbuat dari logam, ada pegangan di kiri dan kanan, ada tutupnya","fakta":"Taukah kamu? Panci besar bisa dipakai untuk memasak nasi untuk 10 orang!"},{"num":2,"nama":"Sendok","image":"https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=400&h=300&fit=crop","digunakan_untuk":"Mengambil makanan dan mengaduk","fungsi":"Alat untuk makan sup, nasi, dan makanan berkuah","spesifikasi":"Terbuat dari logam atau plastik, ada gagang dan bagian cekung","fakta":"Taukah kamu? Sendok besar dipakai koki untuk memasak, namanya sendok sayur!"},{"num":3,"nama":"Piring","image":"https://images.unsplash.com/photo-1578269174936-2709b6aeb913?w=400&h=300&fit=crop","digunakan_untuk":"Menaruh makanan","fungsi":"Wadah untuk menyajikan makanan di meja","spesifikasi":"Bentuk bulat atau persegi, terbuat dari keramik atau plastik","fakta":"Taukah kamu? Piring pertama terbuat dari tanah liat ribuan tahun lalu!"},{"num":4,"nama":"Gelas","image":"https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400&h=300&fit=crop","digunakan_untuk":"Minum air dan jus","fungsi":"Wadah untuk menampung minuman","spesifikasi":"Terbuat dari kaca atau plastik, ada yang bertangkai ada yang tidak","fakta":"Taukah kamu? Gelas kaca bisa didaur ulang dan dipakai lagi!"},{"num":5,"nama":"Wajan","image":"https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=400&h=300&fit=crop","digunakan_untuk":"Menggoreng dan menumis","fungsi":"Alat masak untuk menggoreng makanan dengan minyak","spesifikasi":"Bentuk lebar dan dangkal, terbuat dari besi atau anti lengket","fakta":"Taukah kamu? Wajan dari Tiongkok sudah dipakai lebih dari 2000 tahun!"},{"num":6,"nama":"Sutil","image":"https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop","digunakan_untuk":"Mengaduk makanan di wajan","fungsi":"Alat untuk membolak-balik makanan saat digoreng","spesifikasi":"Pipih di ujung, gagang panjang supaya tangan tidak kepanasan","fakta":"Taukah kamu? Sutil silikon tidak akan menggores wajan anti lengket!"},{"num":7,"nama":"Pisau","image":"https://images.unsplash.com/photo-1593618998160-e34014e67546?w=400&h=300&fit=crop","digunakan_untuk":"Memotong sayur dan buah","fungsi":"Alat tajam untuk memotong bahan makanan","spesifikasi":"Mata pisau terbuat dari baja, ada gagang kayu atau plastik","fakta":"Taukah kamu? Pisau koki yang baik harus sangat tajam supaya aman!"},{"num":8,"nama":"Talenan","image":"https://images.unsplash.com/photo-1594226801341-41427b4e5c22?w=400&h=300&fit=crop","digunakan_untuk":"Alas memotong bahan makanan","fungsi":"Melindungi meja dari goresan pisau","spesifikasi":"Terbuat dari kayu atau plastik, datar dan cukup lebar","fakta":"Taukah kamu? Talenan kayu lebih aman karena bisa membunuh kuman!"}]}',
                'desc' => 'Anak mengenal nama, fungsi, dan kegunaan alat-alat dapur.',
                'image' => 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
                'moral' => NULL,
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","belajar_hal_baru"]',
                'slug' => 'mengenal-alat-dapur',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Mengenal Alat Dapur',
                'type' => 'mengenal_benda',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"slides":[{"num":1,"nama":"Pensil","image":"https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400&h=300&fit=crop","digunakan_untuk":"Menulis dan menggambar","fungsi":"Alat tulis untuk menulis huruf dan menggambar","spesifikasi":"Terbuat dari kayu dengan isi grafit di dalam, harus diraut","fakta":"Taukah kamu? Pensil bisa menulis sejauh 56 kilometer!"},{"num":2,"nama":"Buku","image":"https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=300&fit=crop","digunakan_untuk":"Menulis dan membaca","fungsi":"Tempat menyimpan tulisan dan gambar","spesifikasi":"Terbuat dari kertas yang dijilid, ada sampul depan dan belakang","fakta":"Taukah kamu? Buku pertama di dunia terbuat dari tanah liat!"},{"num":3,"nama":"Penghapus","image":"https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400&h=300&fit=crop","digunakan_untuk":"Menghapus tulisan pensil","fungsi":"Menghilangkan tulisan yang salah","spesifikasi":"Terbuat dari karet, biasanya berwarna putih atau merah muda","fakta":"Taukah kamu? Penghapus pertama terbuat dari roti!"},{"num":4,"nama":"Penggaris","image":"https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400&h=300&fit=crop","digunakan_untuk":"Mengukur dan membuat garis lurus","fungsi":"Alat untuk mengukur panjang dalam sentimeter","spesifikasi":"Terbuat dari plastik atau kayu, panjang 30 sentimeter","fakta":"Taukah kamu? Penggaris sudah dipakai sejak zaman Mesir kuno!"},{"num":5,"nama":"Spidol","image":"https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400&h=300&fit=crop","digunakan_untuk":"Menulis dan mewarnai","fungsi":"Alat untuk menulis dengan tinta berwarna","spesifikasi":"Ada ujung kecil dan besar, tinta bisa diisi ulang","fakta":"Taukah kamu? Spidol pertama dibuat tahun 1962!"},{"num":6,"nama":"Tas Sekolah","image":"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=300&fit=crop","digunakan_untuk":"Membawa buku dan alat tulis","fungsi":"Wadah untuk membawa perlengkapan sekolah","spesifikasi":"Terbuat dari kain kuat, ada tali punggung dan banyak kantong","fakta":"Taukah kamu? Tas sekolah pertama terbuat dari kulit hewan!"},{"num":7,"nama":"Buku Gambar","image":"https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=300&fit=crop","digunakan_untuk":"Menggambar dan mewarnai","fungsi":"Tempat untuk anak berekspresi dengan gambar","spesifikasi":"Kertas tebal dan putih, ada banyak halaman kosong","fakta":"Taukah kamu? Menggambar bisa membuat otak lebih pintar!"},{"num":8,"nama":"Krayon","image":"https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=300&fit=crop","digunakan_untuk":"Mewarnai gambar","fungsi":"Alat mewarnai untuk anak-anak","spesifikasi":"Terbuat dari lilin, ada banyak warna cerah","fakta":"Taukah kamu? Krayon pertama hanya punya warna hitam!"}]}',
                'desc' => 'Anak mengenal nama, fungsi, dan kegunaan alat-alat sekolah.',
                'image' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=300&fit=crop',
                'moral' => NULL,
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","belajar_hal_baru"]',
                'slug' => 'mengenal-alat-sekolah',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Mengenal Alat Sekolah',
                'type' => 'mengenal_benda',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"slides":[{"num":1,"nama":"Mobil","image":"https://images.unsplash.com/photo-1449965408869-ebd3fee7230f?w=400&h=300&fit=crop","digunakan_untuk":"Pergi jauh bersama keluarga","fungsi":"Kendaraan dengan empat roda untuk membawa penumpang","spesifikasi":"Ada empat roda, mesin, setir, dan kursi yang nyaman","fakta":"Taukah kamu? Mobil pertama dibuat tahun 1886 oleh Karl Benz!"},{"num":2,"nama":"Sepeda","image":"https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=400&h=300&fit=crop","digunakan_untuk":"Berolahraga dan pergi ke tempat dekat","fungsi":"Kendaraan dua roda yang digerakkan dengan kayuh kaki","spesifikasi":"Dua roda, pedal, setir, dan rantai penggerak","fakta":"Taukah kamu? Sepeda pertama tidak punya pedal, harus didorong pakai kaki!"},{"num":3,"nama":"Motor","image":"https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=400&h=300&fit=crop","digunakan_untuk":"Pergi cepat ke tempat yang agak jauh","fungsi":"Kendaraan dua roda bermesin","spesifikasi":"Dua roda, mesin bensin, ada helm untuk pengemudi","fakta":"Taukah kamu? Motor pertama dibuat dari rangka sepeda yang dipasangi mesin!"},{"num":4,"nama":"Bus","image":"https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=400&h=300&fit=crop","digunakan_untuk":"Membawa banyak orang sekaligus","fungsi":"Kendaraan besar untuk angkutan umum","spesifikasi":"Sangat panjang, punya banyak kursi, ada pintu geser","fakta":"Taukah kamu? Bus terpanjang di dunia bisa muat 300 orang!"},{"num":5,"nama":"Kereta","image":"https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=400&h=300&fit=crop","digunakan_untuk":"Pergi antar kota dengan cepat","fungsi":"Kendaraan yang jalan di atas rel","spesifikasi":"Berjalan di rel besi, bisa sangat panjang, ada lokomotif","fakta":"Taukah kamu? Kereta cepat di Jepang bisa berjalan 320 km per jam!"},{"num":6,"nama":"Kapal","image":"https://images.unsplash.com/photo-1494412574643-ff11b0a5eb19?w=400&h=300&fit=crop","digunakan_untuk":"Berlayar di laut dan sungai","fungsi":"Kendaraan yang berjalan di atas air","spesifikasi":"Terapung di air, ada lambung yang kedap air, ada mesin atau layar","fakta":"Taukah kamu? Kapal tanker terbesar di dunia panjangnya 400 meter!"},{"num":7,"nama":"Pesawat","image":"https://images.unsplash.com/photo-1436491865332-7a61a109db05?w=400&h=300&fit=crop","digunakan_untuk":"Terbang ke tempat yang sangat jauh","fungsi":"Kendaraan yang terbang di langit","spesifikasi":"Ada sayap, mesin jet, roda yang bisa masuk, dan badan pesawat","fakta":"Taukah kamu? Pesawat terbesar di dunia bisa muat 800 penumpang!"},{"num":8,"nama":"Becak","image":"https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=400&h=300&fit=crop","digunakan_untuk":"Jalan-jalan dekat di kota","fungsi":"Kendaraan roda tiga yang dikayuh manusia","spesifikasi":"Tiga roda, ada tempat duduk penumpang, dikayuh pakai kaki","fakta":"Taukah kamu? Becak sudah ada di Indonesia sejak tahun 1930-an!"}]}',
                'desc' => 'Anak mengenal nama, fungsi, dan spesifikasi kendaraan.',
                'image' => 'https://images.unsplash.com/photo-1449965408869-ebd3fee7230f?w=400&h=300&fit=crop',
                'moral' => NULL,
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","belajar_hal_baru"]',
                'slug' => 'mengenal-kendaraan',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Mengenal Kendaraan',
                'type' => 'mengenal_benda',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"slides":[{"num":1,"nama":"Pisang","image":"https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=300&fit=crop","digunakan_untuk":"Dimakan langsung atau dibuat jus","fungsi":"Buah yang memberi energi dan vitamin","spesifikasi":"Kulit kuning, daging putih lembut, rasanya manis","fakta":"Taukah kamu? Pisang tumbuh terbalik, ujungnya mengarah ke bawah!"},{"num":2,"nama":"Apel","image":"https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&h=300&fit=crop","digunakan_untuk":"Dimakan segar atau dibuat jus","fungsi":"Buah yang kaya vitamin C dan serat","spesifikasi":"Bentuk bulat, kulit merah atau hijau, daging renyah","fakta":"Taukah kamu? Ada lebih dari 7500 jenis apel di seluruh dunia!"},{"num":3,"nama":"Jeruk","image":"https://images.unsplash.com/photo-1547514701-42782101795e?w=400&h=300&fit=crop","digunakan_untuk":"Dimakan atau dibuat jus","fungsi":"Buah yang sangat kaya vitamin C","spesifikasi":"Kulit oranye tebal, ada potongan-potongan di dalam","fakta":"Taukah kamu? Jeruk pertama tumbuh di Asia Tenggara!"},{"num":4,"nama":"Semangka","image":"https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=300&fit=crop","digunakan_untuk":"Dimakan saat cuaca panas","fungsi":"Buah yang banyak airnya, menyegarkan tubuh","spesifikasi":"Kulit hijau, daging merah, ada biji hitam di dalam","fakta":"Taukah kamu? Semangka terbesar di dunia beratnya 159 kg!"},{"num":5,"nama":"Anggur","image":"https://images.unsplash.com/photo-1596363505837-c550db124924?w=400&h=300&fit=crop","digunakan_untuk":"Dimakan segar atau dibuat selai","fungsi":"Buah kecil yang manis dan kaya antioksidan","spesifikasi":"Bulat kecil, tumbuh bergerombol, warna ungu atau hijau","fakta":"Taukah kamu? Anggur sudah ditanam manusia sejak 8000 tahun lalu!"},{"num":6,"nama":"Mangga","image":"https://images.unsplash.com/photo-1553279768-865429fa017d?w=400&h=300&fit=crop","digunakan_untuk":"Dimakan segar atau dibuat rujak","fungsi":"Buah tropis yang kaya vitamin A","spesifikasi":"Kulit hijau atau kuning, daging oranye, ada biji besar","fakta":"Taukah kamu? Mangga adalah buah yang paling banyak dimakan di dunia!"},{"num":7,"nama":"Pepaya","image":"https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=400&h=300&fit=crop","digunakan_untuk":"Dimakan segar untuk kesehatan perut","fungsi":"Buah yang baik untuk pencernaan","spesifikasi":"Kulit hijau atau kuning, daging oranye, ada biji hitam","fakta":"Taukah kamu? Pepaya bisa tumbuh sampai tinggi 10 meter!"},{"num":8,"nama":"Stroberi","image":"https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&h=300&fit=crop","digunakan_untuk":"Dimakan atau dibuat selai","fungsi":"Buah kecil yang kaya vitamin C","spesifikasi":"Merah, ada biji kecil di permukaan, rasanya manis asam","fakta":"Taukah kamu? Stroberi adalah satu-satunya buah yang bijinya di luar!"}]}',
                'desc' => 'Anak mengenal nama, fungsi, dan keunikan buah-buahan.',
                'image' => 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=400&h=300&fit=crop',
                'moral' => NULL,
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","belajar_hal_baru"]',
                'slug' => 'mengenal-buah-buahan',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Mengenal Buah-buahan',
                'type' => 'mengenal_benda',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"slides":[{"num":1,"nama":"Baju","image":"https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=400&h=300&fit=crop","digunakan_untuk":"Melindungi badan atas","fungsi":"Pakaian untuk menutupi tubuh bagian atas","spesifikasi":"Ada lengan, kancing atau resleting, terbuat dari kain","fakta":"Taukah kamu? Baju pertama di dunia terbuat dari kulit hewan!"},{"num":2,"nama":"Celana","image":"https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&h=300&fit=crop","digunakan_untuk":"Melindungi badan bawah","fungsi":"Pakaian untuk menutupi tubuh bagian bawah","spesifikasi":"Ada dua lubang kaki, ada pinggang yang elastis","fakta":"Taukah kamu? Celana pertama dipakai oleh penunggang kuda!"},{"num":3,"nama":"Sepatu","image":"https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop","digunakan_untuk":"Melindungi kaki","fungsi":"Alas kaki supaya kaki tidak terluka","spesifikasi":"Ada sol yang kuat, tali atau velcro, terbuat dari kulit atau kain","fakta":"Taukah kamu? Sepatu tertua di dunia berumur 5500 tahun!"},{"num":4,"nama":"Topi","image":"https://images.unsplash.com/photo-1521369909029-2afed882baee?w=400&h=300&fit=crop","digunakan_untuk":"Melindungi kepala dari panas","fungsi":"Penutup kepala supaya tidak kepanasan","spesifikasi":"Bentuk bulat, ada pinggiran, terbuat dari kain atau jerami","fakta":"Taukah kamu? Topi pertama dibuat untuk melindungi dari hujan!"},{"num":5,"nama":"Kaus Kaki","image":"https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=400&h=300&fit=crop","digunakan_untuk":"Melindungi kaki dari dingin","fungsi":"Pakaian kaki supaya kaki tetap hangat","spesifikasi":"Terbuat dari kain lembut, elastis, ada yang panjang dan pendek","fakta":"Taukah kamu? Kaus kaki pertama terbuat dari kulit hewan!"},{"num":6,"nama":"Jaket","image":"https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=300&fit=crop","digunakan_untuk":"Menghangatkan badan","fungsi":"Pakaian luar yang tebal untuk cuaca dingin","spesifikasi":"Tebal, ada resleting atau kancing, ada kantong","fakta":"Taukah kamu? Jaket bomber pertama dipakai oleh pilot pesawat!"},{"num":7,"nama":"Syal","image":"https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=300&fit=crop","digunakan_untuk":"Menghangatkan leher","fungsi":"Kain panjang untuk melilit leher","spesifikasi":"Terbuat dari wol atau kain lembut, panjang dan sempit","fakta":"Taukah kamu? Syal pertama dipakai oleh tentara Romawi kuno!"},{"num":8,"nama":"Sarung Tangan","image":"https://images.unsplash.com/photo-1531928351158-2f736098e091?w=400&h=300&fit=crop","digunakan_untuk":"Melindungi tangan","fungsi":"Penutup tangan supaya tangan tetap hangat","spesifikasi":"Ada lima lubang jari, terbuat dari kain atau kulit","fakta":"Taukah kamu? Sarung tangan pertama dipakai oleh raja dan ratu!"}]}',
                'desc' => 'Anak mengenal nama, fungsi, dan kegunaan pakaian.',
                'image' => 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=400&h=300&fit=crop',
                'moral' => NULL,
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","belajar_hal_baru"]',
                'slug' => 'mengenal-pakaian',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Mengenal Pakaian',
                'type' => 'mengenal_benda',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"slides":[{"num":1,"nama":"Wortel","image":"https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=300&fit=crop","digunakan_untuk":"Dimakan mentah atau dimasak","fungsi":"Sayuran yang baik untuk kesehatan mata","spesifikasi":"Bentuk panjang, warna oranye, rasanya manis renyah","fakta":"Taukah kamu? Wortel pertama warnanya ungu, bukan oranye!"},{"num":2,"nama":"Bayam","image":"https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=300&fit=crop","digunakan_untuk":"Dimasak sup atau ditumis","fungsi":"Sayuran hijau yang membuat tubuh kuat","spesifikasi":"Daun hijau lebar, batangnya tipis","fakta":"Taukah kamu? Bayam punya zat besi yang sangat banyak!"},{"num":3,"nama":"Tomat","image":"https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&h=300&fit=crop","digunakan_untuk":"Dimasak atau dibuat jus","fungsi":"Sayuran yang kaya vitamin C dan antioksidan","spesifikasi:"Bentuk bulat, warna merah, rasanya sedikit asam","fakta":"Taukah kamu? Tomat sebenarnya adalah buah, bukan sayuran!"},{"num":4,"nama":"Kentang","image":"https://images.unsplash.com/photo-1518977676601-b53f82berubah6?w=400&h=300&fit=crop","digunakan_untuk":"Digoreng, direbus, atau dibuat pure","fungsi":"Sayuran yang memberi energi dan karbohidrat","spesifikasi:"Bentuk bulat lonjong, kulit cokelat, daging putih","fakta":"Taukah kamu? Kentang pertama ditanam di Peru 8000 tahun lalu!"},{"num":5,"nama":"Jagung","image":"https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&h=300&fit=crop","digunakan_untuk":"Dibakar, direbus, atau dibuat popcorn","fungsi":"Sayuran yang kaya serat dan karbohidrat","spesifikasi:"Bentuk lonjong, ada biji kuning berjajar rapi","fakta":"Taukah kamu? Jagung bisa tumbuh sampai tinggi 7 meter!"},{"num":6,"nama":"Timun","image":"https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400&h=300&fit=crop","digunakan_untuk":"Dimakan mentah atau dibuat lalapan","fungsi":"Sayuran yang menyegarkan dan banyak airnya","spesifikasi:"Bentuk lonjong, kulit hijau, daging hijau muda","fakta":"Taukah kamu? Timun bisa membuat wajah segar dan cerah!"},{"num":7,"nama":"Kubis","image":"https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=400&h=300&fit=crop","digunakan_untuk":"Dibuat salad atau sup","fungsi":"Sayuran yang kaya vitamin K dan serat","spesifikasi:"Bentuk bulat, daun berlapis-lapis, hijau muda di dalam","fakta":"Taukah kamu? Kubis punya banyak air, 92% kandungannya adalah air!"},{"num":8,"nama":"Buncis","image":"https://images.unsplash.com/photo-1563746924237-f0e6ae4d2db3?w=400&h=300&fit=crop","digunakan_untuk":"Ditumis atau dimasak sup","fungsi":"Sayuran yang kaya protein nabati","spesifikasi:"Bentuk panjang gepeng, warna hijau, ada biji kecil di dalam","fakta":"Taukah kamu? Buncis bisa tumbuh sampai panjang 20 sentimeter!"}]}',
                'desc' => 'Anak mengenal nama, fungsi, dan keunikan sayuran.',
                'image' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=300&fit=crop',
                'moral' => NULL,
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","belajar_hal_baru"]',
                'slug' => 'mengenal-sayuran',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Mengenal Sayuran',
                'type' => 'mengenal_benda',
                'views' => 0,
            ],
        ];

        DB::table("activities")->insertOrIgnore($dataTables);
    }
}
