<?php

namespace Database\Seeders\Activity;

use App\ActivityType;
use App\Models\Activity;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class MusikGerakSeeder extends Seeder
{
    public function run(): void
    {
        $dataTables = [
            // [
            //     'active' => 1,
            //     'addon_id' => NULL,
            //     'agama' => '"[\\"islam\\"]"',
            //     'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
            //     'created_by' => 1,
            //     'creator' => NULL,
            //     'data' => '{"audio_url":"https:\\/\\/audius.co\\/embed\\/track\\/tonijambo\\/berwudhu?flavor=compact","lyrics":"\\ud83c\\udf88 Cuci dua tangan,\\nlalu kumurlah,\\nbersihkan hidung,\\nlalu mukamu,\\ncuci tangan kanan,\\ncuci tangan kiri,\\nbasuhkan rambut, telinga,\\njuga kaki","moves":["Cuci dua tangan","Masukan air ke hidung","Basuh muka dengan air","Basuh tangan kanan","Basuh tangan kiri","Basuh rambut dan telinga","Basuh kaki"],"moral":"Lagu ini mengajarkan anak berwudhu."}',
            //     'desc' => 'Lagu anak berwudhu.',
            //     'image' => NULL,
            //     'moral' => 'Lagu ini mengajarkan anak berwudhu.',
            //     'notes' => NULL,
            //     'plans' => NULL,
            //     'prompt' => NULL,
            //     'skills' => '["berpikir_kreatif","rutin_belajar"]',
            //     'slug' => Str::slug('Lagu Berwudhu'),
            //     'sort_order' => 1,
            //     'status' => 'pending',
            //     'title' => 'Lagu Berwudhu',
            //     'type' => 'musik_gerak',
            //     'views' => 0,
            // ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"audio_url":"https:\\/\\/w.soundcloud.com\\/player\\/?url=https%3A\\/\\/api.soundcloud.com\\/tracks\\/soundcloud%253Atracks%253A346703008&color=%23ff5500&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false","moves":["Dengarkan musik sambil bermain","Bertepuk tangan mengikuti irama","Bernyanyi bersama lagu yang dikenal","Menari bebas sesuai nada"],"moral":"Lagu anak Indonesia mengajarkan nilai-nilai baik dengan cara yang menyenangkan."}',
                'desc' => 'Kumpulan lagu anak Indonesia selama 60 menit untuk menemani belajar dan bermain.',
                'image' => NULL,
                'moral' => 'Lagu anak Indonesia mengajarkan nilai-nilai baik dengan cara yang menyenangkan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","rutin_belajar"]',
                'slug' => Str::slug('Lagu Anak Indonesia 60 Menit'),
                'sort_order' => 2,
                'status' => 'pending',
                'title' => 'Lagu Anak Indonesia 60 Menit',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"audio_url":"https:\\/\\/www.youtube.com\\/embed\\/xLGiR59fD2k","moves":["Dengarkan musik sambil bermain","Bertepuk tangan mengikuti irama","Bernyanyi bersama lagu yang dikenal","Menari bebas sesuai nada"],"moral":"Lagu anak Indonesia mengajarkan nilai-nilai baik dengan cara yang menyenangkan."}',
                'desc' => 'Belajar Huruf Vokal AIUEO.',
                'image' => NULL,
                'moral' => 'Lagu anak Indonesia mengajarkan nilai-nilai baik dengan cara yang menyenangkan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","rutin_belajar"]',
                'slug' => Str::slug('Belajar Huruf Vokal AIUEO'),
                'sort_order' => 3,
                'status' => 'pending',
                'title' => 'Belajar Huruf Vokal AIUEO',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"audio_url":"https:\\/\\/www.youtube.com\\/embed\\/n5l5Vzm8B-0","moves":["Dengarkan musik sambil bermain","Bertepuk tangan mengikuti irama","Bernyanyi bersama lagu yang dikenal","Menari bebas sesuai nada"],"moral":"Lagu anak Indonesia mengajarkan nilai-nilai baik dengan cara yang menyenangkan."}',
                'desc' => 'Belajar Huruf ABCD.',
                'image' => NULL,
                'moral' => 'Lagu anak Indonesia mengajarkan nilai-nilai baik dengan cara yang menyenangkan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","rutin_belajar"]',
                'slug' => Str::slug('Belajar Huruf ABCD'),
                'sort_order' => 3,
                'status' => 'pending',
                'title' => 'Belajar Huruf ABCD',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"audio_url":"https:\\/\\/www.youtube.com\\/embed\\/OSFOmU38jZ4","moves":["Dengarkan musik sambil bermain","Bertepuk tangan mengikuti irama","Bernyanyi bersama lagu yang dikenal","Menari bebas sesuai nada"],"moral":"Lagu anak Indonesia mengajarkan nilai-nilai baik dengan cara yang menyenangkan."}',
                'desc' => 'Belajar Berwudhu.',
                'image' => NULL,
                'moral' => 'Lagu anak Indonesia mengajarkan nilai-nilai baik dengan cara yang menyenangkan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","rutin_belajar"]',
                'slug' => Str::slug('Belajar Berwudhu'),
                'sort_order' => 3,
                'status' => 'pending',
                'title' => 'Belajar Berwudhu',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Cuci tangan pakai sabun\\nGosok-gosok bersihkan\\nJari depan jari belakang\\nBersih dan wangi tangan kita","moves":["Pegang tangan di depan","Gosok tangan kanan dan kiri","Buka jari dan gosok sela-sela","Kibas-kibas tangan dan cium"],"moral":"Mencuci tangan dengan sabun bisa mencegah kuman."}',
                'desc' => 'Lagu cuci tangan sambil bergerak seru.',
                'image' => NULL,
                'moral' => 'Mencuci tangan dengan sabun bisa mencegah kuman.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kesehatan","rutin_belajar"]',
                'slug' => Str::slug('Lagu Cuci Tangan'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Cuci Tangan',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Satu dua tiga empat lima\\nEnam tujuh delapan sembilan sepuluh\\nAyo kita berhitung bersama\\nAngka-angka itu menyenangkan","moves":["Tunjuk jari satu sampai lima","Tepuk tangan enam sampai sepuluh","Lompat-lompat hitung bersama","Putar badan dan hitung lagi"],"moral":"Berhitung jadi mudah dan seru dengan lagu."}',
                'desc' => 'Lagu berhitung 1-10 dengan gerakan jari.',
                'image' => NULL,
                'moral' => 'Berhitung jadi mudah dan seru dengan lagu.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["matematika","berpikir_logis"]',
                'slug' => Str::slug('Lagu Berhitung 1-10'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Berhitung 1-10',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Sayur-sayuran enak dimakan\\nBayam kangkung dan wortel\\nBrokoli hijau bikin kuat\\nAyo makan sayur setiap hari","moves":["Pegang tangan seperti memetik sayur","Gerakkan tangan seperti mengaduk masakan","Pura-pura makan sayur","Tepuk perut dan tersenyum"],"moral":"Makan sayur membuat tubuh sehat dan kuat."}',
                'desc' => 'Lagu tentang sayur-sayuran dengan gerakan lucu.',
                'image' => NULL,
                'moral' => 'Makan sayur membuat tubuh sehat dan kuat.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kesehatan","mengenal_sayuran"]',
                'slug' => Str::slug('Lagu Sayur-Sayuran'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Sayur-Sayuran',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Buah-buahan segar dan manis\\nPisang jeruk dan mangga\\nSemangka merah banyak air\\nAyo makan buah setiap hari","moves":["Pura-pura memetik buah dari pohon","Pura-pura mengupas buah","Pura-pura makan buah","Tepuk perut dan bilang enak"],"moral":"Makan buah membuat tubuh sehat dan segar."}',
                'desc' => 'Lagu buah-buahan dengan gerakan memetik dan makan.',
                'image' => NULL,
                'moral' => 'Makan buah membuat tubuh sehat dan segar.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kesehatan","mengenal_buah"]',
                'slug' => Str::slug('Lagu Buah-Buahan'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Buah-Buahan',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Hewan-hewan lucu dan imut\\nKucing anjing dan kelinci\\nAyam berkokok di pagi hari\\nAyo sayang semua hewan","moves":["Pura-pura jadi kucing dengan tangan di wajah","Pura-pura jadi anjing menggonggong","Pura-pura jadi kelinci melompat","Pura-pura jadi ayam berkokok"],"moral":"Mengenal dan menyayangi semua hewan."}',
                'desc' => 'Lagu hewan-hewan dengan gerakan meniru hewan.',
                'image' => NULL,
                'moral' => 'Mengenal dan menyayangi semua hewan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_hewan","berpikir_kreatif"]',
                'slug' => Str::slug('Lagu Hewan-Hewan'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Hewan-Hewan',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Merah jingga kuning hijau\\nBiru nila dan ungu\\nTujuh warna pelangi indah\\nCantik di langit setelah hujan","moves":["Angkat tangan ke atas seperti lengkungan","Gerakkan tangan dari kiri ke kanan","Putar badan seperti pelangi","Tepuk tangan tujuh kali"],"moral":"Anak belajar mengenal tujuh warna pelangi."}',
                'desc' => 'Lagu warna pelangi dengan gerakan tangan.',
                'image' => NULL,
                'moral' => 'Anak belajar mengenal tujuh warna pelangi.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_warna","berpikir_kreatif"]',
                'slug' => Str::slug('Lagu Warna Pelangi'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Warna Pelangi',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Keluargaku sayang semua\\nPapa Mama dan Kakak\\nAdik kecil yang lucu\\nKita saling menyayangi","moves":["Peluk diri sendiri","Tunjuk ke Papa dan Mama","Tunjuk ke Kakak dan Adik","Peluk semua keluarga"],"moral":"Anak belajar menyayangi anggota keluarga."}',
                'desc' => 'Lagu keluarga dengan gerakan pelukan hangat.',
                'image' => NULL,
                'moral' => 'Anak belajar menyayangi anggota keluarga.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["sayang_keluarga","komunikasi"]',
                'slug' => Str::slug('Lagu Keluargaku'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Keluargaku',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Badan sehat kuat dan bugar\\nOlahraga setiap hari\\nSenam pagi lari-lari\\nTubuh jadi sehat dan kuat","moves":["Angkat tangan ke atas dan turunkan","Lari di tempat","Lompat-lompat kecil","Regangkan tangan ke samping"],"moral":"Olahraga teratur membuat tubuh sehat."}',
                'desc' => 'Lagu olahraga dengan gerakan senam sederhana.',
                'image' => NULL,
                'moral' => 'Olahraga teratur membuat tubuh sehat.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kesehatan","olahraga"]',
                'slug' => Str::slug('Lagu Badan Sehat'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Badan Sehat',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Cuaca hari ini bagaimana\\nCerah hujan atau berawan\\nPakai payung kalau hujan\\nPakai topi kalau cerah","moves":["Lihat ke atas seperti mengamati langit","Buka payung bayangan","Pakai topi bayangan","Tepuk tangan dan lompat"],"moral":"Anak belajar mengenal cuaca di sekitar."}',
                'desc' => 'Lagu cuaca dengan gerakan mengamati langit.',
                'image' => NULL,
                'moral' => 'Anak belajar mengenal cuaca di sekitar.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_cuaca","pengamatan"]',
                'slug' => Str::slug('Lagu Cuaca'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Cuaca',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Transportasi banyak jenisnya\\nMobil motor dan sepeda\\nKapal terbang dan kereta\\nAyo naik transportasi aman","moves":["Pegang stir mobil bayangan","Kayuh sepeda di tempat","Bentangkan tangan seperti pesawat","Duduk dan goyang seperti naik kereta"],"moral":"Anak belajar mengenal alat transportasi."}',
                'desc' => 'Lagu transportasi dengan gerakan meniru kendaraan.',
                'image' => NULL,
                'moral' => 'Anak belajar mengenal alat transportasi.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_benda","berpikir_kreatif"]',
                'slug' => Str::slug('Lagu Transportasi'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Transportasi',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Anak rajin belajar terus\\nPR selesai tanpa menunda\\nBuku dibaca setiap hari\\nRajin itu bikin pintar","moves":["Pura-pura membaca buku","Tulis di udara","Tunjuk ke kepala dan tersenyum","Tepuk tangan semangat"],"moral":"Rajin belajar membuat anak pintar dan berprestasi."}',
                'desc' => 'Lagu anak rajin dengan gerakan membaca dan menulis.',
                'image' => NULL,
                'moral' => 'Rajin belajar membuat anak pintar dan berprestasi.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["rajin","literasi"]',
                'slug' => Str::slug('Lagu Anak Rajin'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Anak Rajin',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Sopan santun itu penting\\nBilang tolong dan terima kasih\\nPermisi saat lewat orang\\nSopan itu bikin senang","moves":["Anggukkan kepala saat bilang terima kasih","Tunjuk ke mulut saat bilang tolong","Mundur sedikit saat bilang permisi","Tersenyum dan membungkuk"],"moral":"Sopan santun membuat semua orang senang."}',
                'desc' => 'Lagu sopan santun dengan gerakan tata krama.',
                'image' => NULL,
                'moral' => 'Sopan santun membuat semua orang senang.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["sopan","tata_krama"]',
                'slug' => Str::slug('Lagu Sopan Santun'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Sopan Santun',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Sahabatku baik hati\\nBermain bersama setiap hari\\nBerbagi mainan dan cerita\\nSahabat itu saling menyayangi","moves":["Pegang tangan teman di samping","Berputar bersama teman","Bertepuk tangan berdua","Peluk teman di samping"],"moral":"Persahabatan yang baik saling menghargai."}',
                'desc' => 'Lagu sahabat dengan gerakan bermain bersama.',
                'image' => NULL,
                'moral' => 'Persahabatan yang baik saling menghargai.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["persahabatan","komunikasi"]',
                'slug' => Str::slug('Lagu Sahabat'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Sahabat',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Pagi hari matahari terbit\\nBangun tidur langsung mandi\\nSarapan dan pakai baju\\nSiap sekolah dengan semangat","moves":["Regangkan tangan ke atas seperti matahari","Pura-pura mandi","Pura-pura makan","Lompat semangat"],"moral":"Bangun pagi dan beraktivitas itu menyehatkan."}',
                'desc' => 'Lagu pagi hari dengan gerakan rutinitas pagi.',
                'image' => NULL,
                'moral' => 'Bangun pagi dan beraktivitas itu menyehatkan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["rutin_belajar","disiplin"]',
                'slug' => Str::slug('Lagu Pagi Hari'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Pagi Hari',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Malam hari bintang berkelip\\nBulan sabit di langit gelap\\nTidur nyenyak mimpi indah\\nBesok pagi bangun segar","moves":["Tunjuk ke atas seperti melihat bintang","Gerakkan tangan seperti bulan sabit","Tidur di lantai dengan tangan di pipi","Bangun dan regangkan tangan"],"moral":"Tidur tepat waktu membuat tubuh sehat."}',
                'desc' => 'Lagu malam hari dengan gerakan tidur dan bangun.',
                'image' => NULL,
                'moral' => 'Tidur tepat waktu membuat tubuh sehat.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["tidur_teratur","kesehatan"]',
                'slug' => Str::slug('Lagu Malam Hari'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Malam Hari',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Hujan turun rintik-rintik\\nAir jatuh dari langit\\nPakai payung dan sepatu\\nMain air itu seru","moves":["Gerakkan jari seperti air hujan jatuh","Buka payung bayangan","Lompat-lompat genangan bayangan","Tepuk tangan seperti hujan"],"moral":"Hujan itu berkah dari alam."}',
                'desc' => 'Lagu hujan turun dengan gerakan air jatuh.',
                'image' => NULL,
                'moral' => 'Hujan itu berkah dari alam.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_alam","berpikir_kreatif"]',
                'slug' => Str::slug('Lagu Hujan Turun'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Hujan Turun',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Bintang kecil di langit biru\\nBanyak sekali bersinar terang\\nBintang kecil teman malam\\nMembuat langit jadi indah","moves":["Tunjuk ke atas dan gerakkan jari","Kedip-kedip tangan seperti bintang","Putar badan pelan-pelan","Duduk dan lihat ke atas"],"moral":"Mengagumi keindahan langit malam."}',
                'desc' => 'Lagu bintang kecil dengan gerakan tangan.',
                'image' => NULL,
                'moral' => 'Mengagumi keindahan langit malam.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_alam","berimajinasi"]',
                'slug' => Str::slug('Lagu Bintang Kecil'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Bintang Kecil',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Naik kereta api\\nTut tut tut\\nSiapa hendak turun\\nDi stasiun berikut","moves":["Duduk dan goyang seperti naik kereta","Pegang gagang bayangan","Lihat ke kiri dan ke kanan","Bangun dan berjalan seperti turun kereta"],"moral":"Naik kereta itu seru dan menyenangkan."}',
                'desc' => 'Lagu naik kereta dengan gerakan duduk dan berjalan.',
                'image' => NULL,
                'moral' => 'Naik kereta itu seru dan menyenangkan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_benda","berpikir_kreatif"]',
                'slug' => Str::slug('Lagu Naik Kereta'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Naik Kereta',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Berkebun di halaman\\nTanam bunga dan sayur\\nSiram air setiap hari\\nTanaman tumbuh subur","moves":["Pura-pura menggali tanah","Pura-pura menanam benih","Pura-pura menyiram air","Tunjuk tanaman dan tersenyum"],"moral":"Berkebun mengajarkan tanggung jawab dan sabar."}',
                'desc' => 'Lagu berkebun dengan gerakan menanam dan menyiram.',
                'image' => NULL,
                'moral' => 'Berkebun mengajarkan tanggung jawab dan sabar.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["tanggung_jawab","mengenal_alam"]',
                'slug' => Str::slug('Lagu Berkebun'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Berkebun',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3,4,5,6,7,8,9,10,11]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"audio_url":"","lyrics":"Mandi pagi pakai sabun\\nBasuh badan dari kepala\\nSampai ujung kaki bersih\\nBadan wangi dan segar","moves":["Pura-pura membasuh rambut","Pura-pura menggosok badan","Pura-pura membasuh kaki","Kibas-kibas badan dan tersenyum"],"moral":"Mandi pagi membuat badan bersih dan segar."}',
                'desc' => 'Lagu mandi pagi dengan gerakan membasuh badan.',
                'image' => NULL,
                'moral' => 'Mandi pagi membuat badan bersih dan segar.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kesehatan","kebersihan"]',
                'slug' => Str::slug('Lagu Mandi Pagi'),
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lagu Mandi Pagi',
                'type' => 'musik_gerak',
                'views' => 0,
            ],
        ];

        Activity::where('type', ActivityType::MUSIK_GERAK->value)->delete();
        DB::table("activities")->insertOrIgnore($dataTables);
    }
}
