<?php

namespace Database\Seeders\Activity;

use App\ActivityType;
use App\Models\Activity;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OutdoorSeeder extends Seeder
{
    public function run(): void
    {
        $dataTables = [
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Yuk, berbaring di rumput dan tatap langit biru yang luas!"},{"num":2,"text":"Coba perhatikan awan-awan itu. Adakah yang mirip bentuk hewan, kue, atau benda lainnya? Sebutkan, ya!"},{"num":3,"text":"Sekarang, coba hitung ada berapa banyak awan unik yang berhasil kamu temukan?"}]}',
                'desc' => 'Anak mengamati bentuk awan di langit.',
                'image' => NULL,
                'moral' => 'Mengamati awan melatih imajinasi anak.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif"]',
                'slug' => 'mengamati-bentuk-awan',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Mengamati Bentuk Awan',
                'type' => 'outdoor',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Hujan sudah berhenti! Ayo keluar dan lihat ke langit. Ada warna apa di sana?"},{"num":2,"text":"Itu namanya pelangi! Coba sebut warnanya satu per satu: merah, oranye, kuning, hijau, biru, nila, ungu."},{"num":3,"text":"Coba gambar pelangi yang kamu lihat di kertas saat sampai di rumah!"}]}',
                'desc' => 'Anak mengamati pelangi setelah hujan.',
                'image' => NULL,
                'moral' => 'Setelah hujan selalu ada keindahan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["bersyukur"]',
                'slug' => 'mengamati-pelangi',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Mengamati Pelangi',
                'type' => 'outdoor',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Ayo ke pantai! Lepas sepatu dan rasakan pasirnya di kaki. Lembut atau kasar?"},{"num":2,"text":"Dengarkan suara ombak. Besar atau kecil? Ayo bermain air di tepi pantai!"},{"num":3,"text":"Cari kerang di pasir! Ada yang putih, ada yang belang. Kumpulkan yang cantik!"}]}',
                'desc' => 'Anak bermain dan menjelajahi pantai.',
                'image' => NULL,
                'moral' => 'Pantai tempat bermain yang seru.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["bersyukur"]',
                'slug' => 'bermain-di-pantai',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Bermain di Pantai',
                'type' => 'outdoor',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Duduk diam di bawah pohon. Dengarkan! Ada suara apa? Cuit, cuit, cuit!"},{"num":2,"text":"Lihat ke atas! Ada burung kecil bernyanyi riang di dahan. Apa warnanya?"},{"num":3,"text":"Coba tiru suara burung itu. Cuit! Cuit! Siapa yang paling mirip?"}]}',
                'desc' => 'Anak mendengarkan dan mengenal suara burung.',
                'image' => NULL,
                'moral' => 'Mendengarkan suara alam bikin tenang.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["fokus"]',
                'slug' => 'mendengarkan-suara-burung',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Mendengarkan Suara Burung',
                'type' => 'outdoor',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Lihat daun itu! Ada kumbang kecil hijau mengkilap duduk di sana. Seperti permata!"},{"num":2,"text":"Diam-diam amati. Kumbang itu punya sayap lho! Di bawah cangkangnya."},{"num":3,"text":"Wah, kumbangnya terbang ke bunga! Coba ikuti dari mana ia datang."}]}',
                'desc' => 'Anak mengamati kumbang di kebun.',
                'image' => NULL,
                'moral' => 'Serangga kecil punya keindahan sendiri.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["fokus"]',
                'slug' => 'mengamati-kumbang',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Mengamati Kumbang',
                'type' => 'outdoor',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Ayo jalan-jalan di taman! Lihat pohon besar itu. Batangnya kuat dan daunnya banyak."},{"num":2,"text":"Di bawah pohon, ada semut berbaris rapi. Mereka bawa makanan ke sarang!"},{"num":3,"text":"Di kolam kecil, ada ikan kecil berenang. Airnya jernih, batu di dasar kelihatan."},{"num":4,"text":"Dekat bunga, ada kupu-kupu hinggap. Sayapnya oranye dan hitam. Cantik!"},{"num":5,"text":"Di rumput, ada belalang melompat. Tinggi sekali lompatannya!"},{"num":6,"text":"Lihat ke atas! Burung berkicau di dahan. Suaranya merdu."},{"num":7,"text":"Di tanah basah, ada cacing kecil. Dia membantu tanah jadi subur."},{"num":8,"text":"Wah, banyak sekali hewan di taman! Pulang dengan senyum ya."}]}',
                'desc' => 'Anak menjelajahi taman dan mengenal hewan kecil.',
                'image' => NULL,
                'moral' => 'Alam penuh hal menarik kalau kita mau mengamati.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif"]',
                'slug' => 'petualangan-di-taman',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Petualangan di Taman',
                'type' => 'outdoor',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Ayo ke kebun! Di sini ada banyak tanaman. Coba sentuh daunnya, halus atau kasar?"},{"num":2,"text":"Lihat pohon tomat! Buahnya sudah merah. Petik pelan-pelan ya, jangan rusak."},{"num":3,"text":"Di sebelahnya ada cabai. Kecil tapi pedas! Jangan pegang mata setelah pegang cabai."},{"num":4,"text":"Ayo siram tanaman! Ambil air dari ember, siram pelan di akar tanaman."},{"num":5,"text":"Di tanah, ada cacing kecil. Dia menggemburkan tanah supaya tanaman tumbuh subur."},{"num":6,"text":"Dengar dengung? Itu lebah! Dia mengambil madu dari bunga. Jangan diganggu."},{"num":7,"text":"Di pojok kebun, ada tanaman kangkung. Daunnya hijau dan segar."},{"num":8,"text":"Pulang bawa sayuran segar dari kebun! Enak dimasak nanti."}]}',
                'desc' => 'Anak belajar berkebun dan mengenal tanaman sayuran.',
                'image' => NULL,
                'moral' => 'Berkebun itu seru dan hasilnya bisa dimakan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["menjaga_alam"]',
                'slug' => 'petualangan-di-kebun',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Petualangan di Kebun',
                'type' => 'outdoor',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Ayo jalan ke sungai kecil! Airnya jernih, bisa lihat batu di dasar."},{"num":2,"text":"Di tepi sungai, ada katak hijau duduk di atas daun. Diam banget!"},{"num":3,"text":"Lihat ikan kecil berenang! Mereka melawan arus. Kuat ya!"},{"num":4,"text":"Di atas air, ada capung terbang rendah. Sayapnya berkilau kena sinar matahari."},{"num":5,"text":"Coba ambil batu halus dari tepi sungai. Ada yang putih, ada yang belang."},{"num":6,"text":"Dengar suara air mengalir? Tenang ya. Angin sore bertiup sejuk."},{"num":7,"text":"Di batu besar, ada lumut hijau. Licin kalau dipegang. Hati-hati!"},{"num":8,"text":"Pulang dengan batu cantik dan senyum bahagia! Sungai memang seru."}]}',
                'desc' => 'Anak menjelajahi sungai kecil dan mengenal hewan air.',
                'image' => NULL,
                'moral' => 'Alam di sekitar sungai indah dan penuh kehidupan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["bersyukur"]',
                'slug' => 'petualangan-di-sungai',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Petualangan di Sungai',
                'type' => 'outdoor',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Ayo ke sawah! Di sini ada padi hijau yang tumbuh tinggi. Luas sekali!"},{"num":2,"text":"Lihat ada burung bangau berdiri di antara padi. Tinggi dan anggun."},{"num":3,"text":"Di sana, petani membajak sawah pakai kerbau. Kerbau berjalan pelan di lumpur."},{"num":4,"text":"Di pinggir sawah, ada belalang melompat-lompat. Hijau warnanya, sama seperti daun."},{"num":5,"text":"Coba lihat air di sawah. Ada ikan kecil berenang di antara batang padi!"},{"num":6,"text":"Di pematang sawah, ada bunga kecil kuning tumbuh liar. Cantik!"},{"num":7,"text":"Coba jalan di lumpur sawah! Licin ya. Tapi seru!"},{"num":8,"text":"Pulang dengan baju kotor tapi senang! Sawah mengajarkan banyak hal."}]}',
                'desc' => 'Anak menjelajahi sawah dan mengenal kehidupan pedesaan.',
                'image' => NULL,
                'moral' => 'Sawah mengajarkan kita menghargai makanan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["bersyukur"]',
                'slug' => 'petualangan-di-sawah',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Petualangan di Sawah',
                'type' => 'outdoor',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"pages":[{"num":1,"text":"Ayo masuk hutan kecil! Di sini ada pohon tinggi yang batangnya besar sekali."},{"num":2,"text":"Lihat ke atas! Ada sarang lebah di dahan. Jangan terlalu dekat ya."},{"num":3,"text":"Di tanah, ada jamur kecil tumbuh di dekat akar pohon. Warnanya cokelat."},{"num":4,"text":"Dengar suara air? Di sana ada sungai kecil mengalir jernih."},{"num":5,"text":"Di sungai, ada ikan kecil berenang. Airnya dingin dan segar."},{"num":6,"text":"Di batang pohon, ada lumut hijau dan pakis tumbuh. Lembab di sini."},{"num":7,"text":"Ambil daun cantik yang jatuh. Ada yang merah, ada yang kuning. Untuk koleksi!"},{"num":8,"text":"Pulang dengan banyak cerita! Hutan itu rumah bagi banyak makhluk."}]}',
                'desc' => 'Anak menjelajahi hutan kecil dan mengenal tumbuhan.',
                'image' => NULL,
                'moral' => 'Hutan rumah bagi banyak makhluk hidup.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["menjaga_alam"]',
                'slug' => 'petualangan-di-hutan',
                'sort_order' => 0,
                'status' => 'approved',
                'title' => 'Petualangan di Hutan',
                'type' => 'outdoor',
                'views' => 0,
            ],
        ];

        Activity::where('type', ActivityType::OUTDOOR->value)->delete();
        DB::table("activities")->insertOrIgnore($dataTables);
    }
}
