<?php

namespace Database\Seeders\Activity;

use App\ActivityType;
use App\Models\Activity;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProyekKreatifSeeder extends Seeder
{
    public function run(): void
    {
        $dataTables = [
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kertas origami warna-warni","Pensil","Gunting"],"pages":[{"num":1,"text":"Ambil satu lembar kertas origami. Lipat menjadi segitiga, lalu buka kembali. Ini lipatan dasar yang penting!"},{"num":2,"text":"Lipat sisi kiri dan sisi kanan kertas ke garis tengah. Sekarang bentuknya seperti layang-layang."},{"num":3,"text":"Balik kertasnya. Lipat ujung atas ke bawah melewati garis tengah. Tekan kuat-kuat ya!"},{"num":4,"text":"Lipat sayap ke atas dan ke bawah. Gunting ujungnya supaya bentuk sayap lebih cantik."},{"num":5,"text":"Gambar pola di sayap pakai pensil. Bisa titik-titik atau garis-garis."},{"num":6,"text":"Kupu-kupu sudah jadi! Sayapnya cantik dan warna-warni."},{"num":7,"text":"Kupu-kupu origami ini mengajarkan kita sabar. Setiap lipatan harus rapi supaya hasilnya bagus."},{"num":8,"text":"Origami melatih tangan kita jadi kuat dan pintar. Terus berlatih ya!"}],"explanation":"Origami melatih motorik halus anak dan kesabaran. Setiap lipatan membutuhkan ketelitian, sehingga anak belajar fokus dan teliti."}',
                'desc' => 'Kertas origami warna-warni, Pensil, Gunting',
                'image' => NULL,
                'moral' => 'Anak belajar sabar dan kreatif dalam membuat kerajinan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","sabar"]',
                'slug' => 'origami-kupu-kupu',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Origami Kupu-Kupu',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kertas karton","Kertas warna","Gunting","Lem"],"pages":[{"num":1,"text":"Potong kertas warna menjadi kecil-kecil. Gunting hati-hati ya, jangan sampai terkena jari!"},{"num":2,"text":"Gambar lengkungan pelangi di kertas karton pakai pensil. Tujuh lengkungan untuk tujuh warna."},{"num":3,"text":"Tempel potongan kertas sesuai warna pelangi. Mulai dari merah di paling luar, lalu oranye, kuning, hijau, biru, nila, ungu."},{"num":4,"text":"Tambahkan awan kapas di sisi pelangi. Tempel pelan-pelan supaya rapi."},{"num":5,"text":"Kolase pelangi sudah jadi! Warna-warnanya cantik dan bikin senang."},{"num":6,"text":"Lihat hasilnya! Pelangi kertas ini indah sekali."},{"num":7,"text":"Membuat kolase melatih tangan anak jadi kuat dan pintar mengenal warna."},{"num":8,"text":"Warna pelangi ada tujuh: merah, oranye, kuning, hijau, biru, nila, ungu. Coba sebutkan!"}],"explanation":"Kolase melatih motorik halus anak saat memotong dan menempel. Anak juga belajar mengenal urutan warna pelangi."}',
                'desc' => 'Kertas karton, Kertas warna, Gunting, Lem',
                'image' => NULL,
                'moral' => 'Anak belajar mengenal warna dan melatih motorik halus.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","motorik_halus"]',
                'slug' => 'kolase-pelangi',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Kolase Pelangi',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kertas gambar besar","Cat air","Cotton bud","Air","Palet"],"pages":[{"num":1,"text":"Tuang cat air di palet. Pilih warna merah, kuning, biru, dan hijau. Siapkan juga semangkuk air."},{"num":2,"text":"Celupkan cotton bud ke cat merah. Tempelkan di kertas dengan cara ditekan-tekan. Bikin bunga!"},{"num":3,"text":"Ganti cotton bud kuning. Buat titik-titik di sekitar bunga merah. Ini kelopaknya!"},{"num":4,"text":"Pakai cat biru untuk buat langit. Titik-titik biru di bagian atas kertas."},{"num":5,"text":"Jangan lupa hijau untuk daun dan batang. Titik-titik hijau di bawah bunga."},{"num":6,"text":"Lukisan jari sudah jadi! Cantik sekali. Semua titik-titik warna jadi gambar indah."},{"num":7,"text":"Melukis dengan jari melatih anak berani bereksplorasi. Tidak ada yang salah dalam seni!"},{"num":8,"text":"Cuci tangan setelah selesai ya! Cat air mudah dibersihkan pakai air sabun."}],"explanation":"Lukisan jari melatih sensori anak dan kreativitas. Anak belajar mencampur warna dan mengekspresikan perasaan lewat seni."}',
                'desc' => 'Kertas gambar besar, Cat air, Cotton bud, Air, Palet',
                'image' => NULL,
                'moral' => 'Bereksplorasi dengan warna itu seru dan tidak ada yang salah.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","motorik_halus"]',
                'slug' => 'lukisan-jari-warna',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lukisan Jari Warna',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kardus bekas","Gunting","Pensil warna","Lem","Kancing baju"],"pages":[{"num":1,"text":"Ambil kardus bekas. Gambar bentuk badan dan kepala orang di kardus. Besar ya, seukuran tangan!"},{"num":2,"text":"Gunting bentuk badan dan kepala dengan hati-hati. Minta tolong orang dewasa kalau sulit."},{"num":3,"text":"Warnai wajah pakai pensil warna. Bikin mata, hidung, mulut, dan rambut."},{"num":4,"text":"Bisa pakai kancing untuk mata! Tempel dengan lem supaya kuat."},{"num":5,"text":"Tempel kancing baju sebagai kemeja. Lem dengan kuat supaya tidak lepas."},{"num":6,"text":"Bikin tangan dan kaki dari potongan kardus kecil. Tempel di sisi badan boneka."},{"num":7,"text":"Boneka kardus sudah jadi! Bisa jadi teman bermain dan bercerita."},{"num":8,"text":"Membuat boneka dari barang bekas mengajarkan anak daur ulang. Sampah bisa jadi mainan!"}],"explanation":"Membuat boneka dari kardus bekas mengajarkan anak untuk berkreasi dari barang bekas. Anak belajar daur ulang sambil melatih kreativitas."}',
                'desc' => 'Kardus bekas, Gunting, Pensil warna, Lem, Kancing baju',
                'image' => NULL,
                'moral' => 'Barang bekas bisa jadi mainan seru kalau kita kreatif.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","peduli_lingkungan"]',
                'slug' => 'boneka-kardus',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Boneka Kardus',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kertas HVS","Crayon","Stiker bintang","Gunting","Lem"],"pages":[{"num":1,"text":"Lipat kertas HVS menjadi dua. Ini jadi halaman buku kecilmu."},{"num":2,"text":"Gambar di halaman pertama pakai crayon. Bisa gambar keluarga, rumah, atau hewan kesukaanmu."},{"num":3,"text":"Di halaman kedua, gambar lagi! Cerita apa hari ini? Gambar saja semua yang kamu suka."}],"explanation":"Membuat buku gambar sederhana melatih anak mengekspresikan cerita lewat gambar. Anak belajar menyusun cerita dan mengembangkan imajinasi."}',
                'desc' => 'Kertas HVS, Crayon, Stiker bintang, Gunting, Lem',
                'image' => NULL,
                'moral' => 'Setiap gambar yang kita buat punya cerita sendiri.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","komunikasi"]',
                'slug' => 'buku-gambar-mini',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Buku Gambar Mini',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kertas karton","Manik-manik warna-warni","Tali","Gunting","Lem"],"pages":[{"num":1,"text":"Potong kertas karton jadi bentuk lingkaran. Ini jadi dasar bingkai fotomu."},{"num":2,"text":"Lubangi bagian atas lingkaran. Masukkan tali untuk menggantung."},{"num":3,"text":"Oleskan lem di tepi lingkaran. Tempel manik-manik satu per satu mengelilingi tepi."},{"num":4,"text":"Isi semua tepi dengan manik-manik sampai penuh. Pilih warna yang kamu suka!"},{"num":5,"text":"Di tengah lingkaran, tempel foto kecil atau gambar wajahmu."},{"num":6,"text":"Bingkai manik-manik sudah jadi! Cantik sekali."},{"num":7,"text":"Bingkai ini bisa jadi hadiah untuk orang tua. Hadiah buatan tangan itu spesial!"},{"num":8,"text":"Membuat bingkai foto melatih ketelitian anak saat menempel manik-manik kecil."}],"explanation":"Proyek ini melatih motorik halus anak saat menempel manik-manik. Anak juga belajar membuat hadiah untuk orang lain dengan tangan sendiri."}',
                'desc' => 'Kertas karton, Manik-manik warna-warni, Tali, Gunting, Lem',
                'image' => NULL,
                'moral' => 'Membuat hadiah sendiri untuk orang tersayang itu spesial.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","motorik_halus","sayang_keluarga"]',
                'slug' => 'bingkai-foto-manik',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Bingkai Foto Manik-Manik',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Daun kering berbagai bentuk","Kertas gambar","Cat air","Kuas","Air"],"pages":[{"num":1,"text":"Kumpulkan daun kering di halaman. Cari yang bentuknya berbeda-beda. Ada yang besar, ada yang kecil!"},{"num":2,"text":"Oleskan cat air di permukaan daun pakai kuas. Pilih warna merah, kuning, atau biru."},{"num":3,"text":"Balikkan daun yang sudah dicat ke kertas gambar. Tekan pelan-pelan supaya warnanya pindah."},{"num":4,"text":"Angkat daun pelan-pelan. Wah, bentuk daun sudah pindah ke kertas! Cantik sekali."},{"num":5,"text":"Ulangi dengan daun lain dan warna berbeda. Buat pola yang menarik di kertas."},{"num":6,"text":"Cap daun sudah jadi! Setiap daun punya bentuk unik. Alam jadi kanvas seni kita."},{"num":7,"text":"Membuat cap daun mengajarkan anak mengenal bentuk daun dan berkreasi dengan alam."},{"num":8,"text":"Alam punya banyak bentuk cantik. Coba amati daun di sekitarmu!"}],"explanation":"Cap daun melatih anak mengamati bentuk daun yang berbeda. Anak belajar bahwa alam bisa jadi alat seni yang indah."}',
                'desc' => 'Daun kering berbagai bentuk, Kertas gambar, Cat air, Kuas, Air',
                'image' => NULL,
                'moral' => 'Alam punya banyak bentuk cantik yang bisa kita jadikan seni.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","mengenal_alam"]',
                'slug' => 'cap-daun-kering',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Cap Daun Kering',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kertas origami","Gunting","Pensil warna","Stiker"],"pages":[{"num":1,"text":"Ambil kertas origami. Lipat dua bagian bawah ke atas. Ini jadi badan topimu."},{"num":2,"text":"Lipat ujung kiri dan kanan ke tengah. Bentuknya segitiga di bagian atas."},{"num":3,"text":"Lipat bagian bawah ke atas di kedua sisi. Ini jadi pinggiran topi supaya kuat."},{"num":4,"text":"Buka topi pelan-pelan. Tekan bagian bawah supaya bentuknya rata dan bisa dipakai."},{"num":5,"text":"Hias topi pakai pensil warna dan stiker. Gambar bintang, hati, atau apa saja yang kamu suka!"},{"num":6,"text":"Topi sudah jadi! Pakai di kepala dan jalan-jalan keliling rumah. Keren!"},{"num":7,"text":"Membuat topi kertas melatih anak mengikuti langkah-langkah dan berkreasi menghias."},{"num":8,"text":"Setiap lipatan harus tepat supaya topi bisa dipakai. Sabar ya!"}],"explanation":"Membuat topi kertas mengajarkan anak mengikuti instruksi berurutan. Setiap lipatan harus tepat supaya topi bisa dipakai."}',
                'desc' => 'Kertas origami, Gunting, Pensil warna, Stiker',
                'image' => NULL,
                'moral' => 'Mengikuti langkah-langkah dengan sabar menghasilkan karya yang bagus.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","sabar"]',
                'slug' => 'topi-kertas-lucu',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Topi Kertas Lucu',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Botol plastik bekas","Tanah","Benih tanaman kecil","Air","Spatula kecil"],"pages":[{"num":1,"text":"Cuci botol plastik bekas sampai bersih. Keringkan pakai lap. Ini jadi pot tanamanmu!"},{"num":2,"text":"Gunting botol jadi dua bagian. Ambil bagian bawah, ini jadi wadah tanam."},{"num":3,"text":"Isi botol dengan tanah sampai hampir penuh. Tekan pelan-pelan supaya tanahnya padat."},{"num":4,"text":"Buat lubang kecil di tanah pakai jari. Masukkan benih tanaman, lalu tutup dengan tanah tipis."},{"num":5,"text":"Siram air pelan-pelan. Jangan terlalu banyak, cukup supaya tanahnya basah."},{"num":6,"text":"Letakkan pot di tempat yang kena sinar matahari. Setiap hari siram sedikit air."},{"num":7,"text":"Tunggu beberapa hari. Benih akan tumbuh jadi tunas hijau kecil. Seru banget lihatnya!"},{"num":8,"text":"Merawat tanaman mengajarkan anak tanggung jawab. Tanaman butuh air dan kasih sayang setiap hari."}],"explanation":"Menanam dari benih mengajarkan anak tentang siklus hidup tanaman. Anak belajar sabar menunggu dan bertanggung jawab merawat makhluk hidup."}',
                'desc' => 'Botol plastik bekas, Tanah, Benih tanaman kecil, Air',
                'image' => NULL,
                'moral' => 'Merawat tanaman itu seperti merawat teman, butuh sabar dan sayang.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["sabar","peduli_lingkungan","tanggung_jawab"]',
                'slug' => 'kebun-mini-botol',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Kebun Mini dari Botol',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kertas karton","Benang wol","Gunting","Lem","Pensil warna"],"pages":[{"num":1,"text":"Gambar bentuk matahari besar di kertas karton. Bulat di tengah dengan garis-garis di luar."},{"num":2,"text":"Warnai matahari pakai kuning dan oranye. Cerah sekali!"},{"num":3,"text":"Gunting matahari mengikuti garis. Hati-hati ya, jangan sampai terpotong bagian dalam."},{"num":4,"text":"Potong benang wol jadi beberapa bagian. Tempel di belakang matahari, ini jadi sinarnya."},{"num":5,"text":"Hias matahari pakai pensil warna. Gambar senyum dan mata supaya lucu."},{"num":6,"text":"Gantung matahari di kamar pakai benang. Sekarang kamar jadi ceria!"},{"num":7,"text":"Membuat matahari kertas mengajarkan anak tentang bentuk dan warna."},{"num":8,"text":"Anak juga belajar menggunting dengan rapi. Terus berlatih ya!"}],"explanation":"Proyek matahari kertas melatih anak menggunting mengikuti garis lengkung. Anak juga belajar mengenal bentuk geometri sederhana."}',
                'desc' => 'Kertas karton, Benang wol, Gunting, Lem, Pensil warna',
                'image' => NULL,
                'moral' => 'Seperti matahari, kita bisa membuat orang lain ceria.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","motorik_halus"]',
                'slug' => 'matahari-kertas',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Matahari Kertas',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
        ];

        Activity::where('type', ActivityType::PROYEK_KREATIF->value)->delete();
        DB::table("activities")->insertOrIgnore($dataTables);
    }
}
