<?php

namespace Database\Seeders\Activity;

use App\ActivityType;
use App\Models\Activity;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProyekKreatifSeeder extends Seeder
{
    public function run(): void
    {
        $dataTables = [
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kertas origami warna-warni","Pensil","Gunting"],"pages":[{"num":1,"text":"Ambil satu lembar kertas origami. Lipat menjadi segitiga, lalu buka kembali. Ini lipatan dasar yang penting!"},{"num":2,"text":"Lipat sisi kiri dan sisi kanan kertas ke garis tengah. Sekarang bentuknya seperti layang-layang."},{"num":3,"text":"Balik kertasnya. Lipat ujung atas ke bawah melewati garis tengah. Tekan kuat-kuat ya!"},{"num":4,"text":"Lipat sayap ke atas dan ke bawah. Gunting ujungnya supaya bentuk sayap lebih cantik."},{"num":5,"text":"Gambar pola di sayap pakai pensil. Bisa titik-titik atau garis-garis."},{"num":6,"text":"Kupu-kupu sudah jadi! Sayapnya cantik dan warna-warni."},{"num":7,"text":"Kupu-kupu origami ini mengajarkan kita sabar. Setiap lipatan harus rapi supaya hasilnya bagus."},{"num":8,"text":"Origami melatih tangan kita jadi kuat dan pintar. Terus berlatih ya!"}],"explanation":"Origami melatih motorik halus anak dan kesabaran. Setiap lipatan membutuhkan ketelitian, sehingga anak belajar fokus dan teliti."}',
                'desc' => 'Kertas origami warna-warni, Pensil, Gunting',
                'image' => NULL,
                'moral' => 'Anak belajar sabar dan kreatif dalam membuat kerajinan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","sabar"]',
                'slug' => 'origami-kupu-kupu',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Origami Kupu-Kupu',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kertas karton","Kertas warna","Gunting","Lem"],"pages":[{"num":1,"text":"Potong kertas warna menjadi kecil-kecil. Gunting hati-hati ya, jangan sampai terkena jari!"},{"num":2,"text":"Gambar lengkungan pelangi di kertas karton pakai pensil. Tujuh lengkungan untuk tujuh warna."},{"num":3,"text":"Tempel potongan kertas sesuai warna pelangi. Mulai dari merah di paling luar, lalu oranye, kuning, hijau, biru, nila, ungu."},{"num":4,"text":"Tambahkan awan kapas di sisi pelangi. Tempel pelan-pelan supaya rapi."},{"num":5,"text":"Kolase pelangi sudah jadi! Warna-warnanya cantik dan bikin senang."},{"num":6,"text":"Lihat hasilnya! Pelangi kertas ini indah sekali."},{"num":7,"text":"Membuat kolase melatih tangan anak jadi kuat dan pintar mengenal warna."},{"num":8,"text":"Warna pelangi ada tujuh: merah, oranye, kuning, hijau, biru, nila, ungu. Coba sebutkan!"}],"explanation":"Kolase melatih motorik halus anak saat memotong dan menempel. Anak juga belajar mengenal urutan warna pelangi."}',
                'desc' => 'Kertas karton, Kertas warna, Gunting, Lem',
                'image' => NULL,
                'moral' => 'Anak belajar mengenal warna dan melatih motorik halus.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","motorik_halus"]',
                'slug' => 'kolase-pelangi',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Kolase Pelangi',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kertas gambar besar","Cat air","Cotton bud","Air","Palet"],"pages":[{"num":1,"text":"Tuang cat air di palet. Pilih warna merah, kuning, biru, dan hijau. Siapkan juga semangkuk air."},{"num":2,"text":"Celupkan cotton bud ke cat merah. Tempelkan di kertas dengan cara ditekan-tekan. Bikin bunga!"},{"num":3,"text":"Ganti cotton bud kuning. Buat titik-titik di sekitar bunga merah. Ini kelopaknya!"},{"num":4,"text":"Pakai cat biru untuk buat langit. Titik-titik biru di bagian atas kertas."},{"num":5,"text":"Jangan lupa hijau untuk daun dan batang. Titik-titik hijau di bawah bunga."},{"num":6,"text":"Lukisan jari sudah jadi! Cantik sekali. Semua titik-titik warna jadi gambar indah."},{"num":7,"text":"Melukis dengan jari melatih anak berani bereksplorasi. Tidak ada yang salah dalam seni!"},{"num":8,"text":"Cuci tangan setelah selesai ya! Cat air mudah dibersihkan pakai air sabun."}],"explanation":"Lukisan jari melatih sensori anak dan kreativitas. Anak belajar mencampur warna dan mengekspresikan perasaan lewat seni."}',
                'desc' => 'Kertas gambar besar, Cat air, Cotton bud, Air, Palet',
                'image' => NULL,
                'moral' => 'Bereksplorasi dengan warna itu seru dan tidak ada yang salah.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","motorik_halus"]',
                'slug' => 'lukisan-jari-warna',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Lukisan Jari Warna',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kardus bekas","Gunting","Pensil warna","Lem","Kancing baju"],"pages":[{"num":1,"text":"Ambil kardus bekas. Gambar bentuk badan dan kepala orang di kardus. Besar ya, seukuran tangan!"},{"num":2,"text":"Gunting bentuk badan dan kepala dengan hati-hati. Minta tolong orang dewasa kalau sulit."},{"num":3,"text":"Warnai wajah pakai pensil warna. Bikin mata, hidung, mulut, dan rambut."},{"num":4,"text":"Bisa pakai kancing untuk mata! Tempel dengan lem supaya kuat."},{"num":5,"text":"Tempel kancing baju sebagai kemeja. Lem dengan kuat supaya tidak lepas."},{"num":6,"text":"Bikin tangan dan kaki dari potongan kardus kecil. Tempel di sisi badan boneka."},{"num":7,"text":"Boneka kardus sudah jadi! Bisa jadi teman bermain dan bercerita."},{"num":8,"text":"Membuat boneka dari barang bekas mengajarkan anak daur ulang. Sampah bisa jadi mainan!"}],"explanation":"Membuat boneka dari kardus bekas mengajarkan anak untuk berkreasi dari barang bekas. Anak belajar daur ulang sambil melatih kreativitas."}',
                'desc' => 'Kardus bekas, Gunting, Pensil warna, Lem, Kancing baju',
                'image' => NULL,
                'moral' => 'Barang bekas bisa jadi mainan seru kalau kita kreatif.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","peduli_lingkungan"]',
                'slug' => 'boneka-kardus',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Boneka Kardus',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kertas HVS","Crayon","Stiker bintang","Gunting","Lem"],"pages":[{"num":1,"text":"Lipat kertas HVS menjadi dua. Ini jadi halaman buku kecilmu."},{"num":2,"text":"Gambar di halaman pertama pakai crayon. Bisa gambar keluarga, rumah, atau hewan kesukaanmu."},{"num":3,"text":"Di halaman kedua, gambar lagi! Cerita apa hari ini? Gambar saja semua yang kamu suka."}],"explanation":"Membuat buku gambar sederhana melatih anak mengekspresikan cerita lewat gambar. Anak belajar menyusun cerita dan mengembangkan imajinasi."}',
                'desc' => 'Kertas HVS, Crayon, Stiker bintang, Gunting, Lem',
                'image' => NULL,
                'moral' => 'Setiap gambar yang kita buat punya cerita sendiri.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","komunikasi"]',
                'slug' => 'buku-gambar-mini',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Buku Gambar Mini',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kertas karton","Manik-manik warna-warni","Tali","Gunting","Lem"],"pages":[{"num":1,"text":"Potong kertas karton jadi bentuk lingkaran. Ini jadi dasar bingkai fotomu."},{"num":2,"text":"Lubangi bagian atas lingkaran. Masukkan tali untuk menggantung."},{"num":3,"text":"Oleskan lem di tepi lingkaran. Tempel manik-manik satu per satu mengelilingi tepi."},{"num":4,"text":"Isi semua tepi dengan manik-manik sampai penuh. Pilih warna yang kamu suka!"},{"num":5,"text":"Di tengah lingkaran, tempel foto kecil atau gambar wajahmu."},{"num":6,"text":"Bingkai manik-manik sudah jadi! Cantik sekali."},{"num":7,"text":"Bingkai ini bisa jadi hadiah untuk orang tua. Hadiah buatan tangan itu spesial!"},{"num":8,"text":"Membuat bingkai foto melatih ketelitian anak saat menempel manik-manik kecil."}],"explanation":"Proyek ini melatih motorik halus anak saat menempel manik-manik. Anak juga belajar membuat hadiah untuk orang lain dengan tangan sendiri."}',
                'desc' => 'Kertas karton, Manik-manik warna-warni, Tali, Gunting, Lem',
                'image' => NULL,
                'moral' => 'Membuat hadiah sendiri untuk orang tersayang itu spesial.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","motorik_halus","sayang_keluarga"]',
                'slug' => 'bingkai-foto-manik',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Bingkai Foto Manik-Manik',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Daun kering berbagai bentuk","Kertas gambar","Cat air","Kuas","Air"],"pages":[{"num":1,"text":"Kumpulkan daun kering di halaman. Cari yang bentuknya berbeda-beda. Ada yang besar, ada yang kecil!"},{"num":2,"text":"Oleskan cat air di permukaan daun pakai kuas. Pilih warna merah, kuning, atau biru."},{"num":3,"text":"Balikkan daun yang sudah dicat ke kertas gambar. Tekan pelan-pelan supaya warnanya pindah."},{"num":4,"text":"Angkat daun pelan-pelan. Wah, bentuk daun sudah pindah ke kertas! Cantik sekali."},{"num":5,"text":"Ulangi dengan daun lain dan warna berbeda. Buat pola yang menarik di kertas."},{"num":6,"text":"Cap daun sudah jadi! Setiap daun punya bentuk unik. Alam jadi kanvas seni kita."},{"num":7,"text":"Membuat cap daun mengajarkan anak mengenal bentuk daun dan berkreasi dengan alam."},{"num":8,"text":"Alam punya banyak bentuk cantik. Coba amati daun di sekitarmu!"}],"explanation":"Cap daun melatih anak mengamati bentuk daun yang berbeda. Anak belajar bahwa alam bisa jadi alat seni yang indah."}',
                'desc' => 'Daun kering berbagai bentuk, Kertas gambar, Cat air, Kuas, Air',
                'image' => NULL,
                'moral' => 'Alam punya banyak bentuk cantik yang bisa kita jadikan seni.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","mengenal_alam"]',
                'slug' => 'cap-daun-kering',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Cap Daun Kering',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kertas origami","Gunting","Pensil warna","Stiker"],"pages":[{"num":1,"text":"Ambil kertas origami. Lipat dua bagian bawah ke atas. Ini jadi badan topimu."},{"num":2,"text":"Lipat ujung kiri dan kanan ke tengah. Bentuknya segitiga di bagian atas."},{"num":3,"text":"Lipat bagian bawah ke atas di kedua sisi. Ini jadi pinggiran topi supaya kuat."},{"num":4,"text":"Buka topi pelan-pelan. Tekan bagian bawah supaya bentuknya rata dan bisa dipakai."},{"num":5,"text":"Hias topi pakai pensil warna dan stiker. Gambar bintang, hati, atau apa saja yang kamu suka!"},{"num":6,"text":"Topi sudah jadi! Pakai di kepala dan jalan-jalan keliling rumah. Keren!"},{"num":7,"text":"Membuat topi kertas melatih anak mengikuti langkah-langkah dan berkreasi menghias."},{"num":8,"text":"Setiap lipatan harus tepat supaya topi bisa dipakai. Sabar ya!"}],"explanation":"Membuat topi kertas mengajarkan anak mengikuti instruksi berurutan. Setiap lipatan harus tepat supaya topi bisa dipakai."}',
                'desc' => 'Kertas origami, Gunting, Pensil warna, Stiker',
                'image' => NULL,
                'moral' => 'Mengikuti langkah-langkah dengan sabar menghasilkan karya yang bagus.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","sabar"]',
                'slug' => 'topi-kertas-lucu',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Topi Kertas Lucu',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8,9]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Botol plastik bekas","Tanah","Benih tanaman kecil","Air","Spatula kecil"],"pages":[{"num":1,"text":"Cuci botol plastik bekas sampai bersih. Keringkan pakai lap. Ini jadi pot tanamanmu!"},{"num":2,"text":"Gunting botol jadi dua bagian. Ambil bagian bawah, ini jadi wadah tanam."},{"num":3,"text":"Isi botol dengan tanah sampai hampir penuh. Tekan pelan-pelan supaya tanahnya padat."},{"num":4,"text":"Buat lubang kecil di tanah pakai jari. Masukkan benih tanaman, lalu tutup dengan tanah tipis."},{"num":5,"text":"Siram air pelan-pelan. Jangan terlalu banyak, cukup supaya tanahnya basah."},{"num":6,"text":"Letakkan pot di tempat yang kena sinar matahari. Setiap hari siram sedikit air."},{"num":7,"text":"Tunggu beberapa hari. Benih akan tumbuh jadi tunas hijau kecil. Seru banget lihatnya!"},{"num":8,"text":"Merawat tanaman mengajarkan anak tanggung jawab. Tanaman butuh air dan kasih sayang setiap hari."}],"explanation":"Menanam dari benih mengajarkan anak tentang siklus hidup tanaman. Anak belajar sabar menunggu dan bertanggung jawab merawat makhluk hidup."}',
                'desc' => 'Botol plastik bekas, Tanah, Benih tanaman kecil, Air',
                'image' => NULL,
                'moral' => 'Merawat tanaman itu seperti merawat teman, butuh sabar dan sayang.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["sabar","peduli_lingkungan","tanggung_jawab"]',
                'slug' => 'kebun-mini-botol',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Kebun Mini dari Botol',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'mimo',
                'data' => '{"materials":["Kertas karton","Benang wol","Gunting","Lem","Pensil warna"],"pages":[{"num":1,"text":"Gambar bentuk matahari besar di kertas karton. Bulat di tengah dengan garis-garis di luar."},{"num":2,"text":"Warnai matahari pakai kuning dan oranye. Cerah sekali!"},{"num":3,"text":"Gunting matahari mengikuti garis. Hati-hati ya, jangan sampai terpotong bagian dalam."},{"num":4,"text":"Potong benang wol jadi beberapa bagian. Tempel di belakang matahari, ini jadi sinarnya."},{"num":5,"text":"Hias matahari pakai pensil warna. Gambar senyum dan mata supaya lucu."},{"num":6,"text":"Gantung matahari di kamar pakai benang. Sekarang kamar jadi ceria!"},{"num":7,"text":"Membuat matahari kertas mengajarkan anak tentang bentuk dan warna."},{"num":8,"text":"Anak juga belajar menggunting dengan rapi. Terus berlatih ya!"}],"explanation":"Proyek matahari kertas melatih anak menggunting mengikuti garis lengkung. Anak juga belajar mengenal bentuk geometri sederhana."}',
                'desc' => 'Kertas karton, Benang wol, Gunting, Lem, Pensil warna',
                'image' => NULL,
                'moral' => 'Seperti matahari, kita bisa membuat orang lain ceria.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","motorik_halus"]',
                'slug' => 'matahari-kertas',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Matahari Kertas',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Manik-manik warna-warni","Tali elastis","Gunting"],"pages":[{"num":1,"text":"Pilih manik-manik warna yang kamu suka. Siapkan tali elastis."},{"num":2,"text":"Ukur tali di pergelangan tanganmu. Potong lebih panjang sedikit."},{"num":3,"text":"Masukkan manik-manik satu per satu ke tali."},{"num":4,"text":"Buat pola warna: merah, biru, kuning, ulangi."},{"num":5,"text":"Isi tali sampai penuh sesuai ukuran tangan."},{"num":6,"text":"Ikat tali dengan kuat di ujungnya. Gunting sisa tali."},{"num":7,"text":"Gelang sudah jadi! Cantik dan warna-warni."},{"num":8,"text":"Gelang ini bisa jadi hadiah untuk teman atau keluarga."}],"explanation":"Membuat gelang melatih motorik halus anak saat memasukkan manik-manik kecil. Anak juga belajar pola warna."}',
                'desc' => 'Manik-manik warna-warni, Tali elastis, Gunting',
                'image' => NULL,
                'moral' => 'Membuat hadiah sendiri itu spesial dan penuh sayang.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","motorik_halus"]',
                'slug' => 'gelang-dari-manik-manik',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Gelang dari Manik-Manik',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Kardus bekas besar","Gunting","Cat air","Pensil warna","Lem"],"pages":[{"num":1,"text":"Gambar bentuk dinosaurus di kardus. Besar ya!"},{"num":2,"text":"Gunting bentuk dinosaurus dengan hati-hati."},{"num":3,"text":"Warnai dinosaurus pakai cat air hijau atau cokelat."},{"num":4,"text":"Gambar mata, mulut, dan sisik di badan dinosaurus."},{"num":5,"text":"Buat ekor dari potongan kardus kecil. Tempel dengan lem."},{"num":6,"text":"Tambahkan gigi-gigi kecil dari kertas putih."},{"num":7,"text":"Dinosaurus kardus sudah jadi! Keren banget."},{"num":8,"text":"Bermain dinosaurus melatih imajinasi anak."}],"explanation":"Membuat dinosaurus dari kardus bekas melatih kreativitas dan mengajarkan daur ulang."}',
                'desc' => 'Kardus bekas besar, Gunting, Cat air, Pensil warna, Lem',
                'image' => NULL,
                'moral' => 'Barang bekas bisa jadi mainan seru kalau kita kreatif.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","berimajinasi"]',
                'slug' => 'dinosaurus-dari-kardus',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Dinosaurus dari Kardus',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Kertas tisu warna-warni","Kertas karton","Gunting","Lem","Pensil"],"pages":[{"num":1,"text":"Gambar batang bunga di kertas karton pakai pensil."},{"num":2,"text":"Potong kertas tisu jadi kotak-kotak kecil."},{"num":3,"text":"Bola-bola kertas tisu dengan jari. Bikin banyak!"},{"num":4,"text":"Tempel bola-bola tisu di atas karton jadi kelopak bunga."},{"num":5,"text":"Isi semua kelopak sampai penuh dan cantik."},{"num":6,"text":"Warnai batang dan daun pakai pensil warna hijau."},{"num":7,"text":"Bunga kertas tisu sudah jadi! Lembut dan indah."},{"num":8,"text":"Bunga ini tidak akan layu dan bisa jadi hiasan kamar."}],"explanation":"Membuat bunga dari kertas tisu melatih motorik halus anak saat membola-bola kertas."}',
                'desc' => 'Kertas tisu warna-warni, Kertas karton, Gunting, Lem, Pensil',
                'image' => NULL,
                'moral' => 'Membuat bunga sendiri melatih kesabaran dan kreativitas.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","motorik_halus"]',
                'slug' => 'bunga-dari-kertas-tisu',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Bunga dari Kertas Tisu',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Piring kertas","Cat air","Kuas","Gunting","Lem"],"pages":[{"num":1,"text":"Ambil piring kertas. Ini jadi wajahmu!"},{"num":2,"text":"Warnai piring dengan cat air sesuai warna kulitmu."},{"num":3,"text":"Gambar mata, hidung, dan mulut pakai pensil warna."},{"num":4,"text":"Potong kertas untuk rambut. Tempel di atas piring."},{"num":5,"text":"Tambahkan telinga dari potongan kertas kecil."},{"num":6,"text":"Hias dengan stiker atau kancing untuk mata."},{"num":7,"text":"Wajah dari piring sudah jadi! Lucu sekali."},{"num":8,"text":"Coba buat wajah Papa Mama juga ya!"}],"explanation":"Membuat wajah dari piring kertas melatih anak mengenal bagian wajah dan berkreasi."}',
                'desc' => 'Piring kertas, Cat air, Kuas, Gunting, Lem',
                'image' => NULL,
                'moral' => 'Mengenal bagian wajah sambil berkreasi itu seru.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","mengenal_tubuh"]',
                'slug' => 'wajah-dari-piring-kertas',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Wajah dari Piring Kertas',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Stik es krim","Lem","Cat air","Kertas","Pensil"],"pages":[{"num":1,"text":"Siapkan stik es krim. Cuci dan keringkan dulu ya."},{"num":2,"text":"Susun stik jadi bentuk segitiga untuk badan pesawat."},{"num":3,"text":"Lem setiap ujung stik supaya kuat dan tidak lepas."},{"num":4,"text":"Buat sayap dari dua stik yang disilangkan."},{"num":5,"text":"Tempel sayap di badan pesawat dengan lem."},{"num":6,"text":"Warnai pesawat pakai cat air biru atau merah."},{"num":7,"text":"Gambar jendela pesawat pakai spidol putih."},{"num":8,"text":"Pesawat stik es krim sudah jadi! Terbangkan imajinasimu!"}],"explanation":"Membuat pesawat dari stik es krim melatih anak menyusun dan merekatkan benda."}',
                'desc' => 'Stik es krim, Lem, Cat air, Kertas, Pensil',
                'image' => NULL,
                'moral' => 'Benda sederhana bisa jadi mainan kalau kita kreatif.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","motorik_halus"]',
                'slug' => 'pesawat-dari-stik-es-krim',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Pesawat dari Stik Es Krim',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Kardus bekas","Gunting","Lem","Pensil warna","Kertas warna"],"pages":[{"num":1,"text":"Ambil kardus bekas. Gambar pola rumah di kardus."},{"num":2,"text":"Gunting kardus jadi dinding, atap, dan lantai."},{"num":3,"text":"Lem dinding-dinding jadi kotak. Ini rumahmu!"},{"num":4,"text":"Buat atap segitiga dari kardus. Tempel di atas."},{"num":5,"text":"Gambar jendela dan pintu pakai pensil warna."},{"num":6,"text":"Hias dengan kertas warna untuk tirai dan bunga."},{"num":7,"text":"Rumah kardus sudah jadi! Bisa dimainkan dengan boneka."},{"num":8,"text":"Membuat rumah melatih anak berpikir tiga dimensi."}],"explanation":"Membuat rumah dari kardus bekas mengajarkan anak tentang bentuk dan struktur bangunan."}',
                'desc' => 'Kardus bekas, Gunting, Lem, Pensil warna, Kertas warna',
                'image' => NULL,
                'moral' => 'Membuat rumah sendiri melatih kreativitas dan ketelitian.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","berimajinasi"]',
                'slug' => 'rumah-dari-kardus',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Rumah dari Kardus',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Kertas origami warna","Pensil","Gunting"],"pages":[{"num":1,"text":"Ambil kertas origami. Lipat jadi segitiga, lalu buka."},{"num":2,"text":"Lipat sisi kiri dan kanan ke garis tengah."},{"num":3,"text":"Balik kertas. Lipat ujung atas ke bawah."},{"num":4,"text":"Lipat sayap ke atas dan ke bawah."},{"num":5,"text":"Gunting ujung sayap supaya lebih cantik."},{"num":6,"text":"Gambar pola di sayap pakai pensil."},{"num":7,"text":"Kupu-kupu origami sudah jadi! Sayapnya indah."},{"num":8,"text":"Origami melatih tangan jadi kuat dan teliti."}],"explanation":"Origami kupu-kupu melatih motorik halus anak dan kesabaran dalam melipat."}',
                'desc' => 'Kertas origami warna, Pensil, Gunting',
                'image' => NULL,
                'moral' => 'Setiap lipatan yang rapi menghasilkan karya yang indah.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","sabar"]',
                'slug' => 'kupu-kupu-dari-kertas-lipat',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Kupu-Kupu dari Kertas Lipat',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Botol plastik bekas","Cat air","Kertas warna","Gunting","Lem"],"pages":[{"num":1,"text":"Cuci botol plastik bekas sampai bersih."},{"num":2,"text":"Warnai botol pakai cat air biru atau hijau."},{"num":3,"text":"Keringkan botol di bawah kipas."},{"num":4,"text":"Gunting kertas warna jadi bentuk sirip dan ekor."},{"num":5,"text":"Tempel sirip di punggung botol dan ekor di belakang."},{"num":6,"text":"Gambar mata ikan pakai spidol di bagian depan."},{"num":7,"text":"Ikan dari botol plastik sudah jadi! Lucu banget."},{"num":8,"text":"Membuat ikan dari botol bekas mengajarkan daur ulang."}],"explanation":"Membuat ikan dari botol plastik bekas mengajarkan anak untuk berkreasi dari sampah."}',
                'desc' => 'Botol plastik bekas, Cat air, Kertas warna, Gunting, Lem',
                'image' => NULL,
                'moral' => 'Sampah plastik bisa jadi mainan seru kalau didaur ulang.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","peduli_lingkungan"]',
                'slug' => 'ikan-dari-botol-plastik',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Ikan dari Botol Plastik',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Kertas origami","Pensil warna","Stiker"],"pages":[{"num":1,"text":"Ambil kertas origami persegi."},{"num":2,"text":"Lipat jadi segitiga. Buka. Lipat segitiga lainnya."},{"num":3,"text":"Tekan tengah ke dalam. Lipat jadi segitiga kecil."},{"num":4,"text":"Lipat ujung ke luar. Ulangi di sisi lain."},{"num":5,"text":"Buka pelan-pelan. Bintang origami jadi!"},{"num":6,"text":"Hias dengan pensil warna dan stiker."},{"num":7,"text":"Bintang ini bisa digantung di langit-langit kamar."},{"num":8,"text":"Origami bintang melatih ketelitian dan sabar."}],"explanation":"Membuat bintang origami melatih anak mengikuti langkah lipatan yang tepat."}',
                'desc' => 'Kertas origami, Pensil warna, Stiker',
                'image' => NULL,
                'moral' => 'Dengan sabar dan teliti, kita bisa membuat karya indah.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","sabar"]',
                'slug' => 'bintang-dari-kertas-origami',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Bintang dari Kertas Origami',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Kardus bekas","Gunting","Spidol","Jarum pentul","Kertas warna"],"pages":[{"num":1,"text":"Gunting kardus jadi bentuk lingkaran besar."},{"num":2,"text":"Tulis angka 1 sampai 12 di tepi lingkaran."},{"num":3,"text":"Warnai setiap angka dengan warna berbeda."},{"num":4,"text":"Buat jarum jam dari kardus kecil. Tusuk di tengah."},{"num":5,"text":"Buat jarum menit lebih panjang dari kardus."},{"num":6,"text":"Pasang jarum dengan jarum pentul di tengah."},{"num":7,"text":"Jam kardus sudah jadi! Coba atur waktunya."},{"num":8,"text":"Jam ini membantu anak belajar membaca waktu."}],"explanation":"Membuat jam dari kardus mengajarkan anak membaca angka dan mengenal waktu."}',
                'desc' => 'Kardus bekas, Gunting, Spidol, Jarum pentul, Kertas warna',
                'image' => NULL,
                'moral' => 'Belajar mengenal waktu itu seru dan penting.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","matematika"]',
                'slug' => 'jam-dari-kardus',
                'sort_order' =>0,
                'status' => 'pending',
                'title' => 'Jam dari Kardus',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Kain perca berbagai warna","Gunting","Lem","Tali","Pensil"],"pages":[{"num":1,"text":"Kumpulkan kain perca dari sisa jahitan Mama."},{"num":2,"text":"Potong kain jadi persegi-persegi kecil."},{"num":3,"text":"Gambar pola tas di kertas. Gunting polanya."},{"num":4,"text":"Tempel potongan kain di pola tas dengan lem."},{"num":5,"text":"Isi seluruh pola dengan kain perca sampai penuh."},{"num":6,"text":"Buat tali tas dari kain yang dipotong memanjang."},{"num":7,"text":"Tempel tali di sisi tas. Tas kain perca jadi!"},{"num":8,"text":"Tas ini unik karena dibuat dari sisa kain."}],"explanation":"Membuat tas dari kain perca mengajarkan anak daur ulang dan menghargai bahan."}',
                'desc' => 'Kain perca berbagai warna, Gunting, Lem, Tali, Pensil',
                'image' => NULL,
                'moral' => 'Sisa bahan bisa jadi karya yang cantik dan berguna.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","peduli_lingkungan"]',
                'slug' => 'tas-dari-kain-perca',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Tas dari Kain Perca',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Kertas origami","Gunting","Tusuk sate","Lem"],"pages":[{"num":1,"text":"Ambil kertas origami persegi."},{"num":2,"text":"Lipat diagonal jadi segitiga. Buka."},{"num":3,"text":"Lipat diagonal lainnya. Buka."},{"num":4,"text":"Gunting dari ujung ke tengah di empat sisi."},{"num":5,"text":"Lipat satu ujung ke tengah. Lem."},{"num":6,"text":"Lipat semua ujung ke tengah dan lem. Kincir jadi!"},{"num":7,"text":"Tusuk tusuk sate di tengah kincir."},{"num":8,"text":"Tiup kincir angin dan lihat berputar! Seru!"}],"explanation":"Membuat kincir angin melatih anak mengikuti langkah lipatan dan menggunting."}',
                'desc' => 'Kertas origami, Gunting, Tusuk sate, Lem',
                'image' => NULL,
                'moral' => 'Mengikuti langkah-langkah dengan sabar menghasilkan karya.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","motorik_halus"]',
                'slug' => 'kincir-angin-dari-kertas',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Kincir Angin dari Kertas',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Botol plastik bekas","Cat air","Kertas warna","Gunting","Lem"],"pages":[{"num":1,"text":"Cuci botol plastik bekas sampai bersih."},{"num":2,"text":"Warnai botol dengan cat air oranye atau cokelat."},{"num":3,"text":"Keringkan botol di bawah kipas angin."},{"num":4,"text":"Gunting telinga kucing dari kertas. Tempel di botol."},{"num":5,"text":"Gambar mata dan kumis kucing pakai spidol."},{"num":6,"text":"Buat ekor dari kertas yang digulung. Tempel di belakang."},{"num":7,"text":"Kucing dari botol bekas sudah jadi! Lucu banget."},{"num":8,"text":"Membuat kucing dari botol bekas mengajarkan daur ulang."}],"explanation":"Membuat kucing dari botol bekas melatih kreativitas dan kesadaran lingkungan."}',
                'desc' => 'Botol plastik bekas, Cat air, Kertas warna, Gunting, Lem',
                'image' => NULL,
                'moral' => 'Botol bekas bisa jadi mainan lucu kalau kita kreatif.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","peduli_lingkungan"]',
                'slug' => 'kucing-dari-botol-bekas',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Kucing dari Botol Bekas',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Kapas","Kertas karton","Cat air","Kuas","Lem"],"pages":[{"num":1,"text":"Gambar lengkungan pelangi di kertas karton."},{"num":2,"text":"Siapkan tujuh warna cat air di palet."},{"num":3,"text":"Celupkan kapas ke cat merah. Tempel di lengkungan pertama."},{"num":4,"text":"Ganti kapas, celup ke oranye. Tempel di lengkungan kedua."},{"num":5,"text":"Lanjutkan dengan kuning, hijau, biru, nila, ungu."},{"num":6,"text":"Tambahkan awan kapas putih di sisi pelangi."},{"num":7,"text":"Pelangi dari kapas sudah jadi! Cantik dan lembut."},{"num":8,"text":"Pelangi mengajarkan kita tentang keindahan warna."}],"explanation":"Membuat pelangi dari kapas melatih anak mengenal urutan warna dan motorik halus."}',
                'desc' => 'Kapas, Kertas karton, Cat air, Kuas, Lem',
                'image' => NULL,
                'moral' => 'Keindahan warna pelangi mengajarkan keberagaman.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","mengenal_warna"]',
                'slug' => 'pelangi-dari-kapas',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Pelangi dari Kapas',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Tutup botol plastik berbagai ukuran","Lem","Kertas","Spidol","Kardus kecil"],"pages":[{"num":1,"text":"Kumpulkan tutup botol plastik dari berbagai ukuran."},{"num":2,"text":"Cuci dan keringkan semua tutup botol."},{"num":3,"text":"Susun tutup botol jadi bentuk badan robot di kardus."},{"num":4,"text":"Tempel tutup botol dengan lem satu per satu."},{"num":5,"text":"Buat kepala dari tutup botol besar."},{"num":6,"text":"Gambar mata dan mulut robot pakai spidol."},{"num":7,"text":"Robot dari tutup botol sudah jadi! Keren!"},{"num":8,"text":"Membuat robot dari barang bekas mengajarkan daur ulang."}],"explanation":"Membuat robot dari tutup botol mengajarkan anak berkreasi dari limbah plastik."}',
                'desc' => 'Tutup botol plastik, Lem, Kertas, Spidol, Kardus kecil',
                'image' => NULL,
                'moral' => 'Sampah plastik bisa jadi karya seni yang keren.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","peduli_lingkungan"]',
                'slug' => 'robot-dari-tutup-botol',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Robot dari Tutup Botol',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Piring kertas","Gunting","Cat air","Karet gelang","Lem"],"pages":[{"num":1,"text":"Ambil piring kertas. Gambar wajah di piring."},{"num":2,"text":"Gunting lubang mata dan mulut."},{"num":3,"text":"Warnai piring pakai cat air sesuai tokoh yang kamu mau."},{"num":4,"text":"Keringkan piring yang sudah dicat."},{"num":5,"text":"Buat lubang di sisi kiri dan kanan untuk tali."},{"num":6,"text":"Masukkan karet gelang sebagai tali topeng."},{"num":7,"text":"Topeng dari piring kertas sudah jadi! Pakai ya!"},{"num":8,"text":"Bikin topeng berbeda untuk teman-temanmu!"}],"explanation":"Membuat topeng melatih kreativitas anak dan bermain peran."}',
                'desc' => 'Piring kertas, Gunting, Cat air, Karet gelang, Lem',
                'image' => NULL,
                'moral' => 'Bermain peran melatih imajinasi dan keberanian.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","berimajinasi"]',
                'slug' => 'topeng-dari-piring-kertas',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Topeng dari Piring Kertas',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Kertas origami kuning dan cokelat","Gunting","Lem","Pensil"],"pages":[{"num":1,"text":"Gambar lingkaran besar di kertas kuning. Ini jadi pusat bunga."},{"num":2,"text":"Gunting lingkaran dengan rapi."},{"num":3,"text":"Gambar kelopak bunga matahari di kertas kuning."},{"num":4,"text":"Gunting kelopak dan tempel mengelilingi lingkaran."},{"num":5,"text":"Gambar dan gunting daun dari kertas hijau."},{"num":6,"text":"Tempel daun di batang dari kertas cokelat."},{"num":7,"text":"Bunga matahari kertas sudah jadi! Kuning cerah."},{"num":8,"text":"Bunga matahari selalu menghadap matahari. Ceria!"}],"explanation":"Membuat bunga matahari melatih anak menggunting mengikuti garis lengkung."}',
                'desc' => 'Kertas origami kuning dan cokelat, Gunting, Lem, Pensil',
                'image' => NULL,
                'moral' => 'Seperti bunga matahari, kita harus selalu ceria.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","motorik_halus"]',
                'slug' => 'bunga-matahari-dari-kertas',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Bunga Matahari dari Kertas',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Kulit telur bekas","Cat air","Kertas karton","Kuas","Lem"],"pages":[{"num":1,"text":"Kumpulkan kulit telur bekas. Cuci dan keringkan."},{"num":2,"text":"Remukkan kulit telur jadi potongan-potongan kecil."},{"num":3,"text":"Gambar bentuk kura-kura di kertas karton."},{"num":4,"text":"Oleskan lem di bagian cangkang kura-kura."},{"num":5,"text":"Tempel potongan kulit telur di cangkang kura-kura."},{"num":6,"text":"Warnai bagian kepala, kaki, dan ekor pakai cat air."},{"num":7,"text":"Kura-kura dari kulit telur sudah jadi! Unik banget."},{"num":8,"text":"Membuat karya dari kulit telur mengajarkan daur ulang."}],"explanation":"Membuat kura-kura dari kulit telur melatih kreativitas dan kesadaran lingkungan."}',
                'desc' => 'Kulit telur bekas, Cat air, Kertas karton, Kuas, Lem',
                'image' => NULL,
                'moral' => 'Sampah rumah tangga bisa jadi karya seni yang cantik.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","peduli_lingkungan"]',
                'slug' => 'kura-kura-dari-kulit-telur',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Kura-Kura dari Kulit Telur',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Kardus bekas","Gunting","Cat air","Kertas warna","Lem"],"pages":[{"num":1,"text":"Gambar bentuk naga di kardus. Panjang dan besar!"},{"num":2,"text":"Gunting bentuk naga dengan hati-hati."},{"num":3,"text":"Warnai naga pakai cat air hijau atau merah."},{"num":4,"text":"Gambar sisik dan mata naga pakai spidol."},{"num":5,"text":"Buat sayap dari kertas warna. Tempel di badan naga."},{"num":6,"text":"Buat ekor dari kertas yang digulung dan ditempel."},{"num":7,"text":"Naga dari kardus sudah jadi! Gagah banget."},{"num":8,"text":"Membuat naga melatih anak berimajinasi dan berkreasi."}],"explanation":"Membuat naga dari kardus bekas melatih kreativitas dan kemampuan menggunting anak."}',
                'desc' => 'Kardus bekas, Gunting, Cat air, Kertas warna, Lem',
                'image' => NULL,
                'moral' => 'Imajinasi yang liar bisa jadi karya yang luar biasa.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","berimajinasi"]',
                'slug' => 'naga-dari-kardus',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Naga dari Kardus',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
            [
                'active' => 1,
                'id' => NULL,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => 'kilo',
                'data' => '{"materials":["Daun kering berbagai ukuran","Kertas karton","Lem","Spidol","Cat air"],"pages":[{"num":1,"text":"Kumpulkan daun kering di halaman. Cari yang bentuknya bagus."},{"num":2,"text":"Keringkan daun di bawah sinar matahari."},{"num":3,"text":"Ambil dua daun besar untuk sayap kupu-kupu."},{"num":4,"text":"Tempel daun di kertas karton jadi sayap kupu-kupu."},{"num":5,"text":"Gambar badan kupu-kupu di tengah pakai spidol."},{"num":6,"text":"Tambahkan antena dari ranting kecil."},{"num":7,"text":"Warnai badan kupu-kupu pakai cat air."},{"num":8,"text":"Kupu-kupu dari daun kering sudah jadi! Alami banget."}],"explanation":"Membuat kupu-kupu dari daun kering mengajarkan anak memanfaatkan bahan alam."}',
                'desc' => 'Daun kering berbagai ukuran, Kertas karton, Lem, Spidol, Cat air',
                'image' => NULL,
                'moral' => 'Alam menyediakan bahan-bahan cantik untuk berkarya.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_kreatif","mengenal_alam"]',
                'slug' => 'kupu-kupu-dari-daun-kering',
                'sort_order' => 0,
                'status' => 'pending',
                'title' => 'Kupu-Kupu dari Daun Kering',
                'type' => 'proyek_kreatif',
                'views' => 0,
            ],
        ];

        Activity::where('type', ActivityType::PROYEK_KREATIF->value)->delete();
        DB::table("activities")->insertOrIgnore($dataTables);
    }
}
