<?php

namespace Database\Seeders\Activity;

use App\Models\Activity;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TebakTebakanSeeder extends Seeder
{
    public function run(): void
    {
        $samples = [
             [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"sound":"Moo moo","answer":"Sapi","hint":"Hewan yang memberi susu"},{"sound":"Kukuruyuk","answer":"Ayam","hint":"Hewan yang bertelur"},{"sound":"Meong","answer":"Kucing","hint":"Hewan yang suka menangkap tikus"},{"sound":"Guk guk","answer":"Anjing","hint":"Hewan yang setia pada tuannya"}],"moral":"Anak belajar mengenal suara hewan dan melatih daya ingat."}',
                'desc' => 'Anak menebak hewan dari suara yang didengar.',
                'id' => 782,
                'image' => NULL,
                'moral' => 'Anak belajar mengenal suara hewan dan melatih daya ingat.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","konsentrasi"]',
                'slug' => 'tebak-hewan-dari-suara',
                'sort_order' => 4,
                'status' => 'approved',
                'title' => 'Tebak Hewan dari Suara',
                'type' => 'tebak_tebakan',
                'views' => 5,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"description":"Buah ini kuning, panjang, dan manis","answer":"Pisang","hint":"Monyet suka makan ini"},{"description":"Buah ini bulat, merah, dan renyah","answer":"Apel","hint":"Buah dari luar negeri yang sangat populer"},{"description":"Buah ini besar, hijau di luar, merah di dalam","answer":"Semangka","hint":"Buah yang banyak airnya"},{"description":"Buah ini kecil, ungu, dan asam manis","answer":"Anggur","hint":"Buah yang dibuat jus atau kismis"}],"moral":"Anak belajar mengenal buah-buahan dan ciri-cirinya."}',
                'desc' => 'Anak menebak buah dari ciri-ciri yang disebutkan.',
                'id' => 783,
                'image' => NULL,
                'moral' => 'Anak belajar mengenal buah-buahan dan ciri-cirinya.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","pengetahuan"]',
                'slug' => 'tebak-buah-dari-deskripsi',
                'sort_order' => 5,
                'status' => 'approved',
                'title' => 'Tebak Buah dari Deskripsi',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"description":"Benda ini dipakai untuk membersihkan lantai","answer":"Sapu","hint":"Bentuknya panjang ada bulu-bulunya"},{"description":"Benda ini dipakai untuk minum air","answer":"Gelas","hint":"Bentuknya kecil dan bisa pecah"},{"description":"Benda ini dipakai untuk membuka pintu","answer":"Kunci","hint":"Bentuknya kecil dan terbuat dari logam"},{"description":"Benda ini dipakai untuk melihat wajah kita","answer":"Cermin","hint":"Permukaannya licin dan mengkilap"},{"description":"Benda ini dipakai untuk mengukur waktu","answer":"Jam","hint":"Bunyi tik tok setiap saat"}],"moral":"Anak belajar mengenal benda-benda di sekitar rumah dan fungsinya."}',
                'desc' => 'Anak menebak benda dari fungsi atau bentuknya.',
                'id' => 784,
                'image' => NULL,
                'moral' => 'Anak belajar mengenal benda-benda di sekitar rumah dan fungsinya.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","mengamati"]',
                'slug' => 'tebak-benda-di-sekitar-rumah',
                'sort_order' => 8,
                'status' => 'approved',
                'title' => 'Tebak Benda di Sekitar Rumah',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"description":"Hewan ini punya belalai panjang dan telinga lebar","answer":"Gajah","hint":"Hewan darat terbesar di dunia"},{"description":"Hewan ini punya leher sangat panjang","answer":"Jerapah","hint":"Hewan tertinggi di dunia"},{"description":"Hewan ini bisa melompat sangat tinggi dan punya kantong","answer":"Kanguru","hint":"Hewan dari Australia"},{"description":"Hewan ini berwarna hitam putih dan suka bambu","answer":"Panda","hint":"Hewan lucu dari Tiongkok"},{"description":"Hewan ini punya cangkang keras di punggungnya","answer":"Kura-kura","hint":"Hewan yang jalannya sangat lambat"},{"description":"Hewan ini bisa berubah warna mengikuti tempatnya","answer":"Bunglon","hint":"Ahli menyamar di antara daun"}],"moral":"Anak belajar mengenal ciri khas hewan dan melatih daya ingat."}',
                'desc' => 'Anak menebak hewan dari bentuk dan kebiasaannya.',
                'id' => 785,
                'image' => NULL,
                'moral' => 'Anak belajar mengenal ciri khas hewan dan melatih daya ingat.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","pengetahuan"]',
                'slug' => 'tebak-hewan-dari-ciri-ciri',
                'sort_order' => 9,
                'status' => 'approved',
                'title' => 'Tebak Hewan dari Ciri-ciri',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"description":"Warna apa yang dihasilkan dari merah dan kuning?","answer":"Oranye","hint":"Warna buah jeruk"},{"description":"Warna apa yang dihasilkan dari biru dan kuning?","answer":"Hijau","hint":"Warna daun di pohon"},{"description":"Warna apa yang dihasilkan dari merah dan biru?","answer":"Ungu","hint":"Warna buah anggur"},{"description":"Warna apa yang dihasilkan dari putih dan hitam?","answer":"Abu-abu","hint":"Warna awan mendung"},{"description":"Warna apa yang dihasilkan dari merah dan putih?","answer":"Merah muda","hint":"Warna bunga mawar"}],"moral":"Anak belajar mencampur warna dan mengenal hasilnya."}',
                'desc' => 'Anak menebak warna yang dihasilkan dari mencampur dua warna.',
                'id' => 786,
                'image' => NULL,
                'moral' => 'Anak belajar mencampur warna dan mengenal hasilnya.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","kreativitas"]',
                'slug' => 'tebak-warna-dari-campuran',
                'sort_order' => 10,
                'status' => 'approved',
                'title' => 'Tebak Warna dari Campuran',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"description":"Siapa yang pakai stetoskop untuk memeriksa?","answer":"Dokter","hint":"Orang yang merawat orang sakit"},{"description":"Siapa yang pakai kapur untuk menulis di papan?","answer":"Guru","hint":"Orang yang mengajar di sekolah"},{"description":"Siapa yang pakai setrika untuk merapikan baju?","answer":"Tukang setrika","hint":"Orang yang merapikan pakaian"},{"description":"Siapa yang pakai helm dan mengendarai motor?","answer":"Kurir","hint":"Orang yang mengantar paket ke rumah"},{"description":"Siapa yang pakai celemek dan memasak di dapur?","answer":"Koki","hint":"Orang yang membuat makanan enak"},{"description":"Siapa yang pakai sapu untuk membersihkan jalan?","answer":"Petugas kebersihan","hint":"Orang yang membuat lingkungan tetap bersih"}],"moral":"Anak belajar mengenal berbagai profesi dan alat kerjanya."}',
                'desc' => 'Anak menebak pekerjaan dari alat yang dipakai.',
                'id' => 787,
                'image' => NULL,
                'moral' => 'Anak belajar mengenal berbagai profesi dan alat kerjanya.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","pengetahuan"]',
                'slug' => 'tebak-profesi-dari-alat-kerja',
                'sort_order' => 11,
                'status' => 'approved',
                'title' => 'Tebak Profesi dari Alat Kerja',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"description":"Hewan apa yang tinggal di sarang lebah?","answer":"Lebah","hint":"Hewan yang menghasilkan madu"},{"description":"Hewan apa yang tinggal di kolam?","answer":"Ikan","hint":"Hewan yang berenang sepanjang hari"},{"description":"Hewan apa yang tinggal di lubang tanah?","answer":"Kelinci","hint":"Hewan yang suka wortel"},{"description":"Hewan apa yang tinggal di pohon?","answer":"Monyet","hint":"Hewan yang suka makan pisang"},{"description":"Hewan apa yang tinggal di kandang?","answer":"Ayam","hint":"Hewan yang bertelur setiap hari"}],"moral":"Anak belajar mengenal tempat tinggal berbagai hewan."}',
                'desc' => 'Anak menebak hewan dari tempat tinggalnya.',
                'id' => 788,
                'image' => NULL,
                'moral' => 'Anak belajar mengenal tempat tinggal berbagai hewan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","pengetahuan"]',
                'slug' => 'tebak-binatang-dari-tempat-tinggal',
                'sort_order' => 12,
                'status' => 'approved',
                'title' => 'Tebak Binatang dari Tempat Tinggal',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"description":"Sayuran ini oranye, panjang, dan renyah","answer":"Wortel","hint":"Kelinci sangat suka makan ini"},{"description":"Sayuran ini hijau, bentuknya bulat kecil-kecil","answer":"Buncis","hint":"Sering dimasak tumis"},{"description":"Sayuran ini hijau, bentuknya seperti pohon kecil","answer":"Brokoli","hint":"Sayuran sehat yang disukai anak"},{"description":"Sayuran ini merah, bulat, dan sering dibuat jus","answer":"Tomat","hint":"Rasanya asam segar"},{"description":"Sayuran ini putih, bentuknya seperti payung kecil","answer":"Jamur","hint":"Tumbuh di tempat yang lembap"},{"description":"Sayuran ini hijau panjang, sering dibuat lalapan","answer":"Mentimun","hint":"Rasanya segar dan banyak airnya"}],"moral":"Anak belajar mengenal sayuran dan ciri-cirinya."}',
                'desc' => 'Anak menebak sayuran dari bentuk dan warnanya.',
                'id' => 789,
                'image' => NULL,
                'moral' => 'Anak belajar mengenal sayuran dan ciri-cirinya.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","pengetahuan"]',
                'slug' => 'tebak-sayuran-dari-bentuk',
                'sort_order' => 13,
                'status' => 'approved',
                'title' => 'Tebak Sayuran dari Bentuk',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
        ];

        $maxOrder = Activity::max('sort_order') ?? 0;

        foreach ($samples as $i => $item) {
            Activity::updateOrCreate(
                ['slug' => Str::slug($item['title'])],
                [
                    'type' => 'tebak_tebakan',
                    'title' => $item['title'],
                    'desc' => $item['desc'] ?? null,
                    'image' => $item['image'] ?? null,
                    'moral' => $item['data']['moral'] ?? null,
                    'ages' => $item['ages'] ?? [],
                    'agama' => $item['agama'] ?? [],
                    'skills' => $item['skills'] ?? [],
                    'data' => $item['data'] ?? [],
                    'sort_order' => $maxOrder + $i + 1,
                    'active' => true,
                ]
            );
        }
    }
}
