<?php

namespace Database\Seeders\Activity;

use App\ActivityType;
use App\Models\Activity;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TebakTebakanSeeder extends Seeder {
    public function run(): void {
        $samples = [
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Suara Moo moo dari hewan apa?","answer":"Sapi","hint":"Hewan yang memberi susu"},{"question":"Suara Kukuruyuk dari hewan apa?","answer":"Ayam","hint":"Hewan yang bertelur"},{"question":"Suara Meong dari hewan apa?","answer":"Kucing","hint":"Hewan yang suka menangkap tikus"},{"question":"Suara Guk guk dari hewan apa?","answer":"Anjing","hint":"Hewan yang setia pada tuannya"}],"moral":"Anak belajar mengenal suara hewan dan melatih daya ingat."}',
                'desc' => 'Anak menebak hewan dari suara yang didengar.',
                'image' => NULL,
                'moral' => 'Anak belajar mengenal suara hewan dan melatih daya ingat.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","konsentrasi"]',
                'slug' => 'tebak-hewan-dari-suara',
                'sort_order' => 4,
                'status' => 'approved',
                'title' => 'Tebak Hewan dari Suara',
                'type' => 'tebak_tebakan',
                'views' => 5,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Buah ini kuning, panjang, dan manis. Apa?","answer":"Pisang","hint":"Monyet suka makan ini"},{"question":"Buah ini bulat, merah, dan renyah. Apa?","answer":"Apel","hint":"Buah dari luar negeri yang sangat populer"},{"question":"Buah ini besar, hijau di luar, merah di dalam. Apa?","answer":"Semangka","hint":"Buah yang banyak airnya"},{"question":"Buah ini kecil, ungu, dan asam manis. Apa?","answer":"Anggur","hint":"Buah yang dibuat jus atau kismis"}],"moral":"Anak belajar mengenal buah-buahan dan ciri-cirinya."}',
                'desc' => 'Anak menebak buah dari ciri-ciri yang disebutkan.',
                'image' => NULL,
                'moral' => 'Anak belajar mengenal buah-buahan dan ciri-cirinya.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","pengetahuan"]',
                'slug' => 'tebak-buah-dari-deskripsi',
                'sort_order' => 5,
                'status' => 'approved',
                'title' => 'Tebak Buah dari Deskripsi',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Benda ini dipakai untuk membersihkan lantai. Apa?","answer":"Sapu","hint":"Bentuknya panjang ada bulu-bulunya"},{"question":"Benda ini dipakai untuk minum air. Apa?","answer":"Gelas","hint":"Bentuknya kecil dan bisa pecah"},{"question":"Benda ini dipakai untuk membuka pintu. Apa?","answer":"Kunci","hint":"Bentuknya kecil dan terbuat dari logam"},{"question":"Benda ini dipakai untuk melihat wajah kita. Apa?","answer":"Cermin","hint":"Permukaannya licin dan mengkilap"},{"question":"Benda ini dipakai untuk mengukur waktu. Apa?","answer":"Jam","hint":"Bunyi tik tok setiap saat"}],"moral":"Anak belajar mengenal benda-benda di sekitar rumah dan fungsinya."}',
                'desc' => 'Anak menebak benda dari fungsi atau bentuknya.',
                'image' => NULL,
                'moral' => 'Anak belajar mengenal benda-benda di sekitar rumah dan fungsinya.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","mengamati"]',
                'slug' => 'tebak-benda-di-sekitar-rumah',
                'sort_order' => 8,
                'status' => 'approved',
                'title' => 'Tebak Benda di Sekitar Rumah',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Hewan ini punya belalai panjang dan telinga lebar. Apa?","answer":"Gajah","hint":"Hewan darat terbesar di dunia"},{"question":"Hewan ini punya leher sangat panjang. Apa?","answer":"Jerapah","hint":"Hewan tertinggi di dunia"},{"question":"Hewan ini bisa melompat sangat tinggi dan punya kantong. Apa?","answer":"Kanguru","hint":"Hewan dari Australia"},{"question":"Hewan ini berwarna hitam putih dan suka bambu. Apa?","answer":"Panda","hint":"Hewan lucu dari Tiongkok"},{"question":"Hewan ini punya cangkang keras di punggungnya. Apa?","answer":"Kura-kura","hint":"Hewan yang jalannya sangat lambat"},{"question":"Hewan ini bisa berubah warna mengikuti tempatnya. Apa?","answer":"Bunglon","hint":"Ahli menyamar di antara daun"}],"moral":"Anak belajar mengenal ciri khas hewan dan melatih daya ingat."}',
                'desc' => 'Anak menebak hewan dari bentuk dan kebiasaannya.',
                'image' => NULL,
                'moral' => 'Anak belajar mengenal ciri khas hewan dan melatih daya ingat.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","pengetahuan"]',
                'slug' => 'tebak-hewan-dari-ciri-ciri',
                'sort_order' => 9,
                'status' => 'approved',
                'title' => 'Tebak Hewan dari Ciri-ciri',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[5,6,7,8]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Warna apa yang dihasilkan dari merah dan kuning?","answer":"Oranye","hint":"Warna buah jeruk"},{"question":"Warna apa yang dihasilkan dari biru dan kuning?","answer":"Hijau","hint":"Warna daun di pohon"},{"question":"Warna apa yang dihasilkan dari merah dan biru?","answer":"Ungu","hint":"Warna buah anggur"},{"question":"Warna apa yang dihasilkan dari putih dan hitam?","answer":"Abu-abu","hint":"Warna awan mendung"},{"question":"Warna apa yang dihasilkan dari merah dan putih?","answer":"Merah muda","hint":"Warna bunga mawar"}],"moral":"Anak belajar mencampur warna dan mengenal hasilnya."}',
                'desc' => 'Anak menebak warna yang dihasilkan dari mencampur dua warna.',
                'image' => NULL,
                'moral' => 'Anak belajar mencampur warna dan mengenal hasilnya.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","kreativitas"]',
                'slug' => 'tebak-warna-dari-campuran',
                'sort_order' => 10,
                'status' => 'approved',
                'title' => 'Tebak Warna dari Campuran',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7,8]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Siapa yang pakai stetoskop untuk memeriksa?","answer":"Dokter","hint":"Orang yang merawat orang sakit"},{"question":"Siapa yang pakai kapur untuk menulis di papan?","answer":"Guru","hint":"Orang yang mengajar di sekolah"},{"question":"Siapa yang pakai setrika untuk merapikan baju?","answer":"Tukang setrika","hint":"Orang yang merapikan pakaian"},{"question":"Siapa yang pakai helm dan mengendarai motor?","answer":"Kurir","hint":"Orang yang mengantar paket ke rumah"},{"question":"Siapa yang pakai celemek dan memasak di dapur?","answer":"Koki","hint":"Orang yang membuat makanan enak"},{"question":"Siapa yang pakai sapu untuk membersihkan jalan?","answer":"Petugas kebersihan","hint":"Orang yang membuat lingkungan tetap bersih"}],"moral":"Anak belajar mengenal berbagai profesi dan alat kerjanya."}',
                'desc' => 'Anak menebak pekerjaan dari alat yang dipakai.',
                'image' => NULL,
                'moral' => 'Anak belajar mengenal berbagai profesi dan alat kerjanya.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","pengetahuan"]',
                'slug' => 'tebak-profesi-dari-alat-kerja',
                'sort_order' => 11,
                'status' => 'approved',
                'title' => 'Tebak Profesi dari Alat Kerja',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[3,4,5,6,7]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Hewan apa yang tinggal di sarang lebah?","answer":"Lebah","hint":"Hewan yang menghasilkan madu"},{"question":"Hewan apa yang tinggal di kolam?","answer":"Ikan","hint":"Hewan yang berenang sepanjang hari"},{"question":"Hewan apa yang tinggal di lubang tanah?","answer":"Kelinci","hint":"Hewan yang suka wortel"},{"question":"Hewan apa yang tinggal di pohon?","answer":"Monyet","hint":"Hewan yang suka makan pisang"},{"question":"Hewan apa yang tinggal di kandang?","answer":"Ayam","hint":"Hewan yang bertelur setiap hari"}],"moral":"Anak belajar mengenal tempat tinggal berbagai hewan."}',
                'desc' => 'Anak menebak hewan dari tempat tinggalnya.',
                'image' => NULL,
                'moral' => 'Anak belajar mengenal tempat tinggal berbagai hewan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","pengetahuan"]',
                'slug' => 'tebak-binatang-dari-tempat-tinggal',
                'sort_order' => 12,
                'status' => 'approved',
                'title' => 'Tebak Binatang dari Tempat Tinggal',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[4,5,6,7]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Sayuran ini oranye, panjang, dan renyah. Apa?","answer":"Wortel","hint":"Kelinci sangat suka makan ini"},{"question":"Sayuran ini hijau, bentuknya bulat kecil-kecil. Apa?","answer":"Buncis","hint":"Sering dimasak tumis"},{"question":"Sayuran ini hijau, bentuknya seperti pohon kecil. Apa?","answer":"Brokoli","hint":"Sayuran sehat yang disukai anak"},{"question":"Sayuran ini merah, bulat, dan sering dibuat jus. Apa?","answer":"Tomat","hint":"Rasanya asam segar"},{"question":"Sayuran ini putih, bentuknya seperti payung kecil. Apa?","answer":"Jamur","hint":"Tumbuh di tempat yang lembap"},{"question":"Sayuran ini hijau panjang, sering dibuat lalapan. Apa?","answer":"Mentimun","hint":"Rasanya segar dan banyak airnya"}],"moral":"Anak belajar mengenal sayuran dan ciri-cirinya."}',
                'desc' => 'Anak menebak sayuran dari bentuk dan warnanya.',
                'image' => NULL,
                'moral' => 'Anak belajar mengenal sayuran dan ciri-cirinya.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["berpikir_logis","pengetahuan"]',
                'slug' => 'tebak-sayuran-dari-bentuk',
                'sort_order' => 13,
                'status' => 'approved',
                'title' => 'Tebak Sayuran dari Bentuk',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Berwarna kuning, bentuknya bulat, rasanya manis?","answer":"Pisang","hint":"Buah yang mudah dikupas"},{"question":"Berwarna merah, rasanya manis segar?","answer":"Apel","hint":"Buah yang sering dimakan sehari-hari"},{"question":"Berwarna oranye, mengandung banyak vitamin C?","answer":"Jeruk","hint":"Buah yang rasanya asam dan manis"}],"moral":"Anak mengenal nama dan ciri-ciri buah-buahan."}',
                'desc' => 'Anak menebak nama buah dari ciri-cirinya.',
                'image' => NULL,
                'moral' => 'Anak mengenal nama dan ciri-ciri buah-buahan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_benda","kosa_kata"]',
                'slug' => 'tebak-nama-buah',
                'sort_order' => 1,
                'status' => 'pending',
                'title' => 'Tebak Nama Buah',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Dipakai di kepala agar tidak kepanasan?","answer":"Topi","hint":"Melindungi kepala dari sinar matahari"},{"question":"Dipakai di kaki saat berjalan keluar rumah?","answer":"Sepatu","hint":"Melindungi kaki agar tidak terluka"},{"question":"Dipakai di badan agar tetap hangat?","answer":"Baju","hint":"Pakaian yang dipakai setiap hari"}],"moral":"Anak mengenal nama dan fungsi pakaian."}',
                'desc' => 'Anak menebak nama pakaian dari kegunaannya.',
                'image' => NULL,
                'moral' => 'Anak mengenal nama dan fungsi pakaian.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_benda","ingatan"]',
                'slug' => 'tebak-nama-pakaian',
                'sort_order' => 2,
                'status' => 'pending',
                'title' => 'Tebak Nama Pakaian',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Berwarna putih, lembut, bisa dimakan dengan nasi?","answer":"Tahu","hint":"Makanan dari kacang kedelai"},{"question":"Bentuknya bulat pipih, berwarna cokelat?","answer":"Kerupuk","hint":"Makanan renyah yang enak"},{"question":"Rasanya manis, terbuat dari gula?","answer":"Permen","hint":"Makanan yang disukai anak-anak"}],"moral":"Anak mengenal berbagai jenis makanan sehari-hari."}',
                'desc' => 'Anak menebak nama makanan dari ciri-cirinya.',
                'image' => NULL,
                'moral' => 'Anak mengenal berbagai jenis makanan sehari-hari.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kosa_kata","mengenal_benda"]',
                'slug' => 'tebak-nama-makanan',
                'sort_order' => 3,
                'status' => 'pending',
                'title' => 'Tebak Nama Makanan',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Suara Kukuruyuk bunyinya siapa?","answer":"Ayam","hint":"Bangunkan orang di pagi hari"},{"question":"Suara Meong bunyinya siapa?","answer":"Kucing","hint":"Suka bermain dengan bola benang"},{"question":"Suara Guk guk bunyinya siapa?","answer":"Anjing","hint":"Menjaga rumah dengan setia"}],"moral":"Anak mengenal suara dan nama hewan peliharaan."}',
                'desc' => 'Anak menebak nama hewan dari suaranya.',
                'image' => NULL,
                'moral' => 'Anak mengenal suara dan nama hewan peliharaan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["pendengaran","ingatan"]',
                'slug' => 'tebak-hewan-dari-suara',
                'sort_order' => 4,
                'status' => 'pending',
                'title' => 'Tebak Hewan dari Suara',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Benda apa yang dipakai untuk menyikat gigi?","answer":"Sikat gigi","hint":"Bersihkan gigi setiap pagi dan malam"},{"question":"Benda apa yang dipakai untuk mandi?","answer":"Sabun","hint":"Membuat badan menjadi bersih dan wangi"},{"question":"Benda apa yang dipakai untuk mengeringkan badan?","answer":"Handuk","hint":"Dipakai setelah mandi"}],"moral":"Anak mengenal benda untuk menjaga kebersihan diri."}',
                'desc' => 'Anak menebak nama benda kebersihan dari kegunaannya.',
                'image' => NULL,
                'moral' => 'Anak mengenal benda untuk menjaga kebersihan diri.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_benda","kebiasaan_baik"]',
                'slug' => 'tebak-benda-kebersihan',
                'sort_order' => 5,
                'status' => 'pending',
                'title' => 'Tebak Benda Kebersihan',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Berwarna hijau, tumbuh di kebun, dimasak menjadi sayur?","answer":"Bayam","hint":"Sayuran yang membuat tubuh kuat"},{"question":"Berwarna oranye, bentuknya panjang?","answer":"Wortel","hint":"Baik untuk kesehatan mata"},{"question":"Berwarna ungu, rasanya enak dimasak?","answer":"Terong","hint":"Sayuran yang banyak disukai"}],"moral":"Anak mengenal nama dan manfaat sayuran."}',
                'desc' => 'Anak menebak nama sayuran dari ciri-cirinya.',
                'image' => NULL,
                'moral' => 'Anak mengenal nama dan manfaat sayuran.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_benda","kesehatan"]',
                'slug' => 'tebak-nama-sayuran',
                'sort_order' => 6,
                'status' => 'pending',
                'title' => 'Tebak Nama Sayuran',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Benda apa yang dipakai untuk minum?","answer":"Gelas","hint":"Tempat air minum"},{"question":"Benda apa yang dipakai untuk makan nasi?","answer":"Sendok","hint":"Alat makan yang biasa dipakai"},{"question":"Benda apa yang dipakai untuk menaruh makanan?","answer":"Piring","hint":"Tempat makanan saat makan"}],"moral":"Anak mengenal nama dan fungsi peralatan makan."}',
                'desc' => 'Anak menebak nama peralatan makan dari kegunaannya.',
                'image' => NULL,
                'moral' => 'Anak mengenal nama dan fungsi peralatan makan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_benda","kosa_kata"]',
                'slug' => 'tebak-peralatan-makan',
                'sort_order' => 7,
                'status' => 'pending',
                'title' => 'Tebak Peralatan Makan',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Benda apa yang terang saat malam hari?","answer":"Lampu","hint":"Membuat ruangan menjadi terang"},{"question":"Benda apa yang dipakai untuk duduk?","answer":"Kursi","hint":"Tempat duduk yang nyaman"},{"question":"Benda apa yang dipakai untuk tidur?","answer":"Kasur","hint":"Tempat istirahat yang empuk"}],"moral":"Anak mengenal benda-benda di dalam rumah."}',
                'desc' => 'Anak menebak nama benda di rumah dari kegunaannya.',
                'image' => NULL,
                'moral' => 'Anak mengenal benda-benda di dalam rumah.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_benda","lingkungan"]',
                'slug' => 'tebak-benda-di-rumah',
                'sort_order' => 8,
                'status' => 'pending',
                'title' => 'Tebak Benda di Rumah',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Berwarna merah, bulat, ada bijinya?","answer":"Tomat","hint":"Bisa dimakan mentah atau dimasak"},{"question":"Berwarna hijau panjang, rasanya segar?","answer":"Timun","hint":"Sering dimakan sebagai lalapan"},{"question":"Berwarna putih, bentuknya bulat besar?","answer":"Kubis","hint":"Sayuran yang renyah"}],"moral":"Anak mengenal berbagai jenis sayuran segar."}',
                'desc' => 'Anak menebak nama sayuran dari rupa dan rasanya.',
                'image' => NULL,
                'moral' => 'Anak mengenal berbagai jenis sayuran segar.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_benda","penglihatan"]',
                'slug' => 'tebak-nama-sayuran-2',
                'sort_order' => 9,
                'status' => 'pending',
                'title' => 'Tebak Sayuran Segar',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Hewan apa yang berenang di air?","answer":"Ikan","hint":"Bernapas dengan insang"},{"question":"Hewan apa yang terbang di langit?","answer":"Burung","hint":"Memiliki sayap untuk terbang"},{"question":"Hewan apa yang suka melompat?","answer":"Kelinci","hint":"Telinganya panjang dan bulunya lembut"}],"moral":"Anak mengenal tempat hidup dan ciri hewan."}',
                'desc' => 'Anak menebak nama hewan dari ciri hidupnya.',
                'image' => NULL,
                'moral' => 'Anak mengenal tempat hidup dan ciri hewan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_hewan","ingatan"]',
                'slug' => 'tebak-hewan-dari-ciri',
                'sort_order' => 10,
                'status' => 'pending',
                'title' => 'Tebak Hewan dari Ciri',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Benda apa yang dipakai untuk menulis?","answer":"Pensil","hint":"Bisa dihapus jika salah tulis"},{"question":"Benda apa yang dipakai untuk menghapus tulisan?","answer":"Penghapus","hint":"Bentuknya kecil dan lembut"},{"question":"Benda apa tempat menulis dan menggambar?","answer":"Buku","hint":"Berisi halaman putih atau bergaris"}],"moral":"Anak mengenal peralatan belajar sederhana."}',
                'desc' => 'Anak menebak nama peralatan belajar dari kegunaannya.',
                'image' => NULL,
                'moral' => 'Anak mengenal peralatan belajar sederhana.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_benda","belajar"]',
                'slug' => 'tebak-peralatan-belajar',
                'sort_order' => 11,
                'status' => 'pending',
                'title' => 'Tebak Peralatan Belajar',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Berwarna cokelat, bentuknya bulat kecil?","answer":"Anggur","hint":"Bisa dimakan langsung"},{"question":"Berwarna hijau berkulit tebal, rasanya manis?","answer":"Semangka","hint":"Isinya berwarna merah dan berair"},{"question":"Berwarna kuning, bentuknya panjang melengkung?","answer":"Pisang","hint":"Mudah dibawa dan dimakan"}],"moral":"Anak mengenal nama dan rasa buah-buahan segar."}',
                'desc' => 'Anak menebak nama buah dari rupa dan rasanya.',
                'image' => NULL,
                'moral' => 'Anak mengenal nama dan rasa buah-buahan segar.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["penglihatan","kosa_kata"]',
                'slug' => 'tebak-nama-buah-2',
                'sort_order' => 12,
                'status' => 'pending',
                'title' => 'Tebak Buah Segar',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Benda apa yang melindungi mata dari sinar matahari?","answer":"Kacamata","hint":"Dipakai di atas hidung"},{"question":"Benda apa yang dipakai untuk menutup telinga saat hujan?","answer":"Topi lebar","hint":"Melindungi kepala dan telinga"},{"question":"Benda apa yang dipakai untuk melindungi tangan saat bekerja?","answer":"Sarung tangan","hint":"Membuat tangan tetap bersih dan aman"}],"moral":"Anak mengenal fungsi benda pelindung diri."}',
                'desc' => 'Anak menebak nama benda pelindung dari kegunaannya.',
                'image' => NULL,
                'moral' => 'Anak mengenal fungsi benda pelindung diri.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_benda","keamanan"]',
                'slug' => 'tebak-benda-pelindung',
                'sort_order' => 13,
                'status' => 'pending',
                'title' => 'Tebak Benda Pelindung',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Hewan apa yang memberi susu untuk kita minum?","answer":"Sapi","hint":"Besar dan berkaki empat"},{"question":"Hewan apa yang bertelur dan bisa dimakan?","answer":"Ayam","hint":"Bisa dipelihara di halaman rumah"},{"question":"Hewan apa yang suka menggigit tulang?","answer":"Anjing","hint":"Bisa menjadi sahabat manusia"}],"moral":"Anak mengenal manfaat hewan bagi manusia."}',
                'desc' => 'Anak menebak nama hewan dari manfaatnya.',
                'image' => NULL,
                'moral' => 'Anak mengenal manfaat hewan bagi manusia.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_hewan","pengetahuan"]',
                'slug' => 'tebak-hewan-dari-manfaat',
                'sort_order' => 14,
                'status' => 'pending',
                'title' => 'Tebak Hewan dari Manfaatnya',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Benda apa yang berputar dan dipakai untuk jalan?","answer":"Roda","hint":"Ada pada sepeda dan mobil"},{"question":"Benda apa yang terbang membawa orang ke tempat jauh?","answer":"Pesawat","hint":"Terbang tinggi di langit"},{"question":"Benda apa yang berjalan di atas rel?","answer":"Kereta","hint":"Mengangkut banyak orang"}],"moral":"Anak mengenal alat transportasi sederhana."}',
                'desc' => 'Anak menebak nama kendaraan dari cirinya.',
                'image' => NULL,
                'moral' => 'Anak mengenal alat transportasi sederhana.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_benda","lingkungan"]',
                'slug' => 'tebak-nama-kendaraan',
                'sort_order' => 15,
                'status' => 'pending',
                'title' => 'Tebak Nama Kendaraan',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Benda apa yang berwarna putih dan panas saat dimasak?","answer":"Nasi","hint":"Makanan pokok sehari-hari"},{"question":"Benda apa yang terbuat dari tepung dan digoreng?","answer":"Roti goreng","hint":"Makanan ringan yang enak"},{"question":"Benda apa yang terbuat dari kacang dan rasanya gurih?","answer":"Tempe","hint":"Makanan sehat dan bergizi"}],"moral":"Anak mengenal makanan sehat dan bergizi."}',
                'desc' => 'Anak menebak nama makanan sehat dari cirinya.',
                'image' => NULL,
                'moral' => 'Anak mengenal makanan sehat dan bergizi.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["kesehatan","kosa_kata"]',
                'slug' => 'tebak-makanan-sehat',
                'sort_order' => 16,
                'status' => 'pending',
                'title' => 'Tebak Makanan Sehat',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Benda apa yang menyinari bumi di siang hari?","answer":"Matahari","hint":"Terbit di timur dan terbenam di barat"},{"question":"Benda apa yang bersinar terang di malam hari?","answer":"Bulan","hint":"Bentuknya bisa bulat atau sabit"},{"question":"Benda apa yang berkelap-kelip di langit malam?","answer":"Bintang","hint":"Terlihat banyak di langit yang cerah"}],"moral":"Anak mengenal benda-benda di langit."}',
                'desc' => 'Anak menebak nama benda langit dari cirinya.',
                'image' => NULL,
                'moral' => 'Anak mengenal benda-benda di langit.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["pengamatan","pengetahuan"]',
                'slug' => 'tebak-benda-di-langit',
                'sort_order' => 17,
                'status' => 'pending',
                'title' => 'Tebak Benda di Langit',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Benda apa yang tumbuh tinggi dan memiliki daun?","answer":"Pohon","hint":"Memberikan naungan dan oksigen"},{"question":"Benda apa yang tumbuh di tanah dan berwarna-warni?","answer":"Bunga","hint":"Mengeluarkan bau yang harum"},{"question":"Benda apa yang berwarna hijau dan tumbuh merata di tanah?","answer":"Rumput","hint":"Tempat bermain yang nyaman"}],"moral":"Anak mengenal tumbuhan di sekitar lingkungan."}',
                'desc' => 'Anak menebak nama tumbuhan dari cirinya.',
                'image' => NULL,
                'moral' => 'Anak mengenal tumbuhan di sekitar lingkungan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_tumbuhan","lingkungan"]',
                'slug' => 'tebak-nama-tumbuhan',
                'sort_order' => 18,
                'status' => 'pending',
                'title' => 'Tebak Nama Tumbuhan',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Benda apa yang dipakai untuk menutup kaki saat dingin?","answer":"Kaos kaki","hint":"Melindungi kaki agar tetap hangat"},{"question":"Benda apa yang dipakai untuk melindungi tangan saat dingin?","answer":"Sarung tangan","hint":"Berbahan lembut dan hangat"},{"question":"Benda apa yang dipakai melingkar di leher saat dingin?","answer":"Syal","hint":"Membuat leher tetap hangat dan nyaman"}],"moral":"Anak mengenal pakaian untuk menjaga kehangatan tubuh."}',
                'desc' => 'Anak menebak nama pakaian hangat dari kegunaannya.',
                'image' => NULL,
                'moral' => 'Anak mengenal pakaian untuk menjaga kehangatan tubuh.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_benda","kebiasaan"]',
                'slug' => 'tebak-pakaian-hangat',
                'sort_order' => 19,
                'status' => 'pending',
                'title' => 'Tebak Pakaian Hangat',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ],
            [
                'active' => 1,
                'addon_id' => NULL,
                'agama' => '[]',
                'ages' => '[1,2,3]',
                'created_by' => 1,
                'creator' => NULL,
                'data' => '{"questions":[{"question":"Benda apa yang berisi air dan bisa diminum?","answer":"Botol minum","hint":"Dibawa saat bepergian"},{"question":"Benda apa yang dipakai untuk mengelap keringat?","answer":"Kain lap","hint":"Bisa dipakai juga untuk membersihkan meja"},{"question":"Benda apa tempat menyimpan mainan?","answer":"Kotak mainan","hint":"Membuat kamar tetap rapi dan bersih"}],"moral":"Anak mengenal benda yang membantu menjaga kerapian dan kebersihan."}',
                'desc' => 'Anak menebak nama benda sehari-hari dari kegunaannya.',
                'image' => NULL,
                'moral' => 'Anak mengenal benda yang membantu menjaga kerapian dan kebersihan.',
                'notes' => NULL,
                'plans' => NULL,
                'prompt' => NULL,
                'skills' => '["mengenal_benda","kerapian"]',
                'slug' => 'tebak-benda-sehari-hari',
                'sort_order' => 20,
                'status' => 'pending',
                'title' => 'Tebak Benda Sehari-hari',
                'type' => 'tebak_tebakan',
                'views' => 0,
            ]
        ];


        $maxOrder = Activity::max('sort_order') ?? 0;

        Activity::where('type', ActivityType::TEBAK_TEBAKAN->value)->delete();
        foreach ($samples as $i => $item) {
            $data = is_string($item['data']) ? json_decode($item['data'], true) : $item['data'];
            $ages = is_string($item['ages']) ? json_decode($item['ages'], true) : $item['ages'];
            $agama = is_string($item['agama']) ? json_decode($item['agama'], true) : $item['agama'];
            $skills = is_string($item['skills']) ? json_decode($item['skills'], true) : $item['skills'];

            Activity::updateOrCreate(
                ['slug' => Str::slug($item['title'])],
                [
                    'type' => 'tebak_tebakan',
                    'title' => $item['title'],
                    'desc' => $item['desc'] ?? null,
                    'image' => $item['image'] ?? null,
                    'moral' => $data['moral'] ?? $item['moral'] ?? null,
                    'ages' => $ages ?? [],
                    'agama' => $agama ?? [],
                    'skills' => $skills ?? [],
                    'data' => $data ?? [],
                    'sort_order' => $maxOrder + $i + 1,
                    'active' => true,
                ]
            );
        }
    }
}
