<?php

namespace Database\Seeders;

use App\Models\MasterSkill;
use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    public function run(): void
    {
        $skills = [
            ['skill_key' => 'bersyukur', 'skill_emoji' => '🤲', 'skill_title' => 'Bersyukur', 'skill_desc' => 'Anak belajar mengucap syukur atas nikmat kecil.', 'skill_ages' => [2,3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['spiritual'], 'skill_agama' => null, 'skill_color' => '#4CAF50', 'skill_bg' => '#E8F5E9', 'skill_evaluasi' => ['Apakah anak mengucap "Alhamdulillah" saat menerima sesuatu?','Apakah anak tidak mudah mengeluh tentang makanan atau mainan?','Apakah anak bisa menghargai pemberian orang lain?','Apakah anak senang berbagi dengan teman?','Apakah anak mengucap terima kasih tanpa diminta?']],
            ['skill_key' => 'jujur', 'skill_emoji' => '🤝', 'skill_title' => 'Jujur', 'skill_desc' => 'Anak belajar berkata jujur meskipun sulit.', 'skill_ages' => [3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['spiritual'], 'skill_agama' => null, 'skill_color' => '#4CAF50', 'skill_bg' => '#E8F5E9', 'skill_evaluasi' => ['Apakah anak mengakui kesalahan tanpa takut dihukum?','Apakah anak bercerita dengan jujur tentang kegiatannya?','Apakah anak tidak mengambil barang orang lain?','Apakah anak berani mengatakan kebenaran meskipun sulit?','Apakah anak tidak berbohong untuk menghindari masalah?']],
            ['skill_key' => 'peduli_sesama', 'skill_emoji' => '💛', 'skill_title' => 'Peduli Sesama', 'skill_desc' => 'Anak belajar membantu orang di sekitarnya.', 'skill_ages' => [2,3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['spiritual'], 'skill_agama' => null, 'skill_color' => '#4CAF50', 'skill_bg' => '#E8F5E9', 'skill_evaluasi' => ['Apakah anak menolong teman yang kesulitan?','Apakah anak peduli dengan perasaan orang lain?','Apakah anak mau berbagi mainan atau makanan?','Apakah anak senang membantu pekerjaan rumah?','Apakah anak menunjukkan kasih sayang pada hewan?']],
            ['skill_key' => 'menghormati_ortu', 'skill_emoji' => '🙏', 'skill_title' => 'Menghormati Orang Tua', 'skill_desc' => 'Anak belajar sopan dan patuh.', 'skill_ages' => [2,3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['spiritual'], 'skill_agama' => null, 'skill_color' => '#4CAF50', 'skill_bg' => '#E8F5E9', 'skill_evaluasi' => ['Apakah anak menggunakan kata "tolong" dan "terima kasih"?','Apakah anak mendengarkan nasihat orang tua?','Apakah anak tidak membantah saat dinasehati?','Apakah anak senang membantu orang tua?','Apakah anak meminta izin sebelum melakukan sesuatu?']],
            ['skill_key' => 'tidak_mudah_menyerah', 'skill_emoji' => '💪', 'skill_title' => 'Tidak Mudah Menyerah', 'skill_desc' => 'Anak belajar mencoba lagi saat gagal.', 'skill_ages' => [3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['karakter'], 'skill_agama' => null, 'skill_color' => '#FF9800', 'skill_bg' => '#FFF3E0', 'skill_evaluasi' => ['Apakah anak terus mencoba saat gagal?','Apakah anak tidak mudah marah saat kesulitan?','Apakah anak mau belajar hal baru meskipun sulit?','Apakah anak tidak langsung menyerah saat tugas berat?','Apakah anak termotivasi untuk memperbaiki kesalahan?']],
            ['skill_key' => 'berani_bicara', 'skill_emoji' => '🗣', 'skill_title' => 'Berani Bicara', 'skill_desc' => 'Anak belajar menyampaikan pendapat.', 'skill_ages' => [3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['karakter'], 'skill_agama' => null, 'skill_color' => '#FF9800', 'skill_bg' => '#FFF3E0', 'skill_evaluasi' => ['Apakah anak berani menyampaikan pendapat?','Apakah anak tidak malu bertanya di depan kelas?','Apakah anak bisa menjelaskan keinginannya dengan jelas?','Apakah anak berani berbicara dengan orang baru?','Apakah anak tidak takut tampil di depan umum?']],
            ['skill_key' => 'berani_mencoba', 'skill_emoji' => '🔥', 'skill_title' => 'Berani Mencoba', 'skill_desc' => 'Anak belajar menghadapi tantangan baru.', 'skill_ages' => [2,3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['karakter'], 'skill_agama' => null, 'skill_color' => '#FF9800', 'skill_bg' => '#FFF3E0', 'skill_evaluasi' => ['Apakah anak mau mencoba makanan baru?','Apakah anak tertarik dengan kegiatan yang belum pernah dicoba?','Apakah anak tidak takut mencoba permainan baru?','Apakah anak mau mencoba sendiri sebelum minta bantuan?','Apakah anak senang dengan tantangan baru?']],
            ['skill_key' => 'menyelesaikan_tugas', 'skill_emoji' => '🎯', 'skill_title' => 'Menyelesaikan Tugas', 'skill_desc' => 'Anak belajar bertanggung jawab.', 'skill_ages' => [4,5,6,7,8,9,10,11], 'skill_pilars' => ['karakter'], 'skill_agama' => null, 'skill_color' => '#FF9800', 'skill_bg' => '#FFF3E0', 'skill_evaluasi' => ['Apakah anak menyelesaikan pekerjaan yang dimulai?','Apakah anak tidak meninggalkan mainan begitu saja?','Apakah anak bisa fokus pada satu tugas sampai selesai?','Apakah anak ingat tanggung jawabnya tanpa diingatkan?','Apakah anak merasa puas saat menyelesaikan sesuatu?']],
            ['skill_key' => 'berpikir_kreatif', 'skill_emoji' => '🎨', 'skill_title' => 'Berpikir Kreatif', 'skill_desc' => 'Anak belajar menemukan ide baru.', 'skill_ages' => [2,3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['kreatifitas'], 'skill_agama' => null, 'skill_color' => '#2196F3', 'skill_bg' => '#E3F2FD', 'skill_evaluasi' => ['Apakah anak suka menggambar atau membuat kerajinan?','Apakah anak punya imajinasi yang kreatif saat bermain?','Apakah anak bisa menemukan solusi unik untuk masalah?','Apakah anak senang bereksperimen dengan bahan baru?','Apakah anak suka bercerita atau membuat cerita?']],
            ['skill_key' => 'eksperimen', 'skill_emoji' => '🔬', 'skill_title' => 'Eksperimen', 'skill_desc' => 'Anak belajar mencoba hal baru dengan rasa ingin tahu.', 'skill_ages' => [3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['kreatifitas'], 'skill_agama' => null, 'skill_color' => '#2196F3', 'skill_bg' => '#E3F2FD', 'skill_evaluasi' => ['Apakah anak bertanya "mengapa" tentang hal di sekitarnya?','Apakah anak suka mencoba dan mengamati hasilnya?','Apakah anak senang dengan percobaan sederhana?','Apakah anak rasa ingin tahu yang tinggi?','Apakah anak suka mengamati alam dan hewan?']],
            ['skill_key' => 'memecahkan_masalah', 'skill_emoji' => '🧩', 'skill_title' => 'Memecahkan Masalah', 'skill_desc' => 'Anak belajar mencari solusi sendiri.', 'skill_ages' => [4,5,6,7,8,9,10,11], 'skill_pilars' => ['kreatifitas'], 'skill_agama' => null, 'skill_color' => '#2196F3', 'skill_bg' => '#E3F2FD', 'skill_evaluasi' => ['Apakah anak bisa menyelesaikan puzzle atau teka-teki?','Apakah anak berpikir sebelum bertindak?','Apakah anak mencari cara sendiri untuk mengatasi kesulitan?','Apakah anak bisa menyusun strategi sederhana?','Apakah anak belajar dari kesalahan sebelumnya?']],
            ['skill_key' => 'berimajinasi', 'skill_emoji' => '✨', 'skill_title' => 'Berimajinasi', 'skill_desc' => 'Anak belajar menggunakan daya imajinasinya.', 'skill_ages' => [2,3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['kreatifitas'], 'skill_agama' => null, 'skill_color' => '#2196F3', 'skill_bg' => '#E3F2FD', 'skill_evaluasi' => ['Apakah anak suka bermain peran (dokter, guru, dll)?','Apakah anak bisa membuat cerita dari imajinasinya?','Apakah anak punya teman khayalan atau dunia imajinasi?','Apakah anak suka bermain dengan benda seolah-olah benda lain?','Apakah anak senang mendengarkan atau membaca dongeng?']],
            ['skill_key' => 'fokus', 'skill_emoji' => '🎯', 'skill_title' => 'Fokus', 'skill_desc' => 'Anak belajar berkonsentrasi pada satu hal.', 'skill_ages' => [3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['disiplin'], 'skill_agama' => null, 'skill_color' => '#9C27B0', 'skill_bg' => '#F3E5F5', 'skill_evaluasi' => ['Apakah anak bisa duduk tenang selama 15 menit?','Apakah anak tidak mudah terganggu saat mengerjakan sesuatu?','Apakah anak bisa mendengarkan cerita sampai selesai?','Apakah anak fokus saat mengerjakan tugas sekolah?','Apakah anak tidak sering melamun saat diajak bicara?']],
            ['skill_key' => 'atur_waktu', 'skill_emoji' => '⏰', 'skill_title' => 'Atur Waktu', 'skill_desc' => 'Anak belajar mengelola waktunya.', 'skill_ages' => [4,5,6,7,8,9,10,11], 'skill_pilars' => ['disiplin'], 'skill_agama' => null, 'skill_color' => '#9C27B0', 'skill_bg' => '#F3E5F5', 'skill_evaluasi' => ['Apakah anak tahu kapan waktunya belajar dan bermain?','Apakah anak tidak terlambat bangun tidur?','Apakah anak bisa menyelesaikan tugas tepat waktu?','Apakah anak tidak terlalu lama menonton layar?','Apakah anak punya rutinitas harian yang teratur?']],
            ['skill_key' => 'rutin_belajar', 'skill_emoji' => '📖', 'skill_title' => 'Rutin Belajar', 'skill_desc' => 'Anak belajar konsisten belajar setiap hari.', 'skill_ages' => [3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['disiplin'], 'skill_agama' => null, 'skill_color' => '#9C27B0', 'skill_bg' => '#F3E5F5', 'skill_evaluasi' => ['Apakah anak mau belajar tanpa disuruh?','Apakah anak punya jadwal belajar yang konsisten?','Apakah anak senang membaca buku?','Apakah anak mau mengulang pelajaran yang sudah dipelajari?','Apakah anak menunjukkan kemajuan dalam belajar?']],
            ['skill_key' => 'patuh_aturan', 'skill_emoji' => '✅', 'skill_title' => 'Patuh Aturan', 'skill_desc' => 'Anak belajar mengikuti kesepakatan.', 'skill_ages' => [3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['disiplin'], 'skill_agama' => null, 'skill_color' => '#9C27B0', 'skill_bg' => '#F3E5F5', 'skill_evaluasi' => ['Apakah anak mengikuti aturan di rumah?','Apakah anak patuh di sekolah?','Apakah anak tidak melanggar kesepakatan yang sudah dibuat?','Apakah anak mengerti konsekuensi dari perbuatannya?','Apakah anak bisa menunggu giliran?']],
            ['skill_key' => 'masak_sederhana', 'skill_emoji' => '🍳', 'skill_title' => 'Masak Sederhana', 'skill_desc' => 'Anak belajar menyiapkan makanan sendiri.', 'skill_ages' => [5,6,7,8,9,10,11], 'skill_pilars' => ['kemandirian'], 'skill_agama' => null, 'skill_color' => '#3F51B5', 'skill_bg' => '#E8EAF6', 'skill_evaluasi' => ['Apakah anak mau membantu di dapur?','Apakah anak bisa menyiapkan makanan sederhana?','Apakah anak berhati-hati saat menggunakan alat dapur?','Apakah anak senang mencoba resep baru?','Apakah anak bisa membersihkan setelah memasak?']],
            ['skill_key' => 'beres_beres', 'skill_emoji' => '🧹', 'skill_title' => 'Beres-beres', 'skill_desc' => 'Anak belajar merapikan barangnya.', 'skill_ages' => [3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['kemandirian'], 'skill_agama' => null, 'skill_color' => '#3F51B5', 'skill_bg' => '#E8EAF6', 'skill_evaluasi' => ['Apakah anak merapikan mainan setelah bermain?','Apakah anak bisa merapikan tempat tidurnya sendiri?','Apakah anak tidak meninggalkan barang sembarangan?','Apakah anak mau membantu merapikan rumah?','Apakah anak tahu di mana barang-barangnya disimpan?']],
            ['skill_key' => 'kebersihan_diri', 'skill_emoji' => '🚿', 'skill_title' => 'Kebersihan Diri', 'skill_desc' => 'Anak belajar mandi dan sikat gigi sendiri.', 'skill_ages' => [3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['kemandirian'], 'skill_agama' => null, 'skill_color' => '#3F51B5', 'skill_bg' => '#E8EAF6', 'skill_evaluasi' => ['Apakah anak bisa mandi sendiri?','Apakah anak sikat gigi tanpa disuruh?','Apakah anak cuci tangan sebelum makan?','Apakah anak bisa memilih baju sendiri?','Apakah anak menjaga kebersihan pakaiannya?']],
            ['skill_key' => 'mengatur_uang', 'skill_emoji' => '💰', 'skill_title' => 'Mengatur Uang', 'skill_desc' => 'Anak belajar menabung dan berhemat.', 'skill_ages' => [6,7,8,9,10,11], 'skill_pilars' => ['kemandirian'], 'skill_agama' => null, 'skill_color' => '#3F51B5', 'skill_bg' => '#E8EAF6', 'skill_evaluasi' => ['Apakah anak punya celengan atau tabungan?','Apakah anak tidak boros jajan?','Apakah anak bisa membedakan kebutuhan dan keinginan?','Apakah anak senang menabung?','Apakah anak menghargai uang?']],
            ['skill_key' => 'berbagi', 'skill_emoji' => '🎁', 'skill_title' => 'Berbagi', 'skill_desc' => 'Anak belajar membagi dengan orang lain.', 'skill_ages' => [2,3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['sosial'], 'skill_agama' => null, 'skill_color' => '#8D6E63', 'skill_bg' => '#EFEBE9', 'skill_evaluasi' => ['Apakah anak mau berbagi mainan dengan teman?','Apakah anak senang memberi makanan ke orang lain?','Apakah anak tidak pelit dengan barangnya?','Apakah anak bisa bermain gantian?','Apakah anak senang membantu teman yang membutuhkan?']],
            ['skill_key' => 'kerja_sama', 'skill_emoji' => '👫', 'skill_title' => 'Kerja Sama', 'skill_desc' => 'Anak belajar bekerja sama dalam tim.', 'skill_ages' => [3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['sosial'], 'skill_agama' => null, 'skill_color' => '#8D6E63', 'skill_bg' => '#EFEBE9', 'skill_evaluasi' => ['Apakah anak bisa bermain bersama tanpa bertengkar?','Apakah anak mau bergantian saat bermain?','Apakah anak bisa mengikuti aturan kelompok?','Apakah anak senang bekerja sama dalam tim?','Apakah anak tidak mendominasi saat bermain?']],
            ['skill_key' => 'mendengarkan', 'skill_emoji' => '👂', 'skill_title' => 'Mendengarkan', 'skill_desc' => 'Anak belajar mendengarkan orang lain.', 'skill_ages' => [2,3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['sosial'], 'skill_agama' => null, 'skill_color' => '#8D6E63', 'skill_bg' => '#EFEBE9', 'skill_evaluasi' => ['Apakah anak mendengarkan saat orang lain bicara?','Apakah anak tidak memotong pembicaraan?','Apakah anak bisa mengikuti instruksi sederhana?','Apakah anak memperhatikan saat guru menjelaskan?','Apakah anak tidak cuek saat diajak bicara?']],
            ['skill_key' => 'empati', 'skill_emoji' => '💗', 'skill_title' => 'Empati', 'skill_desc' => 'Anak belajar memahami perasaan orang lain.', 'skill_ages' => [3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['sosial'], 'skill_agama' => null, 'skill_color' => '#8D6E63', 'skill_bg' => '#EFEBE9', 'skill_evaluasi' => ['Apakah anak bisa merasakan kesedihan teman?','Apakah anak menolong teman yang menangis?','Apakah anak tidak mengejek orang lain?','Apakah anak peduli dengan perasaan adik/kakak?','Apakah anak senang menghibur orang yang sedih?']],
            ['skill_key' => 'mengenali_emosi', 'skill_emoji' => '😊', 'skill_title' => 'Mengenali Emosi', 'skill_desc' => 'Anak belajar mengenal perasaannya.', 'skill_ages' => [2,3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['emosi'], 'skill_agama' => null, 'skill_color' => '#F44336', 'skill_bg' => '#FFEBEE', 'skill_evaluasi' => ['Apakah anak bisa menyebutkan perasaannya?','Apakah anak tahu kapan ia sedih atau senang?','Apakah anak bisa mengenali wajah marah dan senang?','Apakah anak bercerita tentang perasaannya?','Apakah anak tidak bingung dengan emosinya?']],
            ['skill_key' => 'mengelola_marah', 'skill_emoji' => '😤', 'skill_title' => 'Mengelola Marah', 'skill_desc' => 'Anak belajar menenangkan diri.', 'skill_ages' => [3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['emosi'], 'skill_agama' => null, 'skill_color' => '#F44336', 'skill_bg' => '#FFEBEE', 'skill_evaluasi' => ['Apakah anak tidak mudah marah berlebihan?','Apakah anak bisa menenangkan diri sendiri?','Apakah anak tidak memukul saat marah?','Apakah anak bisa mengungkapkan marah dengan kata-kata?','Apakah anak tidak merusak barang saat kesal?']],
            ['skill_key' => 'quality_time', 'skill_emoji' => '👨‍👩‍👧', 'skill_title' => 'Quality Time', 'skill_desc' => 'Anak belajar menikmati waktu bersama keluarga.', 'skill_ages' => [1,2,3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['emosi'], 'skill_agama' => null, 'skill_color' => '#F44336', 'skill_bg' => '#FFEBEE', 'skill_evaluasi' => ['Apakah anak senang menghabiskan waktu dengan keluarga?','Apakah anak tidak lebih memilih gadget daripada keluarga?','Apakah anak mau ikut kegiatan keluarga?','Apakah anak bercerita tentang harinya?','Apakah anak terlihat bahagia saat bersama keluarga?']],
            ['skill_key' => 'komunikasi_keluarga', 'skill_emoji' => '💬', 'skill_title' => 'Komunikasi Keluarga', 'skill_desc' => 'Anak belajar bercerita ke orang tua.', 'skill_ages' => [3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['emosi'], 'skill_agama' => null, 'skill_color' => '#F44336', 'skill_bg' => '#FFEBEE', 'skill_evaluasi' => ['Apakah anak bercerita tentang kegiatannya di sekolah?','Apakah anak tidak menyimpan masalah sendiri?','Apakah anak berani bilang jika ada masalah?','Apakah anak mau menceritakan perasaannya?','Apakah anak tidak takut bicara dengan orang tua?']],
            ['skill_key' => 'olahraga_teratur', 'skill_emoji' => '🏃', 'skill_title' => 'Olahraga Teratur', 'skill_desc' => 'Anak belajar aktif bergerak setiap hari.', 'skill_ages' => [2,3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['kesehatan'], 'skill_agama' => null, 'skill_color' => '#009688', 'skill_bg' => '#E0F2F1', 'skill_evaluasi' => ['Apakah anak aktif bergerak setiap hari?','Apakah anak senang bermain di luar?','Apakah anak tidak malas bergerak?','Apakah anak bisa berlari dan melompat dengan baik?','Apakah anak punya olahraga favorit?']],
            ['skill_key' => 'makan_sehat', 'skill_emoji' => '🥗', 'skill_title' => 'Makan Sehat', 'skill_desc' => 'Anak belajar memilih makanan bergizi.', 'skill_ages' => [2,3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['kesehatan'], 'skill_agama' => null, 'skill_color' => '#009688', 'skill_bg' => '#E0F2F1', 'skill_evaluasi' => ['Apakah anak mau makan sayur dan buah?','Apakah anak tidak terlalu banyak makanan manis?','Apakah anak sarapan sebelum beraktivitas?','Apakah anak minum air putih yang cukup?','Apakah anak tidak terlalu sering jajan sembarangan?']],
            ['skill_key' => 'tidur_cukup', 'skill_emoji' => '😴', 'skill_title' => 'Tidur Cukup', 'skill_desc' => 'Anak belajar tidur tepat waktu.', 'skill_ages' => [1,2,3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['kesehatan'], 'skill_agama' => null, 'skill_color' => '#009688', 'skill_bg' => '#E0F2F1', 'skill_evaluasi' => ['Apakah anak tidur tepat waktu?','Apakah anak tidak sering begadang?','Apakah anak bangun dengan segar di pagi hari?','Apakah anak punya rutinitas tidur yang teratur?','Apakah anak tidak terlalu lama main gadget sebelum tidur?']],
            ['skill_key' => 'kebersihan_lingkungan', 'skill_emoji' => '🌿', 'skill_title' => 'Kebersihan Lingkungan', 'skill_desc' => 'Anak belajar menjaga kebersihan sekitar.', 'skill_ages' => [3,4,5,6,7,8,9,10,11], 'skill_pilars' => ['kesehatan'], 'skill_agama' => null, 'skill_color' => '#009688', 'skill_bg' => '#E0F2F1', 'skill_evaluasi' => ['Apakah anak tidak membuang sampah sembarangan?','Apakah anak mau membersihkan lingkungan?','Apakah anak peduli dengan kebersihan taman?','Apakah anak tahu cara memilah sampah?','Apakah anak senang menanam tanaman?']],
        ];

        foreach ($skills as $s) {
            MasterSkill::updateOrCreate(['skill_key' => $s['skill_key']], $s);
        }
    }
}
